// Code generated by tools/gen. DO NOT EDIT.

package provider

import (
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/nicole-ashley/terraform-provider-matomo/internal/matomo"
)

type variableEtrackerconfigurationModel struct {
	typedVariableCommon
	EtrackerID           types.String   `tfsdk:"etracker_id"`
	EtrackerBlockCookies types.Bool     `tfsdk:"etracker_block_cookies"`
	EtrackerDNT          types.Bool     `tfsdk:"etracker_dnt"`
	Et_pagename          types.String   `tfsdk:"et_pagename"`
	Et_areas             types.String   `tfsdk:"et_areas"`
	Et_target            types.String   `tfsdk:"et_target"`
	Et_tval              types.String   `tfsdk:"et_tval"`
	Et_tonr              types.String   `tfsdk:"et_tonr"`
	Et_tsale             types.String   `tfsdk:"et_tsale"`
	Et_basket            types.String   `tfsdk:"et_basket"`
	Et_cust              types.String   `tfsdk:"et_cust"`
	CustomDimensions     []types.String `tfsdk:"custom_dimensions"`
}

func variableEtrackerconfigurationSchema() schema.Schema {
	return schema.Schema{
		Description: "Defines the configuration for eTracker Analytics to optimise data collection.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"container_id": schema.StringAttribute{
				Required:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
			},
			"name": schema.StringAttribute{
				Required: true,
			},
			"default_value": schema.StringAttribute{
				Optional:      true,
				Computed:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"etracker_id": schema.StringAttribute{
				Required:    true,
				Description: "Enter the eTracker ID of your website. This is located in your eTracker account under Administration > Setup/Tracking Code.",
			},
			"etracker_block_cookies": schema.BoolAttribute{
				Required: false,
				Optional: true,
				// Computed + UseStateForUnknown: Matomo can return a
				// non-empty default for this field even when it was never
				// sent (e.g. a boolean parameter defaulting to false
				// server-side), which a bare Optional attribute can't
				// reconcile against an unset (null) config without
				// reporting a spurious diff on every subsequent plan - see
				// NeedsBoolPlanModifierImport's doc comment in
				// tools/gen/emit.go. Skipped for List: the generated Go
				// field type is a bare []types.String, which can't
				// represent "the whole list is unknown" the way
				// Computed's plan semantics require (see
				// block_trigger_ids' comment above for the same
				// limitation and the confirmed failure it caused).
				Computed:      true,
				PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()},
				Description:   "",
			},
			"etracker_dnt": schema.BoolAttribute{
				Required: false,
				Optional: true,
				// Computed + UseStateForUnknown: Matomo can return a
				// non-empty default for this field even when it was never
				// sent (e.g. a boolean parameter defaulting to false
				// server-side), which a bare Optional attribute can't
				// reconcile against an unset (null) config without
				// reporting a spurious diff on every subsequent plan - see
				// NeedsBoolPlanModifierImport's doc comment in
				// tools/gen/emit.go. Skipped for List: the generated Go
				// field type is a bare []types.String, which can't
				// represent "the whole list is unknown" the way
				// Computed's plan semantics require (see
				// block_trigger_ids' comment above for the same
				// limitation and the confirmed failure it caused).
				Computed:      true,
				PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()},
				Description:   "",
			},
			"et_pagename": schema.StringAttribute{
				Required: false,
				Optional: true,
				// Computed + UseStateForUnknown: Matomo can return a
				// non-empty default for this field even when it was never
				// sent (e.g. a boolean parameter defaulting to false
				// server-side), which a bare Optional attribute can't
				// reconcile against an unset (null) config without
				// reporting a spurious diff on every subsequent plan - see
				// NeedsBoolPlanModifierImport's doc comment in
				// tools/gen/emit.go. Skipped for List: the generated Go
				// field type is a bare []types.String, which can't
				// represent "the whole list is unknown" the way
				// Computed's plan semantics require (see
				// block_trigger_ids' comment above for the same
				// limitation and the confirmed failure it caused).
				Computed:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
				Description:   "Set variable if you want to overwrite the default value",
			},
			"et_areas": schema.StringAttribute{
				Required: false,
				Optional: true,
				// Computed + UseStateForUnknown: Matomo can return a
				// non-empty default for this field even when it was never
				// sent (e.g. a boolean parameter defaulting to false
				// server-side), which a bare Optional attribute can't
				// reconcile against an unset (null) config without
				// reporting a spurious diff on every subsequent plan - see
				// NeedsBoolPlanModifierImport's doc comment in
				// tools/gen/emit.go. Skipped for List: the generated Go
				// field type is a bare []types.String, which can't
				// represent "the whole list is unknown" the way
				// Computed's plan semantics require (see
				// block_trigger_ids' comment above for the same
				// limitation and the confirmed failure it caused).
				Computed:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
				Description:   "Set variable if you want to overwrite the default value",
			},
			"et_target": schema.StringAttribute{
				Required: false,
				Optional: true,
				// Computed + UseStateForUnknown: Matomo can return a
				// non-empty default for this field even when it was never
				// sent (e.g. a boolean parameter defaulting to false
				// server-side), which a bare Optional attribute can't
				// reconcile against an unset (null) config without
				// reporting a spurious diff on every subsequent plan - see
				// NeedsBoolPlanModifierImport's doc comment in
				// tools/gen/emit.go. Skipped for List: the generated Go
				// field type is a bare []types.String, which can't
				// represent "the whole list is unknown" the way
				// Computed's plan semantics require (see
				// block_trigger_ids' comment above for the same
				// limitation and the confirmed failure it caused).
				Computed:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
				Description:   "Set variable if you want to overwrite the default value",
			},
			"et_tval": schema.StringAttribute{
				Required: false,
				Optional: true,
				// Computed + UseStateForUnknown: Matomo can return a
				// non-empty default for this field even when it was never
				// sent (e.g. a boolean parameter defaulting to false
				// server-side), which a bare Optional attribute can't
				// reconcile against an unset (null) config without
				// reporting a spurious diff on every subsequent plan - see
				// NeedsBoolPlanModifierImport's doc comment in
				// tools/gen/emit.go. Skipped for List: the generated Go
				// field type is a bare []types.String, which can't
				// represent "the whole list is unknown" the way
				// Computed's plan semantics require (see
				// block_trigger_ids' comment above for the same
				// limitation and the confirmed failure it caused).
				Computed:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
				Description:   "Set variable if you want to overwrite the default value",
			},
			"et_tonr": schema.StringAttribute{
				Required: false,
				Optional: true,
				// Computed + UseStateForUnknown: Matomo can return a
				// non-empty default for this field even when it was never
				// sent (e.g. a boolean parameter defaulting to false
				// server-side), which a bare Optional attribute can't
				// reconcile against an unset (null) config without
				// reporting a spurious diff on every subsequent plan - see
				// NeedsBoolPlanModifierImport's doc comment in
				// tools/gen/emit.go. Skipped for List: the generated Go
				// field type is a bare []types.String, which can't
				// represent "the whole list is unknown" the way
				// Computed's plan semantics require (see
				// block_trigger_ids' comment above for the same
				// limitation and the confirmed failure it caused).
				Computed:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
				Description:   "Set variable if you want to overwrite the default value",
			},
			"et_tsale": schema.StringAttribute{
				Required: false,
				Optional: true,
				// Computed + UseStateForUnknown: Matomo can return a
				// non-empty default for this field even when it was never
				// sent (e.g. a boolean parameter defaulting to false
				// server-side), which a bare Optional attribute can't
				// reconcile against an unset (null) config without
				// reporting a spurious diff on every subsequent plan - see
				// NeedsBoolPlanModifierImport's doc comment in
				// tools/gen/emit.go. Skipped for List: the generated Go
				// field type is a bare []types.String, which can't
				// represent "the whole list is unknown" the way
				// Computed's plan semantics require (see
				// block_trigger_ids' comment above for the same
				// limitation and the confirmed failure it caused).
				Computed:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
				Description:   "Set variable if you want to overwrite the default value",
			},
			"et_basket": schema.StringAttribute{
				Required: false,
				Optional: true,
				// Computed + UseStateForUnknown: Matomo can return a
				// non-empty default for this field even when it was never
				// sent (e.g. a boolean parameter defaulting to false
				// server-side), which a bare Optional attribute can't
				// reconcile against an unset (null) config without
				// reporting a spurious diff on every subsequent plan - see
				// NeedsBoolPlanModifierImport's doc comment in
				// tools/gen/emit.go. Skipped for List: the generated Go
				// field type is a bare []types.String, which can't
				// represent "the whole list is unknown" the way
				// Computed's plan semantics require (see
				// block_trigger_ids' comment above for the same
				// limitation and the confirmed failure it caused).
				Computed:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
				Description:   "Set variable if you want to overwrite the default value",
			},
			"et_cust": schema.StringAttribute{
				Required: false,
				Optional: true,
				// Computed + UseStateForUnknown: Matomo can return a
				// non-empty default for this field even when it was never
				// sent (e.g. a boolean parameter defaulting to false
				// server-side), which a bare Optional attribute can't
				// reconcile against an unset (null) config without
				// reporting a spurious diff on every subsequent plan - see
				// NeedsBoolPlanModifierImport's doc comment in
				// tools/gen/emit.go. Skipped for List: the generated Go
				// field type is a bare []types.String, which can't
				// represent "the whole list is unknown" the way
				// Computed's plan semantics require (see
				// block_trigger_ids' comment above for the same
				// limitation and the confirmed failure it caused).
				Computed:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
				Description:   "Set variable if you want to overwrite the default value",
			},
			"custom_dimensions": schema.ListAttribute{
				ElementType: types.StringType,
				Required:    false,
				Optional:    true,
				Description: "Optionally set one or multiple custom dimensions.",
			},
		},
	}
}

func (m *variableEtrackerconfigurationModel) Meta() typedMeta {
	return typedMeta{
		TypeID:       "EtrackerConfiguration",
		ResourceName: "matomo_tagmanager_variable_etrackerconfiguration",
		Schema:       variableEtrackerconfigurationSchema(),
	}
}

// ToParams only includes a key for an Optional parameter when it's
// actually set - sending an empty string for an unset Optional field
// (rather than omitting the key) was rejected by Matomo's own validation
// on live enum/format-constrained parameters (confirmed against a real
// acceptance-test run: an unset htmlPosition sent as "" was rejected by
// CustomHtml's own field validator, which never happens for a key that's
// simply absent from the parameters map). A List-typed parameter is sent
// via matomo.ListParam, never joined into a single string - see
// matomo.ParamValue's doc comment for why.
func (m *variableEtrackerconfigurationModel) ToParams() matomo.ParamsMap {
	p := matomo.ParamsMap{}
	p["etrackerID"] = matomo.ScalarParam(m.EtrackerID.ValueString())
	if !m.EtrackerBlockCookies.IsNull() && !m.EtrackerBlockCookies.IsUnknown() {
		p["etrackerBlockCookies"] = matomo.ScalarParam(paramBoolString(m.EtrackerBlockCookies.ValueBool()))
	}
	if !m.EtrackerDNT.IsNull() && !m.EtrackerDNT.IsUnknown() {
		p["etrackerDNT"] = matomo.ScalarParam(paramBoolString(m.EtrackerDNT.ValueBool()))
	}
	if !m.Et_pagename.IsNull() && !m.Et_pagename.IsUnknown() {
		p["et_pagename"] = matomo.ScalarParam(m.Et_pagename.ValueString())
	}
	if !m.Et_areas.IsNull() && !m.Et_areas.IsUnknown() {
		p["et_areas"] = matomo.ScalarParam(m.Et_areas.ValueString())
	}
	if !m.Et_target.IsNull() && !m.Et_target.IsUnknown() {
		p["et_target"] = matomo.ScalarParam(m.Et_target.ValueString())
	}
	if !m.Et_tval.IsNull() && !m.Et_tval.IsUnknown() {
		p["et_tval"] = matomo.ScalarParam(m.Et_tval.ValueString())
	}
	if !m.Et_tonr.IsNull() && !m.Et_tonr.IsUnknown() {
		p["et_tonr"] = matomo.ScalarParam(m.Et_tonr.ValueString())
	}
	if !m.Et_tsale.IsNull() && !m.Et_tsale.IsUnknown() {
		p["et_tsale"] = matomo.ScalarParam(m.Et_tsale.ValueString())
	}
	if !m.Et_basket.IsNull() && !m.Et_basket.IsUnknown() {
		p["et_basket"] = matomo.ScalarParam(m.Et_basket.ValueString())
	}
	if !m.Et_cust.IsNull() && !m.Et_cust.IsUnknown() {
		p["et_cust"] = matomo.ScalarParam(m.Et_cust.ValueString())
	}
	if m.CustomDimensions != nil {
		p["customDimensions"] = matomo.ListParam(stringSliceFromModel(m.CustomDimensions))
	}
	return p
}

// FromParams mirrors ToParams' omission convention on the way back: a key
// absent from Matomo's response (an unset Optional parameter) must decode
// to a null value, not a zero value ("", false, 0) - decoding it to a
// zero value made every unset Optional parameter round-trip as a
// non-null empty value, which never matched the null the config itself
// produced and left Terraform reporting a perpetual "refresh plan not
// empty" diff on every generated resource with an unset Optional field
// (confirmed against a real acceptance-test run).
func (m *variableEtrackerconfigurationModel) FromParams(p matomo.ParamsMap) {
	m.EtrackerID = types.StringValue(p["etrackerID"].Scalar)
	if v, ok := p["etrackerBlockCookies"]; ok {
		m.EtrackerBlockCookies = types.BoolValue(paramBoolValue(v.Scalar))
	} else {
		m.EtrackerBlockCookies = types.BoolNull()
	}
	if v, ok := p["etrackerDNT"]; ok {
		m.EtrackerDNT = types.BoolValue(paramBoolValue(v.Scalar))
	} else {
		m.EtrackerDNT = types.BoolNull()
	}
	if v, ok := p["et_pagename"]; ok {
		m.Et_pagename = types.StringValue(v.Scalar)
	} else {
		m.Et_pagename = types.StringNull()
	}
	if v, ok := p["et_areas"]; ok {
		m.Et_areas = types.StringValue(v.Scalar)
	} else {
		m.Et_areas = types.StringNull()
	}
	if v, ok := p["et_target"]; ok {
		m.Et_target = types.StringValue(v.Scalar)
	} else {
		m.Et_target = types.StringNull()
	}
	if v, ok := p["et_tval"]; ok {
		m.Et_tval = types.StringValue(v.Scalar)
	} else {
		m.Et_tval = types.StringNull()
	}
	if v, ok := p["et_tonr"]; ok {
		m.Et_tonr = types.StringValue(v.Scalar)
	} else {
		m.Et_tonr = types.StringNull()
	}
	if v, ok := p["et_tsale"]; ok {
		m.Et_tsale = types.StringValue(v.Scalar)
	} else {
		m.Et_tsale = types.StringNull()
	}
	if v, ok := p["et_basket"]; ok {
		m.Et_basket = types.StringValue(v.Scalar)
	} else {
		m.Et_basket = types.StringNull()
	}
	if v, ok := p["et_cust"]; ok {
		m.Et_cust = types.StringValue(v.Scalar)
	} else {
		m.Et_cust = types.StringNull()
	}
	if v, ok := p["customDimensions"]; ok {
		m.CustomDimensions = paramListValue(v.List)
	} else {
		m.CustomDimensions = nil
	}
}

func (m *variableEtrackerconfigurationModel) Common() *typedVariableCommon {
	return &m.typedVariableCommon
}

func newVariableEtrackerconfigurationModel() typedVariableModel {
	return &variableEtrackerconfigurationModel{}
}
