// Code generated by tools/gen. DO NOT EDIT.

package provider

import (
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type variableUrlModel struct {
	typedVariableCommon
	UrlPart types.String `tfsdk:"url_part"`
}

func variableUrlSchema() schema.Schema {
	return schema.Schema{
		Description: "Gets the value of the current page URL.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"container_id": schema.StringAttribute{
				Required:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
			},
			"name": schema.StringAttribute{
				Required: true,
			},
			"default_value": schema.StringAttribute{
				Optional:      true,
				Computed:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"url_part": schema.StringAttribute{
				Required:    true,
				Description: "Select the part of the URL you want to retrieve.",
				Validators: []validator.String{
					stringvalidator.OneOf("hash", "host", "hostname", "href", "origin", "pathname", "port", "protocol", "search"),
				},
			},
		},
	}
}

func (m *variableUrlModel) Meta() typedMeta {
	return typedMeta{
		TypeID:       "Url",
		ResourceName: "matomo_tagmanager_variable_url",
		Schema:       variableUrlSchema(),
	}
}

// ToParams only includes a key for an Optional parameter when it's
// actually set - sending an empty string for an unset Optional field
// (rather than omitting the key) was rejected by Matomo's own validation
// on live enum/format-constrained parameters (confirmed against a real
// acceptance-test run: an unset htmlPosition sent as "" was rejected by
// CustomHtml's own field validator, which never happens for a key that's
// simply absent from the parameters map).
func (m *variableUrlModel) ToParams() map[string]string {
	p := map[string]string{}
	p["urlPart"] = m.UrlPart.ValueString()
	return p
}

// FromParams mirrors ToParams' omission convention on the way back: a key
// absent from Matomo's response (an unset Optional parameter) must decode
// to a null value, not a zero value ("", false, 0) - decoding it to a
// zero value made every unset Optional parameter round-trip as a
// non-null empty value, which never matched the null the config itself
// produced and left Terraform reporting a perpetual "refresh plan not
// empty" diff on every generated resource with an unset Optional field
// (confirmed against a real acceptance-test run).
func (m *variableUrlModel) FromParams(p map[string]string) {
	m.UrlPart = types.StringValue(p["urlPart"])
}

func (m *variableUrlModel) Common() *typedVariableCommon {
	return &m.typedVariableCommon
}

func newVariableUrlModel() typedVariableModel {
	return &variableUrlModel{}
}
