// Code generated by tools/gen. DO NOT EDIT.

package provider

import (
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type tagLinkedininsightModel struct {
	typedTagCommon
	PartnerId    types.String `tfsdk:"partner_id"`
	ConversionId types.String `tfsdk:"conversion_id"`
}

func tagLinkedininsightSchema() schema.Schema {
	return schema.Schema{
		Description: "Adds the LinkedIn Insight Tag so you can apply conversion tracking to your LinkedIn ad campaigns.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"container_id": schema.StringAttribute{
				Required:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
			},
			"name": schema.StringAttribute{
				Required: true,
			},
			"status": schema.StringAttribute{
				Optional:      true,
				Computed:      true,
				Validators:    []validator.String{stringvalidator.OneOf("active", "paused")},
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"fire_trigger_ids": schema.ListAttribute{
				Required:    true,
				ElementType: types.StringType,
			},
			"block_trigger_ids": schema.ListAttribute{
				Optional:    true,
				ElementType: types.StringType,
			},
			"partner_id": schema.StringAttribute{
				Required:    true,
				Description: "You can find the partner ID by logging into your LinkedIn Campaign Manager, and clicking on \"Account Assets\" followed by \"Insight Tag\". If \"Insight Tag\" is not available, please set up the Insight Tag by clicking on \"Conversion Tracking\". There you can enter a domain and continue the set up. You will find the partner ID in the line `_linkedin_partner_id = \"123456\"`. In this example the ID would be \"123456\".",
			},
			"conversion_id": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Description: "An optional conversion ID if you would like a specific conversion recorded when this tag executes.",
			},
		},
	}
}

func (m *tagLinkedininsightModel) Meta() typedMeta {
	return typedMeta{
		TypeID:       "LinkedinInsight",
		ResourceName: "matomo_tagmanager_tag_linkedininsight",
		Schema:       tagLinkedininsightSchema(),
	}
}

// ToParams only includes a key for an Optional parameter when it's
// actually set - sending an empty string for an unset Optional field
// (rather than omitting the key) was rejected by Matomo's own validation
// on live enum/format-constrained parameters (confirmed against a real
// acceptance-test run: an unset htmlPosition sent as "" was rejected by
// CustomHtml's own field validator, which never happens for a key that's
// simply absent from the parameters map).
func (m *tagLinkedininsightModel) ToParams() map[string]string {
	p := map[string]string{}
	p["partnerId"] = m.PartnerId.ValueString()
	if !m.ConversionId.IsNull() && !m.ConversionId.IsUnknown() {
		p["conversionId"] = m.ConversionId.ValueString()
	}
	return p
}

func (m *tagLinkedininsightModel) FromParams(p map[string]string) {
	m.PartnerId = types.StringValue(p["partnerId"])
	m.ConversionId = types.StringValue(p["conversionId"])
}

func (m *tagLinkedininsightModel) Common() *typedTagCommon {
	return &m.typedTagCommon
}

func newTagLinkedininsightModel() typedTagModel {
	return &tagLinkedininsightModel{}
}
