// Code generated by tools/gen. DO NOT EDIT.

package provider

import (
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/listplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type tagHoneybadgerModel struct {
	typedTagCommon
	HoneybadgerApiKey      types.String `tfsdk:"honeybadger_api_key"`
	HoneybadgerEnvironment types.String `tfsdk:"honeybadger_environment"`
	HoneybadgerRevision    types.String `tfsdk:"honeybadger_revision"`
}

func tagHoneybadgerSchema() schema.Schema {
	return schema.Schema{
		Description: "Exception and Uptime Monitoring for Application Developers",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"container_id": schema.StringAttribute{
				Required:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
			},
			"name": schema.StringAttribute{
				Required: true,
			},
			"status": schema.StringAttribute{
				Optional:      true,
				Computed:      true,
				Validators:    []validator.String{stringvalidator.OneOf("active", "paused")},
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"fire_trigger_ids": schema.ListAttribute{
				Required:    true,
				ElementType: types.StringType,
			},
			"block_trigger_ids": schema.ListAttribute{
				Optional:      true,
				Computed:      true,
				ElementType:   types.StringType,
				PlanModifiers: []planmodifier.List{listplanmodifier.UseStateForUnknown()},
			},
			"honeybadger_api_key": schema.StringAttribute{
				Required:    true,
				Description: "The apiKey of your honeybadger project",
			},
			"honeybadger_environment": schema.StringAttribute{
				Required: false,
				Optional: true,
				// Computed + UseStateForUnknown: Matomo can return a
				// non-empty default for this field even when it was never
				// sent (e.g. a boolean parameter defaulting to false
				// server-side), which a bare Optional attribute can't
				// reconcile against an unset (null) config without
				// reporting a spurious diff on every subsequent plan - see
				// NeedsBoolPlanModifierImport's doc comment in
				// tools/gen/emit.go.
				Computed:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
				Description:   "The environment where the container is included (production, dev, etc.). Leave empty to default to the environment of this container.",
			},
			"honeybadger_revision": schema.StringAttribute{
				Required: false,
				Optional: true,
				// Computed + UseStateForUnknown: Matomo can return a
				// non-empty default for this field even when it was never
				// sent (e.g. a boolean parameter defaulting to false
				// server-side), which a bare Optional attribute can't
				// reconcile against an unset (null) config without
				// reporting a spurious diff on every subsequent plan - see
				// NeedsBoolPlanModifierImport's doc comment in
				// tools/gen/emit.go.
				Computed:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
				Description:   "(optional) the version of your project",
			},
		},
	}
}

func (m *tagHoneybadgerModel) Meta() typedMeta {
	return typedMeta{
		TypeID:       "Honeybadger",
		ResourceName: "matomo_tagmanager_tag_honeybadger",
		Schema:       tagHoneybadgerSchema(),
	}
}

// ToParams only includes a key for an Optional parameter when it's
// actually set - sending an empty string for an unset Optional field
// (rather than omitting the key) was rejected by Matomo's own validation
// on live enum/format-constrained parameters (confirmed against a real
// acceptance-test run: an unset htmlPosition sent as "" was rejected by
// CustomHtml's own field validator, which never happens for a key that's
// simply absent from the parameters map).
func (m *tagHoneybadgerModel) ToParams() map[string]string {
	p := map[string]string{}
	p["honeybadgerApiKey"] = m.HoneybadgerApiKey.ValueString()
	if !m.HoneybadgerEnvironment.IsNull() && !m.HoneybadgerEnvironment.IsUnknown() {
		p["honeybadgerEnvironment"] = m.HoneybadgerEnvironment.ValueString()
	}
	if !m.HoneybadgerRevision.IsNull() && !m.HoneybadgerRevision.IsUnknown() {
		p["honeybadgerRevision"] = m.HoneybadgerRevision.ValueString()
	}
	return p
}

// FromParams mirrors ToParams' omission convention on the way back: a key
// absent from Matomo's response (an unset Optional parameter) must decode
// to a null value, not a zero value ("", false, 0) - decoding it to a
// zero value made every unset Optional parameter round-trip as a
// non-null empty value, which never matched the null the config itself
// produced and left Terraform reporting a perpetual "refresh plan not
// empty" diff on every generated resource with an unset Optional field
// (confirmed against a real acceptance-test run).
func (m *tagHoneybadgerModel) FromParams(p map[string]string) {
	m.HoneybadgerApiKey = types.StringValue(p["honeybadgerApiKey"])
	if v, ok := p["honeybadgerEnvironment"]; ok {
		m.HoneybadgerEnvironment = types.StringValue(v)
	} else {
		m.HoneybadgerEnvironment = types.StringNull()
	}
	if v, ok := p["honeybadgerRevision"]; ok {
		m.HoneybadgerRevision = types.StringValue(v)
	} else {
		m.HoneybadgerRevision = types.StringNull()
	}
}

func (m *tagHoneybadgerModel) Common() *typedTagCommon {
	return &m.typedTagCommon
}

func newTagHoneybadgerModel() typedTagModel {
	return &tagHoneybadgerModel{}
}
