// Code generated by tools/gen. DO NOT EDIT.

package provider

import (
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/listplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type tagCookieyesModel struct {
	typedTagCommon
	CookieYesWebsiteKey types.String `tfsdk:"cookie_yes_website_key"`
}

func tagCookieyesSchema() schema.Schema {
	return schema.Schema{
		Description: "CookieYes is a cookie consent solution that helps your website achieve GDPR and CCPA compliance.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"container_id": schema.StringAttribute{
				Required:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
			},
			"name": schema.StringAttribute{
				Required: true,
			},
			"status": schema.StringAttribute{
				Optional:      true,
				Computed:      true,
				Validators:    []validator.String{stringvalidator.OneOf("active", "paused")},
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"fire_trigger_ids": schema.ListAttribute{
				Required:    true,
				ElementType: types.StringType,
			},
			"block_trigger_ids": schema.ListAttribute{
				Optional:      true,
				Computed:      true,
				ElementType:   types.StringType,
				PlanModifiers: []planmodifier.List{listplanmodifier.UseStateForUnknown()},
			},
			"cookie_yes_website_key": schema.StringAttribute{
				Required:    true,
				Description: "",
			},
		},
	}
}

func (m *tagCookieyesModel) Meta() typedMeta {
	return typedMeta{
		TypeID:       "CookieYes",
		ResourceName: "matomo_tagmanager_tag_cookieyes",
		Schema:       tagCookieyesSchema(),
	}
}

// ToParams only includes a key for an Optional parameter when it's
// actually set - sending an empty string for an unset Optional field
// (rather than omitting the key) was rejected by Matomo's own validation
// on live enum/format-constrained parameters (confirmed against a real
// acceptance-test run: an unset htmlPosition sent as "" was rejected by
// CustomHtml's own field validator, which never happens for a key that's
// simply absent from the parameters map).
func (m *tagCookieyesModel) ToParams() map[string]string {
	p := map[string]string{}
	p["cookieYesWebsiteKey"] = m.CookieYesWebsiteKey.ValueString()
	return p
}

// FromParams mirrors ToParams' omission convention on the way back: a key
// absent from Matomo's response (an unset Optional parameter) must decode
// to a null value, not a zero value ("", false, 0) - decoding it to a
// zero value made every unset Optional parameter round-trip as a
// non-null empty value, which never matched the null the config itself
// produced and left Terraform reporting a perpetual "refresh plan not
// empty" diff on every generated resource with an unset Optional field
// (confirmed against a real acceptance-test run).
func (m *tagCookieyesModel) FromParams(p map[string]string) {
	m.CookieYesWebsiteKey = types.StringValue(p["cookieYesWebsiteKey"])
}

func (m *tagCookieyesModel) Common() *typedTagCommon {
	return &m.typedTagCommon
}

func newTagCookieyesModel() typedTagModel {
	return &tagCookieyesModel{}
}
