// Code generated by tools/gen. DO NOT EDIT.

package provider

import (
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type tagZendeskchatModel struct {
	ID              types.String   `tfsdk:"id"`
	ContainerID     types.String   `tfsdk:"container_id"`
	Name            types.String   `tfsdk:"name"`
	Status          types.String   `tfsdk:"status"`
	FireTriggerIDs  []types.String `tfsdk:"fire_trigger_ids"`
	BlockTriggerIDs []types.String `tfsdk:"block_trigger_ids"`
	ZendeskChatId   types.String   `tfsdk:"zendesk_chat_id"`
}

func tagZendeskchatSchema() schema.Schema {
	return schema.Schema{
		Description: "Reach your customers, instantly via web, mobile, and messaging.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"container_id": schema.StringAttribute{
				Required:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
			},
			"name": schema.StringAttribute{
				Required: true,
			},
			"status": schema.StringAttribute{
				Optional:      true,
				Computed:      true,
				Validators:    []validator.String{stringvalidator.OneOf("active", "paused")},
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"fire_trigger_ids": schema.ListAttribute{
				Required:    true,
				ElementType: types.StringType,
			},
			"block_trigger_ids": schema.ListAttribute{
				Optional:    true,
				ElementType: types.StringType,
			},
			"zendesk_chat_id": schema.StringAttribute{
				Required:    true,
				Description: "You can get the Site ID by logging into Zendesk Chat, going to \"Settings\" and clicking on \"Widget\". The Site ID has typically about 32 characters and is the text coming directly after \"https://v2.zopim.com/?\", for example \"123451c27295ad739e46b6b1\".",
			},
		},
	}
}

func (m *tagZendeskchatModel) Meta() typedMeta {
	return typedMeta{
		TypeID:       "ZendeskChat",
		ResourceName: "matomo_tagmanager_tag_zendeskchat",
		Schema:       tagZendeskchatSchema(),
	}
}

func (m *tagZendeskchatModel) ToParams() map[string]string {
	return map[string]string{
		"zendeskChatId": m.ZendeskChatId.ValueString(),
	}
}

func (m *tagZendeskchatModel) FromParams(p map[string]string) {
	m.ZendeskChatId = types.StringValue(p["zendeskChatId"])
}

func newTagZendeskchatModel() typedModel {
	return &tagZendeskchatModel{}
}
