// Code generated by tools/gen. DO NOT EDIT.

package provider

import (
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type tagShareaholicModel struct {
	typedTagCommon
	ShareaholicSiteId         types.String `tfsdk:"shareaholic_site_id"`
	ShareaholicInPageApp      types.String `tfsdk:"shareaholic_in_page_app"`
	ShareaholicAppId          types.String `tfsdk:"shareaholic_app_id"`
	ShareaholicParentSelector types.String `tfsdk:"shareaholic_parent_selector"`
}

func tagShareaholicSchema() schema.Schema {
	return schema.Schema{
		Description: "Content Marketing Platform & Website Traffic Tools",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"container_id": schema.StringAttribute{
				Required:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
			},
			"name": schema.StringAttribute{
				Required: true,
			},
			"status": schema.StringAttribute{
				Optional:      true,
				Computed:      true,
				Validators:    []validator.String{stringvalidator.OneOf("active", "paused")},
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"fire_trigger_ids": schema.ListAttribute{
				Required:    true,
				ElementType: types.StringType,
			},
			"block_trigger_ids": schema.ListAttribute{
				// Not Computed, unlike the other common/generated Optional
				// attributes: the generated Go field type for a List
				// attribute is a bare []types.String (see the Params
				// range below), which - unlike types.List - has no way to
				// represent "the whole list is unknown," so marking it
				// Computed makes terraform-plugin-framework fail outright
				// trying to decode plan's Unknown value into it
				// (confirmed against a real acceptance-test run: "Value
				// Conversion Error ... Received unknown value, however
				// the target type cannot handle unknown values"). A
				// List-typed field can still show a spurious
				// "refresh plan not empty" diff if Matomo defaults it to
				// a non-empty value server-side - fixing that for real
				// would mean switching the generated field type to
				// types.List, which is a larger change than this pass
				// covers.
				Optional:    true,
				ElementType: types.StringType,
			},
			"shareaholic_site_id": schema.StringAttribute{
				Required:    true,
				Description: "Create a new site in Shareaholic and paste the site ID here",
			},
			"shareaholic_in_page_app": schema.StringAttribute{
				Required: false,
				Optional: true,
				// Computed + UseStateForUnknown: Matomo can return a
				// non-empty default for this field even when it was never
				// sent (e.g. a boolean parameter defaulting to false
				// server-side), which a bare Optional attribute can't
				// reconcile against an unset (null) config without
				// reporting a spurious diff on every subsequent plan - see
				// NeedsBoolPlanModifierImport's doc comment in
				// tools/gen/emit.go. Skipped for List: the generated Go
				// field type is a bare []types.String, which can't
				// represent "the whole list is unknown" the way
				// Computed's plan semantics require (see
				// block_trigger_ids' comment above for the same
				// limitation and the confirmed failure it caused).
				Computed:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
				Description:   "Here you can optionally add an In-Page App to your website.",
				Validators: []validator.String{
					stringvalidator.OneOf("", "follow_buttons", "recommendations", "share_buttons", "total_share_count"),
				},
			},
			"shareaholic_app_id": schema.StringAttribute{
				Required: false,
				Optional: true,
				// Computed + UseStateForUnknown: Matomo can return a
				// non-empty default for this field even when it was never
				// sent (e.g. a boolean parameter defaulting to false
				// server-side), which a bare Optional attribute can't
				// reconcile against an unset (null) config without
				// reporting a spurious diff on every subsequent plan - see
				// NeedsBoolPlanModifierImport's doc comment in
				// tools/gen/emit.go. Skipped for List: the generated Go
				// field type is a bare []types.String, which can't
				// represent "the whole list is unknown" the way
				// Computed's plan semantics require (see
				// block_trigger_ids' comment above for the same
				// limitation and the confirmed failure it caused).
				Computed:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
				Description:   "If you want to add an In-Page App enter the App ID here. It is about eight digits long. The App ID is not required for the Total Share Counter.",
			},
			"shareaholic_parent_selector": schema.StringAttribute{
				Required: false,
				Optional: true,
				// Computed + UseStateForUnknown: Matomo can return a
				// non-empty default for this field even when it was never
				// sent (e.g. a boolean parameter defaulting to false
				// server-side), which a bare Optional attribute can't
				// reconcile against an unset (null) config without
				// reporting a spurious diff on every subsequent plan - see
				// NeedsBoolPlanModifierImport's doc comment in
				// tools/gen/emit.go. Skipped for List: the generated Go
				// field type is a bare []types.String, which can't
				// represent "the whole list is unknown" the way
				// Computed's plan semantics require (see
				// block_trigger_ids' comment above for the same
				// limitation and the confirmed failure it caused).
				Computed:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
				Description:   "Enter a CSS selector to the element where the In-Page App should be added.",
			},
		},
	}
}

func (m *tagShareaholicModel) Meta() typedMeta {
	return typedMeta{
		TypeID:       "Shareaholic",
		ResourceName: "matomo_tagmanager_tag_shareaholic",
		Schema:       tagShareaholicSchema(),
	}
}

// ToParams only includes a key for an Optional parameter when it's
// actually set - sending an empty string for an unset Optional field
// (rather than omitting the key) was rejected by Matomo's own validation
// on live enum/format-constrained parameters (confirmed against a real
// acceptance-test run: an unset htmlPosition sent as "" was rejected by
// CustomHtml's own field validator, which never happens for a key that's
// simply absent from the parameters map).
func (m *tagShareaholicModel) ToParams() map[string]string {
	p := map[string]string{}
	p["shareaholicSiteId"] = m.ShareaholicSiteId.ValueString()
	if !m.ShareaholicInPageApp.IsNull() && !m.ShareaholicInPageApp.IsUnknown() {
		p["shareaholicInPageApp"] = m.ShareaholicInPageApp.ValueString()
	}
	if !m.ShareaholicAppId.IsNull() && !m.ShareaholicAppId.IsUnknown() {
		p["shareaholicAppId"] = m.ShareaholicAppId.ValueString()
	}
	if !m.ShareaholicParentSelector.IsNull() && !m.ShareaholicParentSelector.IsUnknown() {
		p["shareaholicParentSelector"] = m.ShareaholicParentSelector.ValueString()
	}
	return p
}

// FromParams mirrors ToParams' omission convention on the way back: a key
// absent from Matomo's response (an unset Optional parameter) must decode
// to a null value, not a zero value ("", false, 0) - decoding it to a
// zero value made every unset Optional parameter round-trip as a
// non-null empty value, which never matched the null the config itself
// produced and left Terraform reporting a perpetual "refresh plan not
// empty" diff on every generated resource with an unset Optional field
// (confirmed against a real acceptance-test run).
func (m *tagShareaholicModel) FromParams(p map[string]string) {
	m.ShareaholicSiteId = types.StringValue(p["shareaholicSiteId"])
	if v, ok := p["shareaholicInPageApp"]; ok {
		m.ShareaholicInPageApp = types.StringValue(v)
	} else {
		m.ShareaholicInPageApp = types.StringNull()
	}
	if v, ok := p["shareaholicAppId"]; ok {
		m.ShareaholicAppId = types.StringValue(v)
	} else {
		m.ShareaholicAppId = types.StringNull()
	}
	if v, ok := p["shareaholicParentSelector"]; ok {
		m.ShareaholicParentSelector = types.StringValue(v)
	} else {
		m.ShareaholicParentSelector = types.StringNull()
	}
}

func (m *tagShareaholicModel) Common() *typedTagCommon {
	return &m.typedTagCommon
}

func newTagShareaholicModel() typedTagModel {
	return &tagShareaholicModel{}
}
