// Code generated by tools/gen. DO NOT EDIT.

package provider

import (
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type triggerWindowloadedModel struct {
	typedTriggerCommon
}

func triggerWindowloadedSchema() schema.Schema {
	return schema.Schema{
		Description: "Triggered when the page is fully loaded including all images etc.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"container_id": schema.StringAttribute{
				Required:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
			},
			"name": schema.StringAttribute{
				Required: true,
			},
		},
	}
}

func (m *triggerWindowloadedModel) Meta() typedMeta {
	return typedMeta{
		TypeID:       "WindowLoaded",
		ResourceName: "matomo_tagmanager_trigger_windowloaded",
		Schema:       triggerWindowloadedSchema(),
	}
}

func (m *triggerWindowloadedModel) ToParams() map[string]string {
	return map[string]string{}
}

func (m *triggerWindowloadedModel) FromParams(p map[string]string) {
}

func (m *triggerWindowloadedModel) Common() *typedTriggerCommon {
	return &m.typedTriggerCommon
}

func newTriggerWindowloadedModel() typedTriggerModel {
	return &triggerWindowloadedModel{}
}
