// Code generated by tools/gen. DO NOT EDIT.

package provider

import (
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type variableMetacontentModel struct {
	typedVariableCommon
	MetaName types.String `tfsdk:"meta_name"`
}

func variableMetacontentSchema() schema.Schema {
	return schema.Schema{
		Description: "Reads a value from a \"meta\" HTML element.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"container_id": schema.StringAttribute{
				Required:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
			},
			"name": schema.StringAttribute{
				Required: true,
			},
			"default_value": schema.StringAttribute{
				Optional: true,
			},
			"meta_name": schema.StringAttribute{
				Required:    true,
				Description: "",
				Validators:  []validator.String{stringvalidator.OneOf("application-name", "author", "content-type", "copyright", "description", "generator", "keywords", "language", "og:description", "og:image", "og:locale", "og:site_name", "og:title", "og:type", "og:url", "robots", "subject", "viewport")},
			},
		},
	}
}

func (m *variableMetacontentModel) Meta() typedMeta {
	return typedMeta{
		TypeID:       "MetaContent",
		ResourceName: "matomo_tagmanager_variable_metacontent",
		Schema:       variableMetacontentSchema(),
	}
}

// ToParams only includes a key for an Optional parameter when it's
// actually set - sending an empty string for an unset Optional field
// (rather than omitting the key) was rejected by Matomo's own validation
// on live enum/format-constrained parameters (confirmed against a real
// acceptance-test run: an unset htmlPosition sent as "" was rejected by
// CustomHtml's own field validator, which never happens for a key that's
// simply absent from the parameters map).
func (m *variableMetacontentModel) ToParams() map[string]string {
	p := map[string]string{}
	p["metaName"] = m.MetaName.ValueString()
	return p
}

func (m *variableMetacontentModel) FromParams(p map[string]string) {
	m.MetaName = types.StringValue(p["metaName"])
}

func (m *variableMetacontentModel) Common() *typedVariableCommon {
	return &m.typedVariableCommon
}

func newVariableMetacontentModel() typedVariableModel {
	return &variableMetacontentModel{}
}
