// Code generated by tools/gen. DO NOT EDIT.

package provider

import (
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type variableMatomoconfigurationModel struct {
	typedVariableCommon
	MatomoUrl                             types.String   `tfsdk:"matomo_url"`
	IdSite                                types.String   `tfsdk:"id_site"`
	EnableLinkTracking                    types.Bool     `tfsdk:"enable_link_tracking"`
	EnableFileTracking                    types.Bool     `tfsdk:"enable_file_tracking"`
	EnableCrossDomainLinking              types.Bool     `tfsdk:"enable_cross_domain_linking"`
	CrossDomainLinkingTimeout             types.Int64    `tfsdk:"cross_domain_linking_timeout"`
	EnableDoNotTrack                      types.Bool     `tfsdk:"enable_do_not_track"`
	DisablePerformanceTracking            types.Bool     `tfsdk:"disable_performance_tracking"`
	EnableJSErrorTracking                 types.Bool     `tfsdk:"enable_js_error_tracking"`
	EnableHeartBeatTimer                  types.Bool     `tfsdk:"enable_heart_beat_timer"`
	HeartBeatTime                         types.Int64    `tfsdk:"heart_beat_time"`
	TrackAllContentImpressions            types.Bool     `tfsdk:"track_all_content_impressions"`
	TrackVisibleContentImpressions        types.Bool     `tfsdk:"track_visible_content_impressions"`
	TrackBots                             types.Bool     `tfsdk:"track_bots"`
	DisableCookies                        types.Bool     `tfsdk:"disable_cookies"`
	RequireConsent                        types.Bool     `tfsdk:"require_consent"`
	RequireCookieConsent                  types.Bool     `tfsdk:"require_cookie_consent"`
	CustomCookieTimeOutEnable             types.Bool     `tfsdk:"custom_cookie_time_out_enable"`
	CustomCookieTimeOut                   types.Int64    `tfsdk:"custom_cookie_time_out"`
	ReferralCookieTimeOut                 types.Int64    `tfsdk:"referral_cookie_time_out"`
	SessionCookieTimeOut                  types.Int64    `tfsdk:"session_cookie_time_out"`
	SetSecureCookie                       types.Bool     `tfsdk:"set_secure_cookie"`
	CookieDomain                          types.String   `tfsdk:"cookie_domain"`
	CookieNamePrefix                      types.String   `tfsdk:"cookie_name_prefix"`
	CookiePath                            types.String   `tfsdk:"cookie_path"`
	CookieSameSite                        types.String   `tfsdk:"cookie_same_site"`
	DisableBrowserFeatureDetection        types.Bool     `tfsdk:"disable_browser_feature_detection"`
	DisableCampaignParameters             types.Bool     `tfsdk:"disable_campaign_parameters"`
	Domains                               []types.String `tfsdk:"domains"`
	AlwaysUseSendBeacon                   types.Bool     `tfsdk:"always_use_send_beacon"`
	DisableAlwaysUseSendBeacon            types.Bool     `tfsdk:"disable_always_use_send_beacon"`
	UserId                                types.String   `tfsdk:"user_id"`
	CustomDimensions                      []types.String `tfsdk:"custom_dimensions"`
	RegisterAsDefaultTracker              types.Bool     `tfsdk:"register_as_default_tracker"`
	BundleTracker                         types.Bool     `tfsdk:"bundle_tracker"`
	JsEndpoint                            types.String   `tfsdk:"js_endpoint"`
	JsEndpointCustom                      types.String   `tfsdk:"js_endpoint_custom"`
	TrackingEndpoint                      types.String   `tfsdk:"tracking_endpoint"`
	TrackingEndpointCustom                types.String   `tfsdk:"tracking_endpoint_custom"`
	AppendToTrackingUrl                   types.String   `tfsdk:"append_to_tracking_url"`
	ForceRequestMethod                    types.Bool     `tfsdk:"force_request_method"`
	RequestMethod                         types.String   `tfsdk:"request_method"`
	RequestContentType                    types.String   `tfsdk:"request_content_type"`
	CustomRequestProcessing               types.String   `tfsdk:"custom_request_processing"`
	CustomData                            []types.String `tfsdk:"custom_data"`
	SetDownloadExtensions                 types.String   `tfsdk:"set_download_extensions"`
	AddDownloadExtensions                 types.String   `tfsdk:"add_download_extensions"`
	RemoveDownloadExtensions              types.String   `tfsdk:"remove_download_extensions"`
	SetIgnoreClasses                      types.String   `tfsdk:"set_ignore_classes"`
	SetReferrerUrl                        types.String   `tfsdk:"set_referrer_url"`
	SetApiUrl                             types.String   `tfsdk:"set_api_url"`
	SetPageViewId                         types.String   `tfsdk:"set_page_view_id"`
	SetExcludedReferrers                  types.String   `tfsdk:"set_excluded_referrers"`
	SetDownloadClasses                    types.String   `tfsdk:"set_download_classes"`
	SetLinkClasses                        types.String   `tfsdk:"set_link_classes"`
	SetCampaignNameKey                    types.String   `tfsdk:"set_campaign_name_key"`
	SetCampaignKeywordKey                 types.String   `tfsdk:"set_campaign_keyword_key"`
	SetConsentGiven                       types.Bool     `tfsdk:"set_consent_given"`
	RememberConsentGiven                  types.Bool     `tfsdk:"remember_consent_given"`
	RememberConsentGivenForHours          types.String   `tfsdk:"remember_consent_given_for_hours"`
	ForgetConsentGiven                    types.Bool     `tfsdk:"forget_consent_given"`
	DiscardHashTag                        types.Bool     `tfsdk:"discard_hash_tag"`
	SetExcludedQueryParams                types.String   `tfsdk:"set_excluded_query_params"`
	SetConversionAttributionFirstReferrer types.Bool     `tfsdk:"set_conversion_attribution_first_referrer"`
	SetDoNotTrack                         types.Bool     `tfsdk:"set_do_not_track"`
	SetLinkTrackingTimer                  types.String   `tfsdk:"set_link_tracking_timer"`
	KillFrame                             types.Bool     `tfsdk:"kill_frame"`
	SetCountPreRendered                   types.Bool     `tfsdk:"set_count_pre_rendered"`
	SetRequestQueueInterval               types.String   `tfsdk:"set_request_queue_interval"`
}

func variableMatomoconfigurationSchema() schema.Schema {
	return schema.Schema{
		Description: "Defines a configuration for Matomo Analytics.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"container_id": schema.StringAttribute{
				Required:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
			},
			"name": schema.StringAttribute{
				Required: true,
			},
			"default_value": schema.StringAttribute{
				Optional: true,
			},
			"matomo_url": schema.StringAttribute{
				Required:    true,
				Description: "The URL of your Matomo instance. It should not include \"/index.php\" or \"piwik.php\". The URL of your current Matomo URL instance is preconfigured.",
			},
			"id_site": schema.StringAttribute{
				Required:    true,
				Description: "The idSite you want to track data into. The idSite of the current website is preconfigured. You may also find the idSite of any other website under \"Administration → Manage Measurables/Websites\".",
			},
			"enable_link_tracking": schema.BoolAttribute{
				Required:    false,
				Optional:    true,
				Description: "Enables the automatic download and outlink tracking.",
			},
			"enable_file_tracking": schema.BoolAttribute{
				Required:    false,
				Optional:    true,
				Description: "Enable tracking of file:// protocol actions. By default, the file:// protocol is not tracked.",
			},
			"enable_cross_domain_linking": schema.BoolAttribute{
				Required:    false,
				Optional:    true,
				Description: "Enable this to accurately measure the same visitor across multiple domain names.",
			},
			"cross_domain_linking_timeout": schema.Int64Attribute{
				Required:    false,
				Optional:    true,
				Description: "Set the cross domain linking timeout (in seconds). By default, the two visits across domains will be linked together when the link is clicked and the page is loaded within a 180 seconds timeout window.",
			},
			"enable_do_not_track": schema.BoolAttribute{
				Required:    false,
				Optional:    true,
				Description: "Enable this feature to not track users who opt out of tracking using Mozilla's (proposed) Do Not Track setting",
			},
			"disable_performance_tracking": schema.BoolAttribute{
				Required:    false,
				Optional:    true,
				Description: "Disables page performance tracking.",
			},
			"enable_js_error_tracking": schema.BoolAttribute{
				Required:    false,
				Optional:    true,
				Description: "Enables the tracking of uncaught JavaScript errors as an event.",
			},
			"enable_heart_beat_timer": schema.BoolAttribute{
				Required:    false,
				Optional:    true,
				Description: "Install a Heart beat timer that will regularly send requests to Matomo in order to better measure the time spent on the page.",
			},
			"heart_beat_time": schema.Int64Attribute{
				Required:    false,
				Optional:    true,
				Description: "The time interval in seconds in which to send pings. Can not be lower then 5s.",
			},
			"track_all_content_impressions": schema.BoolAttribute{
				Required:    false,
				Optional:    true,
				Description: "Enables the content tracking feature by scanning the entire DOM for all content blocks and tracks all impressions once the page has loaded.",
			},
			"track_visible_content_impressions": schema.BoolAttribute{
				Required:    false,
				Optional:    true,
				Description: "Enables the content tracking feature by scanning the entire DOM for all content blocks but only tracks content impressions once the user scrolls to the content and the content is actually visible.",
			},
			"track_bots": schema.BoolAttribute{
				Required:    false,
				Optional:    true,
				Description: "By default, Matomo doesn't track visits by bots in order to show accurate visitor metrics. Enable this feature to add tracking for bot visits.",
			},
			"disable_cookies": schema.BoolAttribute{
				Required:    false,
				Optional:    true,
				Description: "Disables all first party cookies.",
			},
			"require_consent": schema.BoolAttribute{
				Required:    false,
				Optional:    true,
				Description: "Track only when user gave tracking consent. In a consent screen you need to call \"window._paq=window._paq||[];window._paq.push(['rememberConsentGiven']);\" when the user gives consent.",
			},
			"require_cookie_consent": schema.BoolAttribute{
				Required:    false,
				Optional:    true,
				Description: "Use cookies only if the user gave cookie consent, otherwise track the user without cookies. In a consent screen you need to call \"window._paq=window._paq||[];window._paq.push(['rememberCookieConsentGiven']);\" when the user gives consent for cookies.",
			},
			"custom_cookie_time_out_enable": schema.BoolAttribute{
				Required:    false,
				Optional:    true,
				Description: "Allows you to set custom timeouts for various cookies.",
			},
			"custom_cookie_time_out": schema.Int64Attribute{
				Required:    false,
				Optional:    true,
				Description: "Timeout of pk_id in full days. By default, the Matomo tracking cookie expires in 13 months (365 + 28 days) = 393 days.",
			},
			"referral_cookie_time_out": schema.Int64Attribute{
				Required:    false,
				Optional:    true,
				Description: "Timeout of the referral cookie in full days. By default, the Matomo tracking cookie expires in 6 months = 182 days.",
			},
			"session_cookie_time_out": schema.Int64Attribute{
				Required:    false,
				Optional:    true,
				Description: "Timeout of the session cookie in minutes.",
			},
			"set_secure_cookie": schema.BoolAttribute{
				Required:    false,
				Optional:    true,
				Description: "Enable the Secure cookie flag on all first party cookies. This should be used when your website is only available under HTTPS so that all tracking cookies are always sent over secure connection.",
			},
			"cookie_domain": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Description: "",
			},
			"cookie_name_prefix": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Description: "The name prefix of the cookies.",
			},
			"cookie_path": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Description: "When tracking many subdirectories in separate websites, the cookie path prevents the number of cookies to quickly increase and prevent browser from deleting some of the cookies. This ensures optimal data accuracy and improves performance for your users (fewer cookies are sent with each request).",
			},
			"cookie_same_site": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Description: "Set the SameSite attribute for cookies to a custom value. You might want to use this if your site is running in an iframe since then it will only be able to access the cookies if SameSite is set to \"None\". Choosing \"None\" will only work on HTTPS and will automatically also set the secure cookie. If your site is available under http and https, using \"None\" might lead to duplicate or incomplete visits.",
				Validators:  []validator.String{stringvalidator.OneOf("Lax", "None", "Strict")},
			},
			"disable_browser_feature_detection": schema.BoolAttribute{
				Required:    false,
				Optional:    true,
				Description: "By default, Matomo accesses some information from the visitor’s browser like the browser resolution. Some privacy regulations may allow access of such information from the visitor’s device only after having a consent. If this applies to you, you can disable this feature.",
			},
			"disable_campaign_parameters": schema.BoolAttribute{
				Required:    false,
				Optional:    true,
				Description: "When this option is checked, Matomo will not track campaign parameters and they will be removed from the tracked URLs.",
			},
			"domains": schema.ListAttribute{
				ElementType: types.StringType,
				Required:    false,
				Optional:    true,
				Description: "Used to detect outlinks. Add hostnames or domains to be treated as local. For wildcard subdomains, you can use: \".example.com\" or \"*.example.com\". You can also specify a path along a domain: \"*.example.com/subsite1\".",
			},
			"always_use_send_beacon": schema.BoolAttribute{
				Required:    false,
				Optional:    true,
				Description: "Enables sendBeacon usage instead of a regular ajax request. This means when a user clicks for example on an outlink, the navigation to this page will happen much faster.",
			},
			"disable_always_use_send_beacon": schema.BoolAttribute{
				Required:    false,
				Optional:    true,
				Description: "Choose to stop using sendBeacon and use a regular AJAX request instead. This might make clicking on external links a bit slower for users, but it won't be stopped by ad blockers.",
			},
			"user_id": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Description: "Sets a User ID to this user (such as an email address or a username).",
			},
			"custom_dimensions": schema.ListAttribute{
				ElementType: types.StringType,
				Required:    false,
				Optional:    true,
				Description: "Optionally set one or multiple custom dimensions.",
			},
			"register_as_default_tracker": schema.BoolAttribute{
				Required:    false,
				Optional:    true,
				Description: "When enabled, the tracker will be registered as the default one for the website, and will receive all commands that get pushed into the global _paq variable. Useful if you want to use the tracker config from the container with your own _paq.push() JavaScript code.",
			},
			"bundle_tracker": schema.BoolAttribute{
				Required:    false,
				Optional:    true,
				Description: "By bundling the Matomo JavaScript tracker directly into the container it may improve the performance of your website as it reduces the number of needed requests. It is recommended to bundle the Matomo tracker because in most cases the tracker would otherwise be loaded in a separate request on page view anyway. Note: If you use two different Matomo configurations in one container, the setting of the first configuration used in the first Matomo Tag will be applied to all Matomo tags within one container.",
			},
			"js_endpoint": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Description: "Here you can configure the source path of the Matomo Tracker JavaScript, if you are not using the \"Bundle Tracker\" option.",
				Validators:  []validator.String{stringvalidator.OneOf("custom", "js/", "js/tracker.php", "matomo.js", "piwik.js")},
			},
			"js_endpoint_custom": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Description: "Here you can configure a non standard path to fetch the tracker from. Will be appended to the Matomo URL. Should not start with '/'. Keep in mind that, since this is non standard, you have to handle the requests there yourself!",
			},
			"tracking_endpoint": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Description: "Here you can configure the target path for tracking requests.",
				Validators:  []validator.String{stringvalidator.OneOf("custom", "js/", "js/tracker.php", "matomo.php", "piwik.php")},
			},
			"tracking_endpoint_custom": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Description: "Here you can configure a non standard path for tracking requests. Will be appended to the Matomo URL. Should not start with '/'. Keep in mind that, since this is non standard, you have to handle the requests there yourself!",
			},
			"append_to_tracking_url": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Description: "Append a custom string to the end of the HTTP request to matomo.php? (or your selected respective tracking endpoint).",
			},
			"force_request_method": schema.BoolAttribute{
				Required:    false,
				Optional:    true,
				Description: "Enables forcing the request method to either GET or POST.",
			},
			"request_method": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Description: "",
				Validators:  []validator.String{stringvalidator.OneOf("GET", "POST")},
			},
			"request_content_type": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Description: "Set request Content-Type header value for POST requests.",
			},
			"custom_request_processing": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Description: "Can be set to a variable of type \"Custom Request Processing Function\" to augment or override default request sending behaviour.",
			},
			"custom_data": schema.ListAttribute{
				ElementType: types.StringType,
				Required:    false,
				Optional:    true,
				Description: "Optionally set custom data in your tracking request.",
			},
			"set_download_extensions": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Description: "Set a list of file extensions to be recognized as downloads. Example: doc or doc,xls",
			},
			"add_download_extensions": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Description: "Specify additional file extensions to be recognized as downloads. Example: doc or doc,xls",
			},
			"remove_download_extensions": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Description: "Specify file extensions to be removed from the list of download file extensions. Example: doc or doc,xls",
			},
			"set_ignore_classes": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Description: "Set classes to be ignored if present in link (in addition to matomo_ignore and piwik_ignore). Example classA or classA,classB",
			},
			"set_referrer_url": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Description: "Override the detected Http-Referer. We recommend you call this method early in your tracking code before you call trackPageView if it should be applied to all tracking requests.",
			},
			"set_api_url": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Description: "Specify the Matomo HTTP API URL endpoint. Points to the root directory of piwik, e.g. https://matomo.example.org/ or https://example.org/matomo/. This function is only useful when the 'Overlay' report is not working. By default, you do not need to use this function.",
			},
			"set_page_view_id": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Description: "Override PageView id for every use of logPageView(). Do not use this if you call trackPageView() multiple times during tracking (e.g. when tracking a single page application).",
			},
			"set_excluded_referrers": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Description: "Set array of hostnames or domains that should be ignored as referrers. For wildcard subdomains, you can use .example.com or *.example.com",
			},
			"set_download_classes": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Description: "Set classes to be treated as downloads (in addition to matomo_download)",
			},
			"set_link_classes": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Description: "Set classes to be treated as outlinks (in addition to piwik_link). Example class1 or class1,class2",
			},
			"set_campaign_name_key": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Description: "Set campaign name parameter(s).",
			},
			"set_campaign_keyword_key": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Description: "Set campaign keyword parameter(s).",
			},
			"set_consent_given": schema.BoolAttribute{
				Required:    false,
				Optional:    true,
				Description: "Mark that the current user has consented. The consent is one-time only, so in a subsequent browser session, the user will have to consent again. To remember consent, see the Remember consent given option below.",
			},
			"remember_consent_given": schema.BoolAttribute{
				Required:    false,
				Optional:    true,
				Description: "Mark that the current user has consented, and remembers this consent through a browser cookie. The next time the user visits the site, Matomo will remember that they consented, and track them. If you enable this option, you do not need to enable Set consent given option.",
			},
			"remember_consent_given_for_hours": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Description: "Optionally set after how many hours the consent should expire. By default the consent is valid for 30 years unless cookies are deleted by the user or the browser prior to this.",
			},
			"forget_consent_given": schema.BoolAttribute{
				Required:    false,
				Optional:    true,
				Description: "Remove a user's consent, both if the consent was one-time only and if the consent was remembered. After calling this method, the user will have to consent again in order to be tracked.",
			},
			"discard_hash_tag": schema.BoolAttribute{
				Required:    false,
				Optional:    true,
				Description: "If enabled, it will not record the hash tag (anchor) portion of URLs.",
			},
			"set_excluded_query_params": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Description: "Set query params to exclude from URL. Example uuid or uuid1,uuid2",
			},
			"set_conversion_attribution_first_referrer": schema.BoolAttribute{
				Required:    false,
				Optional:    true,
				Description: "If enabled, conversion will be attributed to first referred. By default, conversion is attributed to the most recent referrer.",
			},
			"set_do_not_track": schema.BoolAttribute{
				Required:    false,
				Optional:    true,
				Description: "If enabled, it will not track users who opt out of tracking using Mozilla's (proposed) Do Not Track setting.",
			},
			"set_link_tracking_timer": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Description: "Set delay for link tracking in milliseconds.",
			},
			"kill_frame": schema.BoolAttribute{
				Required:    false,
				Optional:    true,
				Description: "Enable a frame-buster to prevent the tracked web page from being framed/iframed.",
			},
			"set_count_pre_rendered": schema.BoolAttribute{
				Required:    false,
				Optional:    true,
				Description: "If enabled, it will count sites in pre-rendered state.",
			},
			"set_request_queue_interval": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Description: "Defines after how many ms a queued requests will be executed after the request was queued initially. The higher the value the more tracking requests can be sent together at once. interval has to be at least 1000 (1000ms = 1s) and defaults to 2.5 seconds.",
			},
		},
	}
}

func (m *variableMatomoconfigurationModel) Meta() typedMeta {
	return typedMeta{
		TypeID:       "MatomoConfiguration",
		ResourceName: "matomo_tagmanager_variable_matomoconfiguration",
		Schema:       variableMatomoconfigurationSchema(),
	}
}

// ToParams only includes a key for an Optional parameter when it's
// actually set - sending an empty string for an unset Optional field
// (rather than omitting the key) was rejected by Matomo's own validation
// on live enum/format-constrained parameters (confirmed against a real
// acceptance-test run: an unset htmlPosition sent as "" was rejected by
// CustomHtml's own field validator, which never happens for a key that's
// simply absent from the parameters map).
func (m *variableMatomoconfigurationModel) ToParams() map[string]string {
	p := map[string]string{}
	p["matomoUrl"] = m.MatomoUrl.ValueString()
	p["idSite"] = m.IdSite.ValueString()
	if !m.EnableLinkTracking.IsNull() && !m.EnableLinkTracking.IsUnknown() {
		p["enableLinkTracking"] = paramBoolString(m.EnableLinkTracking.ValueBool())
	}
	if !m.EnableFileTracking.IsNull() && !m.EnableFileTracking.IsUnknown() {
		p["enableFileTracking"] = paramBoolString(m.EnableFileTracking.ValueBool())
	}
	if !m.EnableCrossDomainLinking.IsNull() && !m.EnableCrossDomainLinking.IsUnknown() {
		p["enableCrossDomainLinking"] = paramBoolString(m.EnableCrossDomainLinking.ValueBool())
	}
	if !m.CrossDomainLinkingTimeout.IsNull() && !m.CrossDomainLinkingTimeout.IsUnknown() {
		p["crossDomainLinkingTimeout"] = paramInt64String(m.CrossDomainLinkingTimeout.ValueInt64())
	}
	if !m.EnableDoNotTrack.IsNull() && !m.EnableDoNotTrack.IsUnknown() {
		p["enableDoNotTrack"] = paramBoolString(m.EnableDoNotTrack.ValueBool())
	}
	if !m.DisablePerformanceTracking.IsNull() && !m.DisablePerformanceTracking.IsUnknown() {
		p["disablePerformanceTracking"] = paramBoolString(m.DisablePerformanceTracking.ValueBool())
	}
	if !m.EnableJSErrorTracking.IsNull() && !m.EnableJSErrorTracking.IsUnknown() {
		p["enableJSErrorTracking"] = paramBoolString(m.EnableJSErrorTracking.ValueBool())
	}
	if !m.EnableHeartBeatTimer.IsNull() && !m.EnableHeartBeatTimer.IsUnknown() {
		p["enableHeartBeatTimer"] = paramBoolString(m.EnableHeartBeatTimer.ValueBool())
	}
	if !m.HeartBeatTime.IsNull() && !m.HeartBeatTime.IsUnknown() {
		p["heartBeatTime"] = paramInt64String(m.HeartBeatTime.ValueInt64())
	}
	if !m.TrackAllContentImpressions.IsNull() && !m.TrackAllContentImpressions.IsUnknown() {
		p["trackAllContentImpressions"] = paramBoolString(m.TrackAllContentImpressions.ValueBool())
	}
	if !m.TrackVisibleContentImpressions.IsNull() && !m.TrackVisibleContentImpressions.IsUnknown() {
		p["trackVisibleContentImpressions"] = paramBoolString(m.TrackVisibleContentImpressions.ValueBool())
	}
	if !m.TrackBots.IsNull() && !m.TrackBots.IsUnknown() {
		p["trackBots"] = paramBoolString(m.TrackBots.ValueBool())
	}
	if !m.DisableCookies.IsNull() && !m.DisableCookies.IsUnknown() {
		p["disableCookies"] = paramBoolString(m.DisableCookies.ValueBool())
	}
	if !m.RequireConsent.IsNull() && !m.RequireConsent.IsUnknown() {
		p["requireConsent"] = paramBoolString(m.RequireConsent.ValueBool())
	}
	if !m.RequireCookieConsent.IsNull() && !m.RequireCookieConsent.IsUnknown() {
		p["requireCookieConsent"] = paramBoolString(m.RequireCookieConsent.ValueBool())
	}
	if !m.CustomCookieTimeOutEnable.IsNull() && !m.CustomCookieTimeOutEnable.IsUnknown() {
		p["customCookieTimeOutEnable"] = paramBoolString(m.CustomCookieTimeOutEnable.ValueBool())
	}
	if !m.CustomCookieTimeOut.IsNull() && !m.CustomCookieTimeOut.IsUnknown() {
		p["customCookieTimeOut"] = paramInt64String(m.CustomCookieTimeOut.ValueInt64())
	}
	if !m.ReferralCookieTimeOut.IsNull() && !m.ReferralCookieTimeOut.IsUnknown() {
		p["referralCookieTimeOut"] = paramInt64String(m.ReferralCookieTimeOut.ValueInt64())
	}
	if !m.SessionCookieTimeOut.IsNull() && !m.SessionCookieTimeOut.IsUnknown() {
		p["sessionCookieTimeOut"] = paramInt64String(m.SessionCookieTimeOut.ValueInt64())
	}
	if !m.SetSecureCookie.IsNull() && !m.SetSecureCookie.IsUnknown() {
		p["setSecureCookie"] = paramBoolString(m.SetSecureCookie.ValueBool())
	}
	if !m.CookieDomain.IsNull() && !m.CookieDomain.IsUnknown() {
		p["cookieDomain"] = m.CookieDomain.ValueString()
	}
	if !m.CookieNamePrefix.IsNull() && !m.CookieNamePrefix.IsUnknown() {
		p["cookieNamePrefix"] = m.CookieNamePrefix.ValueString()
	}
	if !m.CookiePath.IsNull() && !m.CookiePath.IsUnknown() {
		p["cookiePath"] = m.CookiePath.ValueString()
	}
	if !m.CookieSameSite.IsNull() && !m.CookieSameSite.IsUnknown() {
		p["cookieSameSite"] = m.CookieSameSite.ValueString()
	}
	if !m.DisableBrowserFeatureDetection.IsNull() && !m.DisableBrowserFeatureDetection.IsUnknown() {
		p["disableBrowserFeatureDetection"] = paramBoolString(m.DisableBrowserFeatureDetection.ValueBool())
	}
	if !m.DisableCampaignParameters.IsNull() && !m.DisableCampaignParameters.IsUnknown() {
		p["disableCampaignParameters"] = paramBoolString(m.DisableCampaignParameters.ValueBool())
	}
	if m.Domains != nil {
		p["domains"] = paramListString(m.Domains)
	}
	if !m.AlwaysUseSendBeacon.IsNull() && !m.AlwaysUseSendBeacon.IsUnknown() {
		p["alwaysUseSendBeacon"] = paramBoolString(m.AlwaysUseSendBeacon.ValueBool())
	}
	if !m.DisableAlwaysUseSendBeacon.IsNull() && !m.DisableAlwaysUseSendBeacon.IsUnknown() {
		p["disableAlwaysUseSendBeacon"] = paramBoolString(m.DisableAlwaysUseSendBeacon.ValueBool())
	}
	if !m.UserId.IsNull() && !m.UserId.IsUnknown() {
		p["userId"] = m.UserId.ValueString()
	}
	if m.CustomDimensions != nil {
		p["customDimensions"] = paramListString(m.CustomDimensions)
	}
	if !m.RegisterAsDefaultTracker.IsNull() && !m.RegisterAsDefaultTracker.IsUnknown() {
		p["registerAsDefaultTracker"] = paramBoolString(m.RegisterAsDefaultTracker.ValueBool())
	}
	if !m.BundleTracker.IsNull() && !m.BundleTracker.IsUnknown() {
		p["bundleTracker"] = paramBoolString(m.BundleTracker.ValueBool())
	}
	if !m.JsEndpoint.IsNull() && !m.JsEndpoint.IsUnknown() {
		p["jsEndpoint"] = m.JsEndpoint.ValueString()
	}
	if !m.JsEndpointCustom.IsNull() && !m.JsEndpointCustom.IsUnknown() {
		p["jsEndpointCustom"] = m.JsEndpointCustom.ValueString()
	}
	if !m.TrackingEndpoint.IsNull() && !m.TrackingEndpoint.IsUnknown() {
		p["trackingEndpoint"] = m.TrackingEndpoint.ValueString()
	}
	if !m.TrackingEndpointCustom.IsNull() && !m.TrackingEndpointCustom.IsUnknown() {
		p["trackingEndpointCustom"] = m.TrackingEndpointCustom.ValueString()
	}
	if !m.AppendToTrackingUrl.IsNull() && !m.AppendToTrackingUrl.IsUnknown() {
		p["appendToTrackingUrl"] = m.AppendToTrackingUrl.ValueString()
	}
	if !m.ForceRequestMethod.IsNull() && !m.ForceRequestMethod.IsUnknown() {
		p["forceRequestMethod"] = paramBoolString(m.ForceRequestMethod.ValueBool())
	}
	if !m.RequestMethod.IsNull() && !m.RequestMethod.IsUnknown() {
		p["requestMethod"] = m.RequestMethod.ValueString()
	}
	if !m.RequestContentType.IsNull() && !m.RequestContentType.IsUnknown() {
		p["requestContentType"] = m.RequestContentType.ValueString()
	}
	if !m.CustomRequestProcessing.IsNull() && !m.CustomRequestProcessing.IsUnknown() {
		p["customRequestProcessing"] = m.CustomRequestProcessing.ValueString()
	}
	if m.CustomData != nil {
		p["customData"] = paramListString(m.CustomData)
	}
	if !m.SetDownloadExtensions.IsNull() && !m.SetDownloadExtensions.IsUnknown() {
		p["setDownloadExtensions"] = m.SetDownloadExtensions.ValueString()
	}
	if !m.AddDownloadExtensions.IsNull() && !m.AddDownloadExtensions.IsUnknown() {
		p["addDownloadExtensions"] = m.AddDownloadExtensions.ValueString()
	}
	if !m.RemoveDownloadExtensions.IsNull() && !m.RemoveDownloadExtensions.IsUnknown() {
		p["removeDownloadExtensions"] = m.RemoveDownloadExtensions.ValueString()
	}
	if !m.SetIgnoreClasses.IsNull() && !m.SetIgnoreClasses.IsUnknown() {
		p["setIgnoreClasses"] = m.SetIgnoreClasses.ValueString()
	}
	if !m.SetReferrerUrl.IsNull() && !m.SetReferrerUrl.IsUnknown() {
		p["setReferrerUrl"] = m.SetReferrerUrl.ValueString()
	}
	if !m.SetApiUrl.IsNull() && !m.SetApiUrl.IsUnknown() {
		p["setApiUrl"] = m.SetApiUrl.ValueString()
	}
	if !m.SetPageViewId.IsNull() && !m.SetPageViewId.IsUnknown() {
		p["setPageViewId"] = m.SetPageViewId.ValueString()
	}
	if !m.SetExcludedReferrers.IsNull() && !m.SetExcludedReferrers.IsUnknown() {
		p["setExcludedReferrers"] = m.SetExcludedReferrers.ValueString()
	}
	if !m.SetDownloadClasses.IsNull() && !m.SetDownloadClasses.IsUnknown() {
		p["setDownloadClasses"] = m.SetDownloadClasses.ValueString()
	}
	if !m.SetLinkClasses.IsNull() && !m.SetLinkClasses.IsUnknown() {
		p["setLinkClasses"] = m.SetLinkClasses.ValueString()
	}
	if !m.SetCampaignNameKey.IsNull() && !m.SetCampaignNameKey.IsUnknown() {
		p["setCampaignNameKey"] = m.SetCampaignNameKey.ValueString()
	}
	if !m.SetCampaignKeywordKey.IsNull() && !m.SetCampaignKeywordKey.IsUnknown() {
		p["setCampaignKeywordKey"] = m.SetCampaignKeywordKey.ValueString()
	}
	if !m.SetConsentGiven.IsNull() && !m.SetConsentGiven.IsUnknown() {
		p["setConsentGiven"] = paramBoolString(m.SetConsentGiven.ValueBool())
	}
	if !m.RememberConsentGiven.IsNull() && !m.RememberConsentGiven.IsUnknown() {
		p["rememberConsentGiven"] = paramBoolString(m.RememberConsentGiven.ValueBool())
	}
	if !m.RememberConsentGivenForHours.IsNull() && !m.RememberConsentGivenForHours.IsUnknown() {
		p["rememberConsentGivenForHours"] = m.RememberConsentGivenForHours.ValueString()
	}
	if !m.ForgetConsentGiven.IsNull() && !m.ForgetConsentGiven.IsUnknown() {
		p["forgetConsentGiven"] = paramBoolString(m.ForgetConsentGiven.ValueBool())
	}
	if !m.DiscardHashTag.IsNull() && !m.DiscardHashTag.IsUnknown() {
		p["discardHashTag"] = paramBoolString(m.DiscardHashTag.ValueBool())
	}
	if !m.SetExcludedQueryParams.IsNull() && !m.SetExcludedQueryParams.IsUnknown() {
		p["setExcludedQueryParams"] = m.SetExcludedQueryParams.ValueString()
	}
	if !m.SetConversionAttributionFirstReferrer.IsNull() && !m.SetConversionAttributionFirstReferrer.IsUnknown() {
		p["setConversionAttributionFirstReferrer"] = paramBoolString(m.SetConversionAttributionFirstReferrer.ValueBool())
	}
	if !m.SetDoNotTrack.IsNull() && !m.SetDoNotTrack.IsUnknown() {
		p["setDoNotTrack"] = paramBoolString(m.SetDoNotTrack.ValueBool())
	}
	if !m.SetLinkTrackingTimer.IsNull() && !m.SetLinkTrackingTimer.IsUnknown() {
		p["setLinkTrackingTimer"] = m.SetLinkTrackingTimer.ValueString()
	}
	if !m.KillFrame.IsNull() && !m.KillFrame.IsUnknown() {
		p["killFrame"] = paramBoolString(m.KillFrame.ValueBool())
	}
	if !m.SetCountPreRendered.IsNull() && !m.SetCountPreRendered.IsUnknown() {
		p["setCountPreRendered"] = paramBoolString(m.SetCountPreRendered.ValueBool())
	}
	if !m.SetRequestQueueInterval.IsNull() && !m.SetRequestQueueInterval.IsUnknown() {
		p["setRequestQueueInterval"] = m.SetRequestQueueInterval.ValueString()
	}
	return p
}

// FromParams mirrors ToParams' omission convention on the way back: a key
// absent from Matomo's response (an unset Optional parameter) must decode
// to a null value, not a zero value ("", false, 0) - decoding it to a
// zero value made every unset Optional parameter round-trip as a
// non-null empty value, which never matched the null the config itself
// produced and left Terraform reporting a perpetual "refresh plan not
// empty" diff on every generated resource with an unset Optional field
// (confirmed against a real acceptance-test run).
func (m *variableMatomoconfigurationModel) FromParams(p map[string]string) {
	m.MatomoUrl = types.StringValue(p["matomoUrl"])
	m.IdSite = types.StringValue(p["idSite"])
	if v, ok := p["enableLinkTracking"]; ok {
		m.EnableLinkTracking = types.BoolValue(paramBoolValue(v))
	} else {
		m.EnableLinkTracking = types.BoolNull()
	}
	if v, ok := p["enableFileTracking"]; ok {
		m.EnableFileTracking = types.BoolValue(paramBoolValue(v))
	} else {
		m.EnableFileTracking = types.BoolNull()
	}
	if v, ok := p["enableCrossDomainLinking"]; ok {
		m.EnableCrossDomainLinking = types.BoolValue(paramBoolValue(v))
	} else {
		m.EnableCrossDomainLinking = types.BoolNull()
	}
	if v, ok := p["crossDomainLinkingTimeout"]; ok {
		m.CrossDomainLinkingTimeout = types.Int64Value(paramInt64Value(v))
	} else {
		m.CrossDomainLinkingTimeout = types.Int64Null()
	}
	if v, ok := p["enableDoNotTrack"]; ok {
		m.EnableDoNotTrack = types.BoolValue(paramBoolValue(v))
	} else {
		m.EnableDoNotTrack = types.BoolNull()
	}
	if v, ok := p["disablePerformanceTracking"]; ok {
		m.DisablePerformanceTracking = types.BoolValue(paramBoolValue(v))
	} else {
		m.DisablePerformanceTracking = types.BoolNull()
	}
	if v, ok := p["enableJSErrorTracking"]; ok {
		m.EnableJSErrorTracking = types.BoolValue(paramBoolValue(v))
	} else {
		m.EnableJSErrorTracking = types.BoolNull()
	}
	if v, ok := p["enableHeartBeatTimer"]; ok {
		m.EnableHeartBeatTimer = types.BoolValue(paramBoolValue(v))
	} else {
		m.EnableHeartBeatTimer = types.BoolNull()
	}
	if v, ok := p["heartBeatTime"]; ok {
		m.HeartBeatTime = types.Int64Value(paramInt64Value(v))
	} else {
		m.HeartBeatTime = types.Int64Null()
	}
	if v, ok := p["trackAllContentImpressions"]; ok {
		m.TrackAllContentImpressions = types.BoolValue(paramBoolValue(v))
	} else {
		m.TrackAllContentImpressions = types.BoolNull()
	}
	if v, ok := p["trackVisibleContentImpressions"]; ok {
		m.TrackVisibleContentImpressions = types.BoolValue(paramBoolValue(v))
	} else {
		m.TrackVisibleContentImpressions = types.BoolNull()
	}
	if v, ok := p["trackBots"]; ok {
		m.TrackBots = types.BoolValue(paramBoolValue(v))
	} else {
		m.TrackBots = types.BoolNull()
	}
	if v, ok := p["disableCookies"]; ok {
		m.DisableCookies = types.BoolValue(paramBoolValue(v))
	} else {
		m.DisableCookies = types.BoolNull()
	}
	if v, ok := p["requireConsent"]; ok {
		m.RequireConsent = types.BoolValue(paramBoolValue(v))
	} else {
		m.RequireConsent = types.BoolNull()
	}
	if v, ok := p["requireCookieConsent"]; ok {
		m.RequireCookieConsent = types.BoolValue(paramBoolValue(v))
	} else {
		m.RequireCookieConsent = types.BoolNull()
	}
	if v, ok := p["customCookieTimeOutEnable"]; ok {
		m.CustomCookieTimeOutEnable = types.BoolValue(paramBoolValue(v))
	} else {
		m.CustomCookieTimeOutEnable = types.BoolNull()
	}
	if v, ok := p["customCookieTimeOut"]; ok {
		m.CustomCookieTimeOut = types.Int64Value(paramInt64Value(v))
	} else {
		m.CustomCookieTimeOut = types.Int64Null()
	}
	if v, ok := p["referralCookieTimeOut"]; ok {
		m.ReferralCookieTimeOut = types.Int64Value(paramInt64Value(v))
	} else {
		m.ReferralCookieTimeOut = types.Int64Null()
	}
	if v, ok := p["sessionCookieTimeOut"]; ok {
		m.SessionCookieTimeOut = types.Int64Value(paramInt64Value(v))
	} else {
		m.SessionCookieTimeOut = types.Int64Null()
	}
	if v, ok := p["setSecureCookie"]; ok {
		m.SetSecureCookie = types.BoolValue(paramBoolValue(v))
	} else {
		m.SetSecureCookie = types.BoolNull()
	}
	if v, ok := p["cookieDomain"]; ok {
		m.CookieDomain = types.StringValue(v)
	} else {
		m.CookieDomain = types.StringNull()
	}
	if v, ok := p["cookieNamePrefix"]; ok {
		m.CookieNamePrefix = types.StringValue(v)
	} else {
		m.CookieNamePrefix = types.StringNull()
	}
	if v, ok := p["cookiePath"]; ok {
		m.CookiePath = types.StringValue(v)
	} else {
		m.CookiePath = types.StringNull()
	}
	if v, ok := p["cookieSameSite"]; ok {
		m.CookieSameSite = types.StringValue(v)
	} else {
		m.CookieSameSite = types.StringNull()
	}
	if v, ok := p["disableBrowserFeatureDetection"]; ok {
		m.DisableBrowserFeatureDetection = types.BoolValue(paramBoolValue(v))
	} else {
		m.DisableBrowserFeatureDetection = types.BoolNull()
	}
	if v, ok := p["disableCampaignParameters"]; ok {
		m.DisableCampaignParameters = types.BoolValue(paramBoolValue(v))
	} else {
		m.DisableCampaignParameters = types.BoolNull()
	}
	if v, ok := p["domains"]; ok {
		m.Domains = paramListValue(v)
	} else {
		m.Domains = nil
	}
	if v, ok := p["alwaysUseSendBeacon"]; ok {
		m.AlwaysUseSendBeacon = types.BoolValue(paramBoolValue(v))
	} else {
		m.AlwaysUseSendBeacon = types.BoolNull()
	}
	if v, ok := p["disableAlwaysUseSendBeacon"]; ok {
		m.DisableAlwaysUseSendBeacon = types.BoolValue(paramBoolValue(v))
	} else {
		m.DisableAlwaysUseSendBeacon = types.BoolNull()
	}
	if v, ok := p["userId"]; ok {
		m.UserId = types.StringValue(v)
	} else {
		m.UserId = types.StringNull()
	}
	if v, ok := p["customDimensions"]; ok {
		m.CustomDimensions = paramListValue(v)
	} else {
		m.CustomDimensions = nil
	}
	if v, ok := p["registerAsDefaultTracker"]; ok {
		m.RegisterAsDefaultTracker = types.BoolValue(paramBoolValue(v))
	} else {
		m.RegisterAsDefaultTracker = types.BoolNull()
	}
	if v, ok := p["bundleTracker"]; ok {
		m.BundleTracker = types.BoolValue(paramBoolValue(v))
	} else {
		m.BundleTracker = types.BoolNull()
	}
	if v, ok := p["jsEndpoint"]; ok {
		m.JsEndpoint = types.StringValue(v)
	} else {
		m.JsEndpoint = types.StringNull()
	}
	if v, ok := p["jsEndpointCustom"]; ok {
		m.JsEndpointCustom = types.StringValue(v)
	} else {
		m.JsEndpointCustom = types.StringNull()
	}
	if v, ok := p["trackingEndpoint"]; ok {
		m.TrackingEndpoint = types.StringValue(v)
	} else {
		m.TrackingEndpoint = types.StringNull()
	}
	if v, ok := p["trackingEndpointCustom"]; ok {
		m.TrackingEndpointCustom = types.StringValue(v)
	} else {
		m.TrackingEndpointCustom = types.StringNull()
	}
	if v, ok := p["appendToTrackingUrl"]; ok {
		m.AppendToTrackingUrl = types.StringValue(v)
	} else {
		m.AppendToTrackingUrl = types.StringNull()
	}
	if v, ok := p["forceRequestMethod"]; ok {
		m.ForceRequestMethod = types.BoolValue(paramBoolValue(v))
	} else {
		m.ForceRequestMethod = types.BoolNull()
	}
	if v, ok := p["requestMethod"]; ok {
		m.RequestMethod = types.StringValue(v)
	} else {
		m.RequestMethod = types.StringNull()
	}
	if v, ok := p["requestContentType"]; ok {
		m.RequestContentType = types.StringValue(v)
	} else {
		m.RequestContentType = types.StringNull()
	}
	if v, ok := p["customRequestProcessing"]; ok {
		m.CustomRequestProcessing = types.StringValue(v)
	} else {
		m.CustomRequestProcessing = types.StringNull()
	}
	if v, ok := p["customData"]; ok {
		m.CustomData = paramListValue(v)
	} else {
		m.CustomData = nil
	}
	if v, ok := p["setDownloadExtensions"]; ok {
		m.SetDownloadExtensions = types.StringValue(v)
	} else {
		m.SetDownloadExtensions = types.StringNull()
	}
	if v, ok := p["addDownloadExtensions"]; ok {
		m.AddDownloadExtensions = types.StringValue(v)
	} else {
		m.AddDownloadExtensions = types.StringNull()
	}
	if v, ok := p["removeDownloadExtensions"]; ok {
		m.RemoveDownloadExtensions = types.StringValue(v)
	} else {
		m.RemoveDownloadExtensions = types.StringNull()
	}
	if v, ok := p["setIgnoreClasses"]; ok {
		m.SetIgnoreClasses = types.StringValue(v)
	} else {
		m.SetIgnoreClasses = types.StringNull()
	}
	if v, ok := p["setReferrerUrl"]; ok {
		m.SetReferrerUrl = types.StringValue(v)
	} else {
		m.SetReferrerUrl = types.StringNull()
	}
	if v, ok := p["setApiUrl"]; ok {
		m.SetApiUrl = types.StringValue(v)
	} else {
		m.SetApiUrl = types.StringNull()
	}
	if v, ok := p["setPageViewId"]; ok {
		m.SetPageViewId = types.StringValue(v)
	} else {
		m.SetPageViewId = types.StringNull()
	}
	if v, ok := p["setExcludedReferrers"]; ok {
		m.SetExcludedReferrers = types.StringValue(v)
	} else {
		m.SetExcludedReferrers = types.StringNull()
	}
	if v, ok := p["setDownloadClasses"]; ok {
		m.SetDownloadClasses = types.StringValue(v)
	} else {
		m.SetDownloadClasses = types.StringNull()
	}
	if v, ok := p["setLinkClasses"]; ok {
		m.SetLinkClasses = types.StringValue(v)
	} else {
		m.SetLinkClasses = types.StringNull()
	}
	if v, ok := p["setCampaignNameKey"]; ok {
		m.SetCampaignNameKey = types.StringValue(v)
	} else {
		m.SetCampaignNameKey = types.StringNull()
	}
	if v, ok := p["setCampaignKeywordKey"]; ok {
		m.SetCampaignKeywordKey = types.StringValue(v)
	} else {
		m.SetCampaignKeywordKey = types.StringNull()
	}
	if v, ok := p["setConsentGiven"]; ok {
		m.SetConsentGiven = types.BoolValue(paramBoolValue(v))
	} else {
		m.SetConsentGiven = types.BoolNull()
	}
	if v, ok := p["rememberConsentGiven"]; ok {
		m.RememberConsentGiven = types.BoolValue(paramBoolValue(v))
	} else {
		m.RememberConsentGiven = types.BoolNull()
	}
	if v, ok := p["rememberConsentGivenForHours"]; ok {
		m.RememberConsentGivenForHours = types.StringValue(v)
	} else {
		m.RememberConsentGivenForHours = types.StringNull()
	}
	if v, ok := p["forgetConsentGiven"]; ok {
		m.ForgetConsentGiven = types.BoolValue(paramBoolValue(v))
	} else {
		m.ForgetConsentGiven = types.BoolNull()
	}
	if v, ok := p["discardHashTag"]; ok {
		m.DiscardHashTag = types.BoolValue(paramBoolValue(v))
	} else {
		m.DiscardHashTag = types.BoolNull()
	}
	if v, ok := p["setExcludedQueryParams"]; ok {
		m.SetExcludedQueryParams = types.StringValue(v)
	} else {
		m.SetExcludedQueryParams = types.StringNull()
	}
	if v, ok := p["setConversionAttributionFirstReferrer"]; ok {
		m.SetConversionAttributionFirstReferrer = types.BoolValue(paramBoolValue(v))
	} else {
		m.SetConversionAttributionFirstReferrer = types.BoolNull()
	}
	if v, ok := p["setDoNotTrack"]; ok {
		m.SetDoNotTrack = types.BoolValue(paramBoolValue(v))
	} else {
		m.SetDoNotTrack = types.BoolNull()
	}
	if v, ok := p["setLinkTrackingTimer"]; ok {
		m.SetLinkTrackingTimer = types.StringValue(v)
	} else {
		m.SetLinkTrackingTimer = types.StringNull()
	}
	if v, ok := p["killFrame"]; ok {
		m.KillFrame = types.BoolValue(paramBoolValue(v))
	} else {
		m.KillFrame = types.BoolNull()
	}
	if v, ok := p["setCountPreRendered"]; ok {
		m.SetCountPreRendered = types.BoolValue(paramBoolValue(v))
	} else {
		m.SetCountPreRendered = types.BoolNull()
	}
	if v, ok := p["setRequestQueueInterval"]; ok {
		m.SetRequestQueueInterval = types.StringValue(v)
	} else {
		m.SetRequestQueueInterval = types.StringNull()
	}
}

func (m *variableMatomoconfigurationModel) Common() *typedVariableCommon {
	return &m.typedVariableCommon
}

func newVariableMatomoconfigurationModel() typedVariableModel {
	return &variableMatomoconfigurationModel{}
}
