// Code generated by tools/gen. DO NOT EDIT.

package provider

import (
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type tagHoneybadgerModel struct {
	typedTagCommon
	HoneybadgerApiKey      types.String `tfsdk:"honeybadger_api_key"`
	HoneybadgerEnvironment types.String `tfsdk:"honeybadger_environment"`
	HoneybadgerRevision    types.String `tfsdk:"honeybadger_revision"`
}

func tagHoneybadgerSchema() schema.Schema {
	return schema.Schema{
		Description: "Exception and Uptime Monitoring for Application Developers",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"container_id": schema.StringAttribute{
				Required:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
			},
			"name": schema.StringAttribute{
				Required: true,
			},
			"status": schema.StringAttribute{
				Optional:      true,
				Computed:      true,
				Validators:    []validator.String{stringvalidator.OneOf("active", "paused")},
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"fire_trigger_ids": schema.ListAttribute{
				Required:    true,
				ElementType: types.StringType,
			},
			"block_trigger_ids": schema.ListAttribute{
				Optional:    true,
				ElementType: types.StringType,
			},
			"honeybadger_api_key": schema.StringAttribute{
				Required:    true,
				Description: "The apiKey of your honeybadger project",
			},
			"honeybadger_environment": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Description: "The environment where the container is included (production, dev, etc.). Leave empty to default to the environment of this container.",
			},
			"honeybadger_revision": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Description: "(optional) the version of your project",
			},
		},
	}
}

func (m *tagHoneybadgerModel) Meta() typedMeta {
	return typedMeta{
		TypeID:       "Honeybadger",
		ResourceName: "matomo_tagmanager_tag_honeybadger",
		Schema:       tagHoneybadgerSchema(),
	}
}

func (m *tagHoneybadgerModel) ToParams() map[string]string {
	return map[string]string{
		"honeybadgerApiKey":      m.HoneybadgerApiKey.ValueString(),
		"honeybadgerEnvironment": m.HoneybadgerEnvironment.ValueString(),
		"honeybadgerRevision":    m.HoneybadgerRevision.ValueString(),
	}
}

func (m *tagHoneybadgerModel) FromParams(p map[string]string) {
	m.HoneybadgerApiKey = types.StringValue(p["honeybadgerApiKey"])
	m.HoneybadgerEnvironment = types.StringValue(p["honeybadgerEnvironment"])
	m.HoneybadgerRevision = types.StringValue(p["honeybadgerRevision"])
}

func (m *tagHoneybadgerModel) Common() *typedTagCommon {
	return &m.typedTagCommon
}

func newTagHoneybadgerModel() typedTagModel {
	return &tagHoneybadgerModel{}
}
