// Code generated by tools/gen. DO NOT EDIT.

package provider

import (
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/nicole-ashley/terraform-provider-matomo/internal/matomo"
)

type triggerFullscreenModel struct {
	typedTriggerCommon
	TriggerAction types.String `tfsdk:"trigger_action"`
	TriggerLimit  types.Int64  `tfsdk:"trigger_limit"`
}

func triggerFullscreenSchema() schema.Schema {
	return schema.Schema{
		Description: "Triggered when the window goes into or leaves full screen.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"container_id": schema.StringAttribute{
				Required:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
			},
			"name": schema.StringAttribute{
				Required: true,
			},
			"description": schema.StringAttribute{
				Optional:      true,
				Computed:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
				Description:   "Optional free-text description, shown in Matomo's Tag Manager UI.",
			},
			"trigger_action": schema.StringAttribute{
				Required:    true,
				Description: "",
				Validators: []validator.String{
					stringvalidator.OneOf("any", "enter", "exit"),
				},
			},
			"trigger_limit": schema.Int64Attribute{
				Required: false,
				Optional: true,
				// Computed + UseStateForUnknown: Matomo can return a
				// non-empty default for this field even when it was never
				// sent (e.g. a boolean parameter defaulting to false
				// server-side), which a bare Optional attribute can't
				// reconcile against an unset (null) config without
				// reporting a spurious diff on every subsequent plan - see
				// NeedsBoolPlanModifierImport's doc comment in
				// tools/gen/emit.go. Skipped for List: the generated Go
				// field type is a bare []types.String, which can't
				// represent "the whole list is unknown" the way
				// Computed's plan semantics require (see
				// block_trigger_ids' comment above for the same
				// limitation and the confirmed failure it caused).
				Computed:      true,
				PlanModifiers: []planmodifier.Int64{int64planmodifier.UseStateForUnknown()},
				Description:   "Enter \"0\" to trigger it each time the event occurs",
			},
		},
	}
}

func (m *triggerFullscreenModel) Meta() typedMeta {
	return typedMeta{
		TypeID:       "Fullscreen",
		ResourceName: "matomo_tagmanager_trigger_fullscreen",
		Schema:       triggerFullscreenSchema(),
	}
}

// ToParams only includes a key for an Optional parameter when it's
// actually set - sending an empty string for an unset Optional field
// (rather than omitting the key) was rejected by Matomo's own validation
// on live enum/format-constrained parameters (confirmed against a real
// acceptance-test run: an unset htmlPosition sent as "" was rejected by
// CustomHtml's own field validator, which never happens for a key that's
// simply absent from the parameters map). A List-typed parameter is sent
// via matomo.ListParam, never joined into a single string - see
// matomo.ParamValue's doc comment for why. A ListOfObjects (real nested
// block) parameter is sent via matomo.ListOfObjectsParam, row by row; a
// single-key MULTI_TUPLE parameter (SingleKeyName set, e.g. domains) stays
// a flat list in the schema/model but is wire-encoded via
// matomo.WrapSingleKeyParam instead of matomo.ListParam - see
// matomo.ParamValue's doc comment for why Matomo needs this shape.
func (m *triggerFullscreenModel) ToParams() matomo.ParamsMap {
	p := matomo.ParamsMap{}
	p["triggerAction"] = matomo.ScalarParam(m.TriggerAction.ValueString())
	if !m.TriggerLimit.IsNull() && !m.TriggerLimit.IsUnknown() {
		p["triggerLimit"] = matomo.ScalarParam(paramInt64String(m.TriggerLimit.ValueInt64()))
	}
	return p
}

// FromParams mirrors ToParams' omission convention on the way back: a key
// absent from Matomo's response (an unset Optional parameter) must decode
// to a null value, not a zero value ("", false, 0) - decoding it to a
// zero value made every unset Optional parameter round-trip as a
// non-null empty value, which never matched the null the config itself
// produced and left Terraform reporting a perpetual "refresh plan not
// empty" diff on every generated resource with an unset Optional field
// (confirmed against a real acceptance-test run).
func (m *triggerFullscreenModel) FromParams(p matomo.ParamsMap) {
	m.TriggerAction = types.StringValue(p["triggerAction"].Scalar)
	if v, ok := p["triggerLimit"]; ok {
		m.TriggerLimit = types.Int64Value(paramInt64Value(v.Scalar))
	} else {
		m.TriggerLimit = types.Int64Null()
	}
}

func (m *triggerFullscreenModel) Common() *typedTriggerCommon {
	return &m.typedTriggerCommon
}

func newTriggerFullscreenModel() typedTriggerModel {
	return &triggerFullscreenModel{}
}
