// Code generated by tools/gen. DO NOT EDIT.

package provider

import (
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type triggerTimerModel struct {
	ID              types.String `tfsdk:"id"`
	ContainerID     types.String `tfsdk:"container_id"`
	Name            types.String `tfsdk:"name"`
	TriggerInterval types.Int64  `tfsdk:"trigger_interval"`
	EventName       types.String `tfsdk:"event_name"`
	TriggerLimit    types.Int64  `tfsdk:"trigger_limit"`
}

func triggerTimerSchema() schema.Schema {
	return schema.Schema{
		Description: "Triggered in a specific interval, for example every 3 seconds.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"container_id": schema.StringAttribute{
				Required:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
			},
			"name": schema.StringAttribute{
				Required: true,
			},
			"trigger_interval": schema.Int64Attribute{
				Required:    true,
				Description: "",
			},
			"event_name": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Description: "You can optionally change the name of this event. This can be useful if you have for example multiple timers on the page and want to perform different logic based on the name of the timer.",
			},
			"trigger_limit": schema.Int64Attribute{
				Required:    false,
				Optional:    true,
				Description: "Enter \"0\" to not limit the trigger.",
			},
		},
	}
}

func (m *triggerTimerModel) Meta() typedMeta {
	return typedMeta{
		TypeID:       "Timer",
		ResourceName: "matomo_tagmanager_trigger_timer",
		Schema:       triggerTimerSchema(),
	}
}

func (m *triggerTimerModel) ToParams() map[string]string {
	return map[string]string{
		"triggerInterval": paramInt64String(m.TriggerInterval.ValueInt64()),
		"eventName":       m.EventName.ValueString(),
		"triggerLimit":    paramInt64String(m.TriggerLimit.ValueInt64()),
	}
}

func (m *triggerTimerModel) FromParams(p map[string]string) {
	m.TriggerInterval = types.Int64Value(paramInt64Value(p["triggerInterval"]))
	m.EventName = types.StringValue(p["eventName"])
	m.TriggerLimit = types.Int64Value(paramInt64Value(p["triggerLimit"]))
}

func newTriggerTimerModel() typedModel {
	return &triggerTimerModel{}
}
