// Code generated by tools/gen. DO NOT EDIT.

package provider

import (
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type tagFacebookpixelModel struct {
	typedTagCommon
	PixelId types.String `tfsdk:"pixel_id"`
}

func tagFacebookpixelSchema() schema.Schema {
	return schema.Schema{
		Description: "The Facebook Pixel is a web analytics and advertising service offered by Facebook.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"container_id": schema.StringAttribute{
				Required:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
			},
			"name": schema.StringAttribute{
				Required: true,
			},
			"status": schema.StringAttribute{
				Optional:      true,
				Computed:      true,
				Validators:    []validator.String{stringvalidator.OneOf("active", "paused")},
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"fire_trigger_ids": schema.ListAttribute{
				Required:    true,
				ElementType: types.StringType,
			},
			"block_trigger_ids": schema.ListAttribute{
				Optional:    true,
				ElementType: types.StringType,
			},
			"pixel_id": schema.StringAttribute{
				Required:    true,
				Description: "",
			},
		},
	}
}

func (m *tagFacebookpixelModel) Meta() typedMeta {
	return typedMeta{
		TypeID:       "FacebookPixel",
		ResourceName: "matomo_tagmanager_tag_facebookpixel",
		Schema:       tagFacebookpixelSchema(),
	}
}

func (m *tagFacebookpixelModel) ToParams() map[string]string {
	return map[string]string{
		"pixelId": m.PixelId.ValueString(),
	}
}

func (m *tagFacebookpixelModel) FromParams(p map[string]string) {
	m.PixelId = types.StringValue(p["pixelId"])
}

func (m *tagFacebookpixelModel) Common() *typedTagCommon {
	return &m.typedTagCommon
}

func newTagFacebookpixelModel() typedTagModel {
	return &tagFacebookpixelModel{}
}
