// Code generated by tools/gen. DO NOT EDIT.

package provider

import (
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type variableClickdataattributeModel struct {
	typedVariableCommon
	DataAttribute types.String `tfsdk:"data_attribute"`
}

func variableClickdataattributeSchema() schema.Schema {
	return schema.Schema{
		Description: "Reads a custom value from the clicked data-attribute.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"container_id": schema.StringAttribute{
				Required:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
			},
			"name": schema.StringAttribute{
				Required: true,
			},
			"default_value": schema.StringAttribute{
				Optional:      true,
				Computed:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"data_attribute": schema.StringAttribute{
				Required:    true,
				Description: "Only add suffix, If data attribute is data-demo just set \"demo\"",
			},
		},
	}
}

func (m *variableClickdataattributeModel) Meta() typedMeta {
	return typedMeta{
		TypeID:       "ClickDataAttribute",
		ResourceName: "matomo_tagmanager_variable_clickdataattribute",
		Schema:       variableClickdataattributeSchema(),
	}
}

// ToParams only includes a key for an Optional parameter when it's
// actually set - sending an empty string for an unset Optional field
// (rather than omitting the key) was rejected by Matomo's own validation
// on live enum/format-constrained parameters (confirmed against a real
// acceptance-test run: an unset htmlPosition sent as "" was rejected by
// CustomHtml's own field validator, which never happens for a key that's
// simply absent from the parameters map).
func (m *variableClickdataattributeModel) ToParams() map[string]string {
	p := map[string]string{}
	p["dataAttribute"] = m.DataAttribute.ValueString()
	return p
}

// FromParams mirrors ToParams' omission convention on the way back: a key
// absent from Matomo's response (an unset Optional parameter) must decode
// to a null value, not a zero value ("", false, 0) - decoding it to a
// zero value made every unset Optional parameter round-trip as a
// non-null empty value, which never matched the null the config itself
// produced and left Terraform reporting a perpetual "refresh plan not
// empty" diff on every generated resource with an unset Optional field
// (confirmed against a real acceptance-test run).
func (m *variableClickdataattributeModel) FromParams(p map[string]string) {
	m.DataAttribute = types.StringValue(p["dataAttribute"])
}

func (m *variableClickdataattributeModel) Common() *typedVariableCommon {
	return &m.typedVariableCommon
}

func newVariableClickdataattributeModel() typedVariableModel {
	return &variableClickdataattributeModel{}
}
