// Code generated by tools/gen. DO NOT EDIT.

package provider

import (
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type triggerJavascripterrorModel struct {
	ID          types.String `tfsdk:"id"`
	ContainerID types.String `tfsdk:"container_id"`
	Name        types.String `tfsdk:"name"`
}

func triggerJavascripterrorSchema() schema.Schema {
	return schema.Schema{
		Description: "Triggered when a JavaScript error happens.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"container_id": schema.StringAttribute{
				Required:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
			},
			"name": schema.StringAttribute{
				Required: true,
			},
		},
	}
}

func (m *triggerJavascripterrorModel) Meta() typedMeta {
	return typedMeta{
		TypeID:       "JavaScriptError",
		ResourceName: "matomo_tagmanager_trigger_javascripterror",
		Schema:       triggerJavascripterrorSchema(),
	}
}

func (m *triggerJavascripterrorModel) ToParams() map[string]string {
	return map[string]string{}
}

func (m *triggerJavascripterrorModel) FromParams(p map[string]string) {
}

func newTriggerJavascripterrorModel() typedModel {
	return &triggerJavascripterrorModel{}
}
