// Code generated by tools/gen. DO NOT EDIT.

package provider

import (
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type tagPingdomrumModel struct {
	typedTagCommon
	PingdomROMId types.String `tfsdk:"pingdom_rom_id"`
}

func tagPingdomrumSchema() schema.Schema {
	return schema.Schema{
		Description: "Pingdom Real User Monitoring (RUM) lets you collect performance data from actual visitors to your site.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"container_id": schema.StringAttribute{
				Required:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
			},
			"name": schema.StringAttribute{
				Required: true,
			},
			"status": schema.StringAttribute{
				Optional:      true,
				Computed:      true,
				Validators:    []validator.String{stringvalidator.OneOf("active", "paused")},
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"fire_trigger_ids": schema.ListAttribute{
				Required:    true,
				ElementType: types.StringType,
			},
			"block_trigger_ids": schema.ListAttribute{
				Optional:    true,
				ElementType: types.StringType,
			},
			"pingdom_rom_id": schema.StringAttribute{
				Required:    true,
				Description: "You can get the Site ID by logging into Pingdom, going to \"Monitoring\" and clicking on \"Real User Monitoring\". Every added site will get its own Site ID.",
			},
		},
	}
}

func (m *tagPingdomrumModel) Meta() typedMeta {
	return typedMeta{
		TypeID:       "PingdomRUM",
		ResourceName: "matomo_tagmanager_tag_pingdomrum",
		Schema:       tagPingdomrumSchema(),
	}
}

func (m *tagPingdomrumModel) ToParams() map[string]string {
	return map[string]string{
		"pingdomROMId": m.PingdomROMId.ValueString(),
	}
}

func (m *tagPingdomrumModel) FromParams(p map[string]string) {
	m.PingdomROMId = types.StringValue(p["pingdomROMId"])
}

func (m *tagPingdomrumModel) Common() *typedTagCommon {
	return &m.typedTagCommon
}

func newTagPingdomrumModel() typedTagModel {
	return &tagPingdomrumModel{}
}
