// Code generated by tools/gen. DO NOT EDIT.

package provider

import (
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/nicole-ashley/terraform-provider-matomo/internal/matomo"
)

type variableReferrerurlModel struct {
	typedVariableCommon
	UrlPart types.String `tfsdk:"url_part"`
}

func variableReferrerurlSchema() schema.Schema {
	return schema.Schema{
		Description: "Gets the value of the Referrer URL.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"container_id": schema.StringAttribute{
				Required:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
			},
			"name": schema.StringAttribute{
				Required: true,
			},
			"description": schema.StringAttribute{
				Optional:      true,
				Computed:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
				Description:   "Optional free-text description, shown in Matomo's Tag Manager UI.",
			},
			"default_value": schema.StringAttribute{
				Optional:      true,
				Computed:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"url_part": schema.StringAttribute{
				Required:    true,
				Description: "Select the part of the URL you want to retrieve.",
				Validators: []validator.String{
					stringvalidator.OneOf("host", "hostname", "href", "origin", "pathname", "port", "protocol", "search"),
				},
			},
		},
	}
}

func (m *variableReferrerurlModel) Meta() typedMeta {
	return typedMeta{
		TypeID:       "ReferrerUrl",
		ResourceName: "matomo_tagmanager_variable_referrerurl",
		Schema:       variableReferrerurlSchema(),
	}
}

// ToParams only includes a key for an Optional parameter when it's
// actually set - sending an empty string for an unset Optional field
// (rather than omitting the key) was rejected by Matomo's own validation
// on live enum/format-constrained parameters (confirmed against a real
// acceptance-test run: an unset htmlPosition sent as "" was rejected by
// CustomHtml's own field validator, which never happens for a key that's
// simply absent from the parameters map). A List-typed parameter is sent
// via matomo.ListParam, never joined into a single string - see
// matomo.ParamValue's doc comment for why. A ListOfObjects (real nested
// block) parameter is sent via matomo.ListOfObjectsParam, row by row; a
// single-key MULTI_TUPLE parameter (SingleKeyName set, e.g. domains) stays
// a flat list in the schema/model but is wire-encoded via
// matomo.WrapSingleKeyParam instead of matomo.ListParam - see
// matomo.ParamValue's doc comment for why Matomo needs this shape.
func (m *variableReferrerurlModel) ToParams() matomo.ParamsMap {
	p := matomo.ParamsMap{}
	p["urlPart"] = matomo.ScalarParam(m.UrlPart.ValueString())
	return p
}

// FromParams mirrors ToParams' omission convention on the way back: a key
// absent from Matomo's response (an unset Optional parameter) must decode
// to a null value, not a zero value ("", false, 0) - decoding it to a
// zero value made every unset Optional parameter round-trip as a
// non-null empty value, which never matched the null the config itself
// produced and left Terraform reporting a perpetual "refresh plan not
// empty" diff on every generated resource with an unset Optional field
// (confirmed against a real acceptance-test run).
func (m *variableReferrerurlModel) FromParams(p matomo.ParamsMap) {
	m.UrlPart = types.StringValue(p["urlPart"].Scalar)
}

func (m *variableReferrerurlModel) Common() *typedVariableCommon {
	return &m.typedVariableCommon
}

func newVariableReferrerurlModel() typedVariableModel {
	return &variableReferrerurlModel{}
}
