// Code generated by tools/gen. DO NOT EDIT.

package provider

import (
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type triggerAlldownloadsclickModel struct {
	typedTriggerCommon
	DownloadExtensions types.String `tfsdk:"download_extensions"`
}

func triggerAlldownloadsclickSchema() schema.Schema {
	return schema.Schema{
		Description: "Triggered when a link is clicked which links to a downloadable file. It will be triggered on left, middle and right click.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"container_id": schema.StringAttribute{
				Required:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
			},
			"name": schema.StringAttribute{
				Required: true,
			},
			"download_extensions": schema.StringAttribute{
				Required:    true,
				Description: "Comma separated list of file extensions which will be considered as a download.",
			},
		},
	}
}

func (m *triggerAlldownloadsclickModel) Meta() typedMeta {
	return typedMeta{
		TypeID:       "AllDownloadsClick",
		ResourceName: "matomo_tagmanager_trigger_alldownloadsclick",
		Schema:       triggerAlldownloadsclickSchema(),
	}
}

// ToParams only includes a key for an Optional parameter when it's
// actually set - sending an empty string for an unset Optional field
// (rather than omitting the key) was rejected by Matomo's own validation
// on live enum/format-constrained parameters (confirmed against a real
// acceptance-test run: an unset htmlPosition sent as "" was rejected by
// CustomHtml's own field validator, which never happens for a key that's
// simply absent from the parameters map).
func (m *triggerAlldownloadsclickModel) ToParams() map[string]string {
	p := map[string]string{}
	p["downloadExtensions"] = m.DownloadExtensions.ValueString()
	return p
}

func (m *triggerAlldownloadsclickModel) FromParams(p map[string]string) {
	m.DownloadExtensions = types.StringValue(p["downloadExtensions"])
}

func (m *triggerAlldownloadsclickModel) Common() *typedTriggerCommon {
	return &m.typedTriggerCommon
}

func newTriggerAlldownloadsclickModel() typedTriggerModel {
	return &triggerAlldownloadsclickModel{}
}
