// Code generated by tools/gen. DO NOT EDIT.

package provider

import (
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type variableJavascriptModel struct {
	ID           types.String `tfsdk:"id"`
	ContainerID  types.String `tfsdk:"container_id"`
	Name         types.String `tfsdk:"name"`
	DefaultValue types.String `tfsdk:"default_value"`
	VariableName types.String `tfsdk:"variable_name"`
}

func variableJavascriptSchema() schema.Schema {
	return schema.Schema{
		Description: "Reads the value of a global JavaScript variable.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"container_id": schema.StringAttribute{
				Required:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
			},
			"name": schema.StringAttribute{
				Required: true,
			},
			"default_value": schema.StringAttribute{
				Optional: true,
			},
			"variable_name": schema.StringAttribute{
				Required:    true,
				Description: "The name of any variable that is available within the global scope. In case you want to access the value of a nested object, you can access the value of an object by separating each property by a dot, for example \"document.referrer\".",
			},
		},
	}
}

func (m *variableJavascriptModel) Meta() typedMeta {
	return typedMeta{
		TypeID:       "JavaScript",
		ResourceName: "matomo_tagmanager_variable_javascript",
		Schema:       variableJavascriptSchema(),
	}
}

func (m *variableJavascriptModel) ToParams() map[string]string {
	return map[string]string{
		"variableName": m.VariableName.ValueString(),
	}
}

func (m *variableJavascriptModel) FromParams(p map[string]string) {
	m.VariableName = types.StringValue(p["variableName"])
}

func newVariableJavascriptModel() typedModel {
	return &variableJavascriptModel{}
}
