// Code generated by tools/gen. DO NOT EDIT.

package provider

import (
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type tagCookiebotModel struct {
	typedTagCommon
	CookiebotId types.String `tfsdk:"cookiebot_id"`
}

func tagCookiebotSchema() schema.Schema {
	return schema.Schema{
		Description: "Cookiebot CMP makes the use of cookies and online tracking of your website GDPR compliant.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"container_id": schema.StringAttribute{
				Required:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
			},
			"name": schema.StringAttribute{
				Required: true,
			},
			"status": schema.StringAttribute{
				Optional:      true,
				Computed:      true,
				Validators:    []validator.String{stringvalidator.OneOf("active", "paused")},
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"fire_trigger_ids": schema.ListAttribute{
				Required:    true,
				ElementType: types.StringType,
			},
			"block_trigger_ids": schema.ListAttribute{
				Optional:    true,
				ElementType: types.StringType,
			},
			"cookiebot_id": schema.StringAttribute{
				Required:    true,
				Description: "Insert the domain group id provided in the \"Your Script\" section on Cookiebot website.",
			},
		},
	}
}

func (m *tagCookiebotModel) Meta() typedMeta {
	return typedMeta{
		TypeID:       "Cookiebot",
		ResourceName: "matomo_tagmanager_tag_cookiebot",
		Schema:       tagCookiebotSchema(),
	}
}

// ToParams only includes a key for an Optional parameter when it's
// actually set - sending an empty string for an unset Optional field
// (rather than omitting the key) was rejected by Matomo's own validation
// on live enum/format-constrained parameters (confirmed against a real
// acceptance-test run: an unset htmlPosition sent as "" was rejected by
// CustomHtml's own field validator, which never happens for a key that's
// simply absent from the parameters map).
func (m *tagCookiebotModel) ToParams() map[string]string {
	p := map[string]string{}
	p["cookiebotId"] = m.CookiebotId.ValueString()
	return p
}

func (m *tagCookiebotModel) FromParams(p map[string]string) {
	m.CookiebotId = types.StringValue(p["cookiebotId"])
}

func (m *tagCookiebotModel) Common() *typedTagCommon {
	return &m.typedTagCommon
}

func newTagCookiebotModel() typedTagModel {
	return &tagCookiebotModel{}
}
