// Code generated by tools/gen. DO NOT EDIT.

package provider

import (
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/nicole-ashley/terraform-provider-matomo/internal/matomo"
)

type variableDatalayerModel struct {
	typedVariableCommon
	DataLayerName types.String `tfsdk:"data_layer_name"`
}

func variableDatalayerSchema() schema.Schema {
	return schema.Schema{
		Description: "Reads a custom value from the Data-Layer.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"container_id": schema.StringAttribute{
				Required:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
			},
			"name": schema.StringAttribute{
				Required: true,
			},
			"default_value": schema.StringAttribute{
				Optional:      true,
				Computed:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"data_layer_name": schema.StringAttribute{
				Required:    true,
				Description: "The name of any variable that is stored within the dataLayer. In case you want to access the value of a nested object, you can access the value of an object by separating each property by a dot, for example \"object1.myPropertyOfObject1\".",
			},
		},
	}
}

func (m *variableDatalayerModel) Meta() typedMeta {
	return typedMeta{
		TypeID:       "DataLayer",
		ResourceName: "matomo_tagmanager_variable_datalayer",
		Schema:       variableDatalayerSchema(),
	}
}

// ToParams only includes a key for an Optional parameter when it's
// actually set - sending an empty string for an unset Optional field
// (rather than omitting the key) was rejected by Matomo's own validation
// on live enum/format-constrained parameters (confirmed against a real
// acceptance-test run: an unset htmlPosition sent as "" was rejected by
// CustomHtml's own field validator, which never happens for a key that's
// simply absent from the parameters map). A List-typed parameter is sent
// via matomo.ListParam, never joined into a single string - see
// matomo.ParamValue's doc comment for why. A ListOfObjects (real nested
// block) parameter is sent via matomo.ListOfObjectsParam, row by row; a
// single-key MULTI_TUPLE parameter (SingleKeyName set, e.g. domains) stays
// a flat list in the schema/model but is wire-encoded via
// matomo.WrapSingleKeyParam instead of matomo.ListParam - see
// matomo.ParamValue's doc comment for why Matomo needs this shape.
func (m *variableDatalayerModel) ToParams() matomo.ParamsMap {
	p := matomo.ParamsMap{}
	p["dataLayerName"] = matomo.ScalarParam(m.DataLayerName.ValueString())
	return p
}

// FromParams mirrors ToParams' omission convention on the way back: a key
// absent from Matomo's response (an unset Optional parameter) must decode
// to a null value, not a zero value ("", false, 0) - decoding it to a
// zero value made every unset Optional parameter round-trip as a
// non-null empty value, which never matched the null the config itself
// produced and left Terraform reporting a perpetual "refresh plan not
// empty" diff on every generated resource with an unset Optional field
// (confirmed against a real acceptance-test run).
func (m *variableDatalayerModel) FromParams(p matomo.ParamsMap) {
	m.DataLayerName = types.StringValue(p["dataLayerName"].Scalar)
}

func (m *variableDatalayerModel) Common() *typedVariableCommon {
	return &m.typedVariableCommon
}

func newVariableDatalayerModel() typedVariableModel {
	return &variableDatalayerModel{}
}
