// Code generated by tools/gen. DO NOT EDIT.

package provider

import (
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type tagBugsnagModel struct {
	typedTagCommon
	ApiKey        types.String `tfsdk:"api_key"`
	CollectUserIp types.Bool   `tfsdk:"collect_user_ip"`
}

func tagBugsnagSchema() schema.Schema {
	return schema.Schema{
		Description: "Add error monitoring to your applications with Bugsnag.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"container_id": schema.StringAttribute{
				Required:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
			},
			"name": schema.StringAttribute{
				Required: true,
			},
			"status": schema.StringAttribute{
				Optional:      true,
				Computed:      true,
				Validators:    []validator.String{stringvalidator.OneOf("active", "paused")},
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"fire_trigger_ids": schema.ListAttribute{
				Required:    true,
				ElementType: types.StringType,
			},
			"block_trigger_ids": schema.ListAttribute{
				Optional:    true,
				ElementType: types.StringType,
			},
			"api_key": schema.StringAttribute{
				Required:    true,
				Description: "You can find your API key in your project settings from your Bugsnag dashboard.",
			},
			"collect_user_ip": schema.BoolAttribute{
				Required:    false,
				Optional:    true,
				Description: "This should be disable if you don't want to track personal information about your users.",
			},
		},
	}
}

func (m *tagBugsnagModel) Meta() typedMeta {
	return typedMeta{
		TypeID:       "Bugsnag",
		ResourceName: "matomo_tagmanager_tag_bugsnag",
		Schema:       tagBugsnagSchema(),
	}
}

func (m *tagBugsnagModel) ToParams() map[string]string {
	return map[string]string{
		"apiKey":        m.ApiKey.ValueString(),
		"collectUserIp": paramBoolString(m.CollectUserIp.ValueBool()),
	}
}

func (m *tagBugsnagModel) FromParams(p map[string]string) {
	m.ApiKey = types.StringValue(p["apiKey"])
	m.CollectUserIp = types.BoolValue(paramBoolValue(p["collectUserIp"]))
}

func (m *tagBugsnagModel) Common() *typedTagCommon {
	return &m.typedTagCommon
}

func newTagBugsnagModel() typedTagModel {
	return &tagBugsnagModel{}
}
