// Code generated by tools/gen. DO NOT EDIT.

package provider

import (
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/nicole-ashley/terraform-provider-matomo/internal/matomo"
)

type tagLinkedininsightModel struct {
	typedTagCommon
	PartnerId    types.String `tfsdk:"partner_id"`
	ConversionId types.String `tfsdk:"conversion_id"`
}

func tagLinkedininsightSchema() schema.Schema {
	return schema.Schema{
		Description: "Adds the LinkedIn Insight Tag so you can apply conversion tracking to your LinkedIn ad campaigns.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"container_id": schema.StringAttribute{
				Required:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
			},
			"name": schema.StringAttribute{
				Required: true,
			},
			"status": schema.StringAttribute{
				Optional:      true,
				Computed:      true,
				Validators:    []validator.String{stringvalidator.OneOf("active", "paused")},
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"fire_trigger_ids": schema.ListAttribute{
				Required:    true,
				ElementType: types.StringType,
			},
			"block_trigger_ids": schema.ListAttribute{
				// Not Computed, unlike the other common/generated Optional
				// attributes: the generated Go field type for a List
				// attribute is a bare []types.String (see the Params
				// range below), which - unlike types.List - has no way to
				// represent "the whole list is unknown," so marking it
				// Computed makes terraform-plugin-framework fail outright
				// trying to decode plan's Unknown value into it
				// (confirmed against a real acceptance-test run: "Value
				// Conversion Error ... Received unknown value, however
				// the target type cannot handle unknown values"). A
				// List-typed field can still show a spurious
				// "refresh plan not empty" diff if Matomo defaults it to
				// a non-empty value server-side - fixing that for real
				// would mean switching the generated field type to
				// types.List, which is a larger change than this pass
				// covers.
				Optional:    true,
				ElementType: types.StringType,
			},
			"partner_id": schema.StringAttribute{
				Required:    true,
				Description: "You can find the partner ID by logging into your LinkedIn Campaign Manager, and clicking on \"Account Assets\" followed by \"Insight Tag\". If \"Insight Tag\" is not available, please set up the Insight Tag by clicking on \"Conversion Tracking\". There you can enter a domain and continue the set up. You will find the partner ID in the line `_linkedin_partner_id = \"123456\"`. In this example the ID would be \"123456\".",
			},
			"conversion_id": schema.StringAttribute{
				Required: false,
				Optional: true,
				// Computed + UseStateForUnknown: Matomo can return a
				// non-empty default for this field even when it was never
				// sent (e.g. a boolean parameter defaulting to false
				// server-side), which a bare Optional attribute can't
				// reconcile against an unset (null) config without
				// reporting a spurious diff on every subsequent plan - see
				// NeedsBoolPlanModifierImport's doc comment in
				// tools/gen/emit.go. Skipped for List: the generated Go
				// field type is a bare []types.String, which can't
				// represent "the whole list is unknown" the way
				// Computed's plan semantics require (see
				// block_trigger_ids' comment above for the same
				// limitation and the confirmed failure it caused).
				Computed:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
				Description:   "An optional conversion ID if you would like a specific conversion recorded when this tag executes.",
			},
		},
	}
}

func (m *tagLinkedininsightModel) Meta() typedMeta {
	return typedMeta{
		TypeID:       "LinkedinInsight",
		ResourceName: "matomo_tagmanager_tag_linkedininsight",
		Schema:       tagLinkedininsightSchema(),
	}
}

// ToParams only includes a key for an Optional parameter when it's
// actually set - sending an empty string for an unset Optional field
// (rather than omitting the key) was rejected by Matomo's own validation
// on live enum/format-constrained parameters (confirmed against a real
// acceptance-test run: an unset htmlPosition sent as "" was rejected by
// CustomHtml's own field validator, which never happens for a key that's
// simply absent from the parameters map). A List-typed parameter is sent
// via matomo.ListParam, never joined into a single string - see
// matomo.ParamValue's doc comment for why. A ListOfObjects (real nested
// block) parameter is sent via matomo.ListOfObjectsParam, row by row; a
// single-key MULTI_TUPLE parameter (SingleKeyName set, e.g. domains) stays
// a flat list in the schema/model but is wire-encoded via
// matomo.WrapSingleKeyParam instead of matomo.ListParam - see
// matomo.ParamValue's doc comment for why Matomo needs this shape.
func (m *tagLinkedininsightModel) ToParams() matomo.ParamsMap {
	p := matomo.ParamsMap{}
	p["partnerId"] = matomo.ScalarParam(m.PartnerId.ValueString())
	if !m.ConversionId.IsNull() && !m.ConversionId.IsUnknown() {
		p["conversionId"] = matomo.ScalarParam(m.ConversionId.ValueString())
	}
	return p
}

// FromParams mirrors ToParams' omission convention on the way back: a key
// absent from Matomo's response (an unset Optional parameter) must decode
// to a null value, not a zero value ("", false, 0) - decoding it to a
// zero value made every unset Optional parameter round-trip as a
// non-null empty value, which never matched the null the config itself
// produced and left Terraform reporting a perpetual "refresh plan not
// empty" diff on every generated resource with an unset Optional field
// (confirmed against a real acceptance-test run).
func (m *tagLinkedininsightModel) FromParams(p matomo.ParamsMap) {
	m.PartnerId = types.StringValue(p["partnerId"].Scalar)
	if v, ok := p["conversionId"]; ok {
		m.ConversionId = types.StringValue(v.Scalar)
	} else {
		m.ConversionId = types.StringNull()
	}
}

func (m *tagLinkedininsightModel) Common() *typedTagCommon {
	return &m.typedTagCommon
}

func newTagLinkedininsightModel() typedTagModel {
	return &tagLinkedininsightModel{}
}
