package provider

import (
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

// This file is generated by tools/gen only if it does not already exist.
// Once present, tools/gen never overwrites it - edit freely to add real
// assertions (this scaffold only proves create+read-back with placeholder
// values).
func TestAccTagTawkto_createAndReadBack(t *testing.T) {
	testAccPreCheck(t)
	resourceName := "matomo_tagmanager_tag_tawkto.test"

	resource.Test(t, resource.TestCase{
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: testAccTagTawktoConfig(),
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttrSet(resourceName, "id"),
				),
			},
			{
				ResourceName:      resourceName,
				ImportState:       true,
				ImportStateVerify: true,
			},
		},
	})
}

func testAccTagTawktoConfig() string {
	return `
provider "matomo" {}

resource "matomo_site" "test" {
  name = "Generated TawkTo Acceptance Site"
  urls = ["https://acc-generated-tawkto.example.com"]
}

resource "matomo_tagmanager_container" "test" {
  site_id = matomo_site.test.id
  context = "web"
  name    = "Generated TawkTo Acceptance Container"
}

resource "matomo_tagmanager_trigger" "test" {
  container_id = matomo_tagmanager_container.test.id
  type         = "PageView"
  name         = "Generated TawkTo Acceptance Trigger"
}

resource "matomo_tagmanager_tag_tawkto" "test" {
  container_id = matomo_tagmanager_container.test.id
  name         = "generated-test-tawkto"
  fire_trigger_ids = [matomo_tagmanager_trigger.test.id]
  // TawkToTag.php requires a minimum 16-character tawkToId (confirmed
  // live: "test-value" (10 chars) was rejected).
  tawk_to_id = "test-value-12345"
  tawk_to_widget_id = "test-value-12345"
}
`
}
