// Code generated by tools/gen. DO NOT EDIT.

package provider

import (
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type variableClickhtmlattributeModel struct {
	typedVariableCommon
	HtmlAttribute types.String `tfsdk:"html_attribute"`
}

func variableClickhtmlattributeSchema() schema.Schema {
	return schema.Schema{
		Description: "Reads a custom value from the clicked HTML attribute.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"container_id": schema.StringAttribute{
				Required:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
			},
			"name": schema.StringAttribute{
				Required: true,
			},
			"default_value": schema.StringAttribute{
				Optional:      true,
				Computed:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"html_attribute": schema.StringAttribute{
				Required:    true,
				Description: "The name of the attribute, such as title, value, alt, or any other HTML attribute.",
			},
		},
	}
}

func (m *variableClickhtmlattributeModel) Meta() typedMeta {
	return typedMeta{
		TypeID:       "ClickHtmlAttribute",
		ResourceName: "matomo_tagmanager_variable_clickhtmlattribute",
		Schema:       variableClickhtmlattributeSchema(),
	}
}

// ToParams only includes a key for an Optional parameter when it's
// actually set - sending an empty string for an unset Optional field
// (rather than omitting the key) was rejected by Matomo's own validation
// on live enum/format-constrained parameters (confirmed against a real
// acceptance-test run: an unset htmlPosition sent as "" was rejected by
// CustomHtml's own field validator, which never happens for a key that's
// simply absent from the parameters map).
func (m *variableClickhtmlattributeModel) ToParams() map[string]string {
	p := map[string]string{}
	p["htmlAttribute"] = m.HtmlAttribute.ValueString()
	return p
}

// FromParams mirrors ToParams' omission convention on the way back: a key
// absent from Matomo's response (an unset Optional parameter) must decode
// to a null value, not a zero value ("", false, 0) - decoding it to a
// zero value made every unset Optional parameter round-trip as a
// non-null empty value, which never matched the null the config itself
// produced and left Terraform reporting a perpetual "refresh plan not
// empty" diff on every generated resource with an unset Optional field
// (confirmed against a real acceptance-test run).
func (m *variableClickhtmlattributeModel) FromParams(p map[string]string) {
	m.HtmlAttribute = types.StringValue(p["htmlAttribute"])
}

func (m *variableClickhtmlattributeModel) Common() *typedVariableCommon {
	return &m.typedVariableCommon
}

func newVariableClickhtmlattributeModel() typedVariableModel {
	return &variableClickhtmlattributeModel{}
}
