// Code generated by tools/gen. DO NOT EDIT.

package provider

import (
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type triggerAlldownloadsclickModel struct {
	ID                 types.String `tfsdk:"id"`
	ContainerID        types.String `tfsdk:"container_id"`
	Name               types.String `tfsdk:"name"`
	DownloadExtensions types.String `tfsdk:"download_extensions"`
}

func triggerAlldownloadsclickSchema() schema.Schema {
	return schema.Schema{
		Description: "Triggered when a link is clicked which links to a downloadable file. It will be triggered on left, middle and right click.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"container_id": schema.StringAttribute{
				Required:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
			},
			"name": schema.StringAttribute{
				Required: true,
			},
			"download_extensions": schema.StringAttribute{
				Required:    true,
				Description: "Comma separated list of file extensions which will be considered as a download.",
			},
		},
	}
}

func (m *triggerAlldownloadsclickModel) Meta() typedMeta {
	return typedMeta{
		TypeID:       "AllDownloadsClick",
		ResourceName: "matomo_tagmanager_trigger_alldownloadsclick",
		Schema:       triggerAlldownloadsclickSchema(),
	}
}

func (m *triggerAlldownloadsclickModel) ToParams() map[string]string {
	return map[string]string{
		"downloadExtensions": m.DownloadExtensions.ValueString(),
	}
}

func (m *triggerAlldownloadsclickModel) FromParams(p map[string]string) {
	m.DownloadExtensions = types.StringValue(p["downloadExtensions"])
}

func newTriggerAlldownloadsclickModel() typedModel {
	return &triggerAlldownloadsclickModel{}
}
