package provider

import (
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

// This file is generated by tools/gen only if it does not already exist.
// Once present, tools/gen never overwrites it - edit freely to add real
// assertions (this scaffold only proves create+read-back with placeholder
// values).
func TestAccTagDrift_createAndReadBack(t *testing.T) {
	testAccPreCheck(t)
	resourceName := "matomo_tagmanager_tag_drift.test"

	resource.Test(t, resource.TestCase{
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: testAccTagDriftConfig(),
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttrSet(resourceName, "id"),
				),
			},
			{
				ResourceName:      resourceName,
				ImportState:       true,
				ImportStateVerify: true,
			},
		},
	})
}

func testAccTagDriftConfig() string {
	return `
provider "matomo" {}

resource "matomo_site" "test" {
  name = "Generated Drift Acceptance Site"
  urls = ["https://acc-generated-drift.example.com"]
}

resource "matomo_tagmanager_container" "test" {
  site_id = matomo_site.test.id
  context = "web"
  name    = "Generated Drift Acceptance Container"
}

resource "matomo_tagmanager_trigger" "test" {
  container_id = matomo_tagmanager_container.test.id
  type         = "PageView"
  name         = "Generated Drift Acceptance Trigger"
}

resource "matomo_tagmanager_tag_drift" "test" {
  container_id = matomo_tagmanager_container.test.id
  name         = "generated-test-drift"
  fire_trigger_ids = [matomo_tagmanager_trigger.test.id]
  // DriftTag.php requires a minimum 12-character driftId (confirmed live:
  // "test-value" (10 chars) was rejected).
  drift_id = "test-value-1"
}
`
}
