// Code generated by tools/gen. DO NOT EDIT.

package provider

import (
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type tagTawktoModel struct {
	typedTagCommon
	TawkToId       types.String `tfsdk:"tawk_to_id"`
	TawkToWidgetId types.String `tfsdk:"tawk_to_widget_id"`
}

func tagTawktoSchema() schema.Schema {
	return schema.Schema{
		Description: "Tawk.to lets you monitor and chat with visitors on your website.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"container_id": schema.StringAttribute{
				Required:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
			},
			"name": schema.StringAttribute{
				Required: true,
			},
			"status": schema.StringAttribute{
				Optional:      true,
				Computed:      true,
				Validators:    []validator.String{stringvalidator.OneOf("active", "paused")},
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"fire_trigger_ids": schema.ListAttribute{
				Required:    true,
				ElementType: types.StringType,
			},
			"block_trigger_ids": schema.ListAttribute{
				Optional:    true,
				ElementType: types.StringType,
			},
			"tawk_to_id": schema.StringAttribute{
				Required:    true,
				Description: "You can get the Site ID by logging into Tawk.to, going to \"Administration\" and clicking on \"Property Settings\". The Site ID has typically about 25 characters, for example \"123451c27295ad739e46b6b1\".",
			},
			"tawk_to_widget_id": schema.StringAttribute{
				Required:    true,
				Description: "You can get the Widget ID by logging into Tawk.to, going to \"Administration\" and clicking on \"Chat Widget\" and selecting an appropriate widget. The widget ID can be retrieved from \"Direct Chat Link\" as https://tawk.to/chat/{SITE_ID}/{WIDGET_ID}.",
			},
		},
	}
}

func (m *tagTawktoModel) Meta() typedMeta {
	return typedMeta{
		TypeID:       "TawkTo",
		ResourceName: "matomo_tagmanager_tag_tawkto",
		Schema:       tagTawktoSchema(),
	}
}

func (m *tagTawktoModel) ToParams() map[string]string {
	return map[string]string{
		"tawkToId":       m.TawkToId.ValueString(),
		"tawkToWidgetId": m.TawkToWidgetId.ValueString(),
	}
}

func (m *tagTawktoModel) FromParams(p map[string]string) {
	m.TawkToId = types.StringValue(p["tawkToId"])
	m.TawkToWidgetId = types.StringValue(p["tawkToWidgetId"])
}

func (m *tagTawktoModel) Common() *typedTagCommon {
	return &m.typedTagCommon
}

func newTagTawktoModel() typedTagModel {
	return &tagTawktoModel{}
}
