// Code generated by tools/gen. DO NOT EDIT.

package provider

import (
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type triggerFullscreenModel struct {
	typedTriggerCommon
	TriggerAction types.String `tfsdk:"trigger_action"`
	TriggerLimit  types.Int64  `tfsdk:"trigger_limit"`
}

func triggerFullscreenSchema() schema.Schema {
	return schema.Schema{
		Description: "Triggered when the window goes into or leaves full screen.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"container_id": schema.StringAttribute{
				Required:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
			},
			"name": schema.StringAttribute{
				Required: true,
			},
			"trigger_action": schema.StringAttribute{
				Required:    true,
				Description: "",
				Validators:  []validator.String{stringvalidator.OneOf("any", "enter", "exit")},
			},
			"trigger_limit": schema.Int64Attribute{
				Required:    false,
				Optional:    true,
				Description: "Enter \"0\" to trigger it each time the event occurs",
			},
		},
	}
}

func (m *triggerFullscreenModel) Meta() typedMeta {
	return typedMeta{
		TypeID:       "Fullscreen",
		ResourceName: "matomo_tagmanager_trigger_fullscreen",
		Schema:       triggerFullscreenSchema(),
	}
}

func (m *triggerFullscreenModel) ToParams() map[string]string {
	return map[string]string{
		"triggerAction": m.TriggerAction.ValueString(),
		"triggerLimit":  paramInt64String(m.TriggerLimit.ValueInt64()),
	}
}

func (m *triggerFullscreenModel) FromParams(p map[string]string) {
	m.TriggerAction = types.StringValue(p["triggerAction"])
	m.TriggerLimit = types.Int64Value(paramInt64Value(p["triggerLimit"]))
}

func (m *triggerFullscreenModel) Common() *typedTriggerCommon {
	return &m.typedTriggerCommon
}

func newTriggerFullscreenModel() typedTriggerModel {
	return &triggerFullscreenModel{}
}
