// Code generated by tools/gen. DO NOT EDIT.

package provider

import (
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
)

type triggerFormsubmitModel struct {
	typedTriggerCommon
}

func triggerFormsubmitSchema() schema.Schema {
	return schema.Schema{
		Description: "Triggered when any form is submitted.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"container_id": schema.StringAttribute{
				Required:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
			},
			"name": schema.StringAttribute{
				Required: true,
			},
		},
	}
}

func (m *triggerFormsubmitModel) Meta() typedMeta {
	return typedMeta{
		TypeID:       "FormSubmit",
		ResourceName: "matomo_tagmanager_trigger_formsubmit",
		Schema:       triggerFormsubmitSchema(),
	}
}

// ToParams only includes a key for an Optional parameter when it's
// actually set - sending an empty string for an unset Optional field
// (rather than omitting the key) was rejected by Matomo's own validation
// on live enum/format-constrained parameters (confirmed against a real
// acceptance-test run: an unset htmlPosition sent as "" was rejected by
// CustomHtml's own field validator, which never happens for a key that's
// simply absent from the parameters map).
func (m *triggerFormsubmitModel) ToParams() map[string]string {
	p := map[string]string{}
	return p
}

func (m *triggerFormsubmitModel) FromParams(p map[string]string) {
}

func (m *triggerFormsubmitModel) Common() *typedTriggerCommon {
	return &m.typedTriggerCommon
}

func newTriggerFormsubmitModel() typedTriggerModel {
	return &triggerFormsubmitModel{}
}
