// Code generated by tools/gen. DO NOT EDIT.

package provider

import (
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type tagAxeptioModel struct {
	typedTagCommon
	ProjectId types.String `tfsdk:"project_id"`
}

func tagAxeptioSchema() schema.Schema {
	return schema.Schema{
		Description: "Axeptio is a low-code Consent Management Platform.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"container_id": schema.StringAttribute{
				Required:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
			},
			"name": schema.StringAttribute{
				Required: true,
			},
			"status": schema.StringAttribute{
				Optional:      true,
				Computed:      true,
				Validators:    []validator.String{stringvalidator.OneOf("active", "paused")},
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"fire_trigger_ids": schema.ListAttribute{
				Required:    true,
				ElementType: types.StringType,
			},
			"block_trigger_ids": schema.ListAttribute{
				Optional:    true,
				ElementType: types.StringType,
			},
			"project_id": schema.StringAttribute{
				Required:    true,
				Description: "Enter your Project ID. You can find it in the settings menu of your Axeptio project.",
			},
		},
	}
}

func (m *tagAxeptioModel) Meta() typedMeta {
	return typedMeta{
		TypeID:       "Axeptio",
		ResourceName: "matomo_tagmanager_tag_axeptio",
		Schema:       tagAxeptioSchema(),
	}
}

func (m *tagAxeptioModel) ToParams() map[string]string {
	return map[string]string{
		"projectId": m.ProjectId.ValueString(),
	}
}

func (m *tagAxeptioModel) FromParams(p map[string]string) {
	m.ProjectId = types.StringValue(p["projectId"])
}

func (m *tagAxeptioModel) Common() *typedTagCommon {
	return &m.typedTagCommon
}

func newTagAxeptioModel() typedTagModel {
	return &tagAxeptioModel{}
}
