// Code generated by tools/gen. DO NOT EDIT.

package provider

import (
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type triggerAlllinksclickModel struct {
	typedTriggerCommon
}

func triggerAlllinksclickSchema() schema.Schema {
	return schema.Schema{
		Description: "Triggered when a link is clicked. It will be triggered on left, middle and right click.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"container_id": schema.StringAttribute{
				Required:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
			},
			"name": schema.StringAttribute{
				Required: true,
			},
		},
	}
}

func (m *triggerAlllinksclickModel) Meta() typedMeta {
	return typedMeta{
		TypeID:       "AllLinksClick",
		ResourceName: "matomo_tagmanager_trigger_alllinksclick",
		Schema:       triggerAlllinksclickSchema(),
	}
}

func (m *triggerAlllinksclickModel) ToParams() map[string]string {
	return map[string]string{}
}

func (m *triggerAlllinksclickModel) FromParams(p map[string]string) {
}

func (m *triggerAlllinksclickModel) Common() *typedTriggerCommon {
	return &m.typedTriggerCommon
}

func newTriggerAlllinksclickModel() typedTriggerModel {
	return &triggerAlllinksclickModel{}
}
