// Code generated by tools/gen. DO NOT EDIT.

package provider

import (
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type tagLivezilladynamicModel struct {
	typedTagCommon
	LivezillaDynamicID     types.String `tfsdk:"livezilla_dynamic_id"`
	LivezillaDynamicDomain types.String `tfsdk:"livezilla_dynamic_domain"`
	LivezillaDynamicDefer  types.Bool   `tfsdk:"livezilla_dynamic_defer"`
}

func tagLivezilladynamicSchema() schema.Schema {
	return schema.Schema{
		Description: "Livezilla lets you monitor and chat with visitors on your website.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"container_id": schema.StringAttribute{
				Required:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
			},
			"name": schema.StringAttribute{
				Required: true,
			},
			"status": schema.StringAttribute{
				Optional:      true,
				Computed:      true,
				Validators:    []validator.String{stringvalidator.OneOf("active", "paused")},
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"fire_trigger_ids": schema.ListAttribute{
				Required:    true,
				ElementType: types.StringType,
			},
			"block_trigger_ids": schema.ListAttribute{
				Optional:    true,
				ElementType: types.StringType,
			},
			"livezilla_dynamic_id": schema.StringAttribute{
				Required:    true,
				Description: "Insert the Livezilla ID from your Dynamic Code section.",
			},
			"livezilla_dynamic_domain": schema.StringAttribute{
				Required:    true,
				Description: "Enter the Domain where Livezilla is installed. Example: https://www.example.com",
			},
			"livezilla_dynamic_defer": schema.BoolAttribute{
				Required:    false,
				Optional:    true,
				Description: "In most cases you should let it activated.",
			},
		},
	}
}

func (m *tagLivezilladynamicModel) Meta() typedMeta {
	return typedMeta{
		TypeID:       "LivezillaDynamic",
		ResourceName: "matomo_tagmanager_tag_livezilladynamic",
		Schema:       tagLivezilladynamicSchema(),
	}
}

// ToParams only includes a key for an Optional parameter when it's
// actually set - sending an empty string for an unset Optional field
// (rather than omitting the key) was rejected by Matomo's own validation
// on live enum/format-constrained parameters (confirmed against a real
// acceptance-test run: an unset htmlPosition sent as "" was rejected by
// CustomHtml's own field validator, which never happens for a key that's
// simply absent from the parameters map).
func (m *tagLivezilladynamicModel) ToParams() map[string]string {
	p := map[string]string{}
	p["LivezillaDynamicID"] = m.LivezillaDynamicID.ValueString()
	p["LivezillaDynamicDomain"] = m.LivezillaDynamicDomain.ValueString()
	if !m.LivezillaDynamicDefer.IsNull() && !m.LivezillaDynamicDefer.IsUnknown() {
		p["LivezillaDynamicDefer"] = paramBoolString(m.LivezillaDynamicDefer.ValueBool())
	}
	return p
}

func (m *tagLivezilladynamicModel) FromParams(p map[string]string) {
	m.LivezillaDynamicID = types.StringValue(p["LivezillaDynamicID"])
	m.LivezillaDynamicDomain = types.StringValue(p["LivezillaDynamicDomain"])
	m.LivezillaDynamicDefer = types.BoolValue(paramBoolValue(p["LivezillaDynamicDefer"]))
}

func (m *tagLivezilladynamicModel) Common() *typedTagCommon {
	return &m.typedTagCommon
}

func newTagLivezilladynamicModel() typedTagModel {
	return &tagLivezilladynamicModel{}
}
