// Code generated by tools/gen. DO NOT EDIT.

package provider

import (
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/listplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type tagGoogleconsentmodev2Model struct {
	typedTagCommon
	ConsentAction []types.String `tfsdk:"consent_action"`
	ConsentTypes  []types.String `tfsdk:"consent_types"`
}

func tagGoogleconsentmodev2Schema() schema.Schema {
	return schema.Schema{
		Description: "Consent mode v2 allows you to communicate to Google the consent status of your users regarding cookies or application IDs.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"container_id": schema.StringAttribute{
				Required:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
			},
			"name": schema.StringAttribute{
				Required: true,
			},
			"status": schema.StringAttribute{
				Optional:      true,
				Computed:      true,
				Validators:    []validator.String{stringvalidator.OneOf("active", "paused")},
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"fire_trigger_ids": schema.ListAttribute{
				Required:    true,
				ElementType: types.StringType,
			},
			"block_trigger_ids": schema.ListAttribute{
				Optional:      true,
				Computed:      true,
				ElementType:   types.StringType,
				PlanModifiers: []planmodifier.List{listplanmodifier.UseStateForUnknown()},
			},
			"consent_action": schema.ListAttribute{
				ElementType: types.StringType,
				Required:    true,
				Description: "Select 'default' to set default values, and 'update' to handle users consent.",
			},
			"consent_types": schema.ListAttribute{
				ElementType: types.StringType,
				Required:    false,
				Optional:    true,
				// Computed + UseStateForUnknown: Matomo can return a
				// non-empty default for this field even when it was never
				// sent (e.g. a boolean parameter defaulting to false
				// server-side), which a bare Optional attribute can't
				// reconcile against an unset (null) config without
				// reporting a spurious diff on every subsequent plan - see
				// NeedsBoolPlanModifierImport's doc comment in
				// tools/gen/emit.go.
				Computed:      true,
				PlanModifiers: []planmodifier.List{listplanmodifier.UseStateForUnknown()},
				Description:   "",
			},
		},
	}
}

func (m *tagGoogleconsentmodev2Model) Meta() typedMeta {
	return typedMeta{
		TypeID:       "GoogleConsentModeV2",
		ResourceName: "matomo_tagmanager_tag_googleconsentmodev2",
		Schema:       tagGoogleconsentmodev2Schema(),
	}
}

// ToParams only includes a key for an Optional parameter when it's
// actually set - sending an empty string for an unset Optional field
// (rather than omitting the key) was rejected by Matomo's own validation
// on live enum/format-constrained parameters (confirmed against a real
// acceptance-test run: an unset htmlPosition sent as "" was rejected by
// CustomHtml's own field validator, which never happens for a key that's
// simply absent from the parameters map).
func (m *tagGoogleconsentmodev2Model) ToParams() map[string]string {
	p := map[string]string{}
	p["consentAction"] = paramListString(m.ConsentAction)
	if m.ConsentTypes != nil {
		p["consentTypes"] = paramListString(m.ConsentTypes)
	}
	return p
}

// FromParams mirrors ToParams' omission convention on the way back: a key
// absent from Matomo's response (an unset Optional parameter) must decode
// to a null value, not a zero value ("", false, 0) - decoding it to a
// zero value made every unset Optional parameter round-trip as a
// non-null empty value, which never matched the null the config itself
// produced and left Terraform reporting a perpetual "refresh plan not
// empty" diff on every generated resource with an unset Optional field
// (confirmed against a real acceptance-test run).
func (m *tagGoogleconsentmodev2Model) FromParams(p map[string]string) {
	m.ConsentAction = paramListValue(p["consentAction"])
	if v, ok := p["consentTypes"]; ok {
		m.ConsentTypes = paramListValue(v)
	} else {
		m.ConsentTypes = nil
	}
}

func (m *tagGoogleconsentmodev2Model) Common() *typedTagCommon {
	return &m.typedTagCommon
}

func newTagGoogleconsentmodev2Model() typedTagModel {
	return &tagGoogleconsentmodev2Model{}
}
