// Code generated by tools/gen. DO NOT EDIT.

package provider

import (
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type variableTimesinceloadModel struct {
	typedVariableCommon
	Unit types.String `tfsdk:"unit"`
}

func variableTimesinceloadSchema() schema.Schema {
	return schema.Schema{
		Description: "Calculates the time that has passed since the page was loaded.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"container_id": schema.StringAttribute{
				Required:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
			},
			"name": schema.StringAttribute{
				Required: true,
			},
			"default_value": schema.StringAttribute{
				Optional: true,
			},
			"unit": schema.StringAttribute{
				Required:    true,
				Description: "Select in which unit you want to retrieve the time.",
				Validators:  []validator.String{stringvalidator.OneOf("m", "ms", "s")},
			},
		},
	}
}

func (m *variableTimesinceloadModel) Meta() typedMeta {
	return typedMeta{
		TypeID:       "TimeSinceLoad",
		ResourceName: "matomo_tagmanager_variable_timesinceload",
		Schema:       variableTimesinceloadSchema(),
	}
}

func (m *variableTimesinceloadModel) ToParams() map[string]string {
	return map[string]string{
		"unit": m.Unit.ValueString(),
	}
}

func (m *variableTimesinceloadModel) FromParams(p map[string]string) {
	m.Unit = types.StringValue(p["unit"])
}

func (m *variableTimesinceloadModel) Common() *typedVariableCommon {
	return &m.typedVariableCommon
}

func newVariableTimesinceloadModel() typedVariableModel {
	return &variableTimesinceloadModel{}
}
