// Code generated by tools/gen. DO NOT EDIT.

package provider

import (
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type tagVisualwebsiteoptimizerModel struct {
	ID              types.String   `tfsdk:"id"`
	ContainerID     types.String   `tfsdk:"container_id"`
	Name            types.String   `tfsdk:"name"`
	Status          types.String   `tfsdk:"status"`
	FireTriggerIDs  []types.String `tfsdk:"fire_trigger_ids"`
	BlockTriggerIDs []types.String `tfsdk:"block_trigger_ids"`
	AccountId       types.String   `tfsdk:"account_id"`
}

func tagVisualwebsiteoptimizerSchema() schema.Schema {
	return schema.Schema{
		Description: "Visual Website Optimizer is an all-in-one A/B testing and Conversion Optimization Platform.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"container_id": schema.StringAttribute{
				Required:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
			},
			"name": schema.StringAttribute{
				Required: true,
			},
			"status": schema.StringAttribute{
				Optional:      true,
				Computed:      true,
				Validators:    []validator.String{stringvalidator.OneOf("active", "paused")},
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"fire_trigger_ids": schema.ListAttribute{
				Required:    true,
				ElementType: types.StringType,
			},
			"block_trigger_ids": schema.ListAttribute{
				Optional:    true,
				ElementType: types.StringType,
			},
			"account_id": schema.StringAttribute{
				Required:    true,
				Description: "Your Visual Website Optimizer Account ID",
			},
		},
	}
}

func (m *tagVisualwebsiteoptimizerModel) Meta() typedMeta {
	return typedMeta{
		TypeID:       "VisualWebsiteOptimizer",
		ResourceName: "matomo_tagmanager_tag_visualwebsiteoptimizer",
		Schema:       tagVisualwebsiteoptimizerSchema(),
	}
}

func (m *tagVisualwebsiteoptimizerModel) ToParams() map[string]string {
	return map[string]string{
		"accountId": m.AccountId.ValueString(),
	}
}

func (m *tagVisualwebsiteoptimizerModel) FromParams(p map[string]string) {
	m.AccountId = types.StringValue(p["accountId"])
}

func newTagVisualwebsiteoptimizerModel() typedModel {
	return &tagVisualwebsiteoptimizerModel{}
}
