// Code generated by tools/gen. DO NOT EDIT.

package provider

import (
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type triggerWindowunloadModel struct {
	ID          types.String `tfsdk:"id"`
	ContainerID types.String `tfsdk:"container_id"`
	Name        types.String `tfsdk:"name"`
}

func triggerWindowunloadSchema() schema.Schema {
	return schema.Schema{
		Description: "Triggered just before the browser window is closed or when the user navigates to a different page.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"container_id": schema.StringAttribute{
				Required:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
			},
			"name": schema.StringAttribute{
				Required: true,
			},
		},
	}
}

func (m *triggerWindowunloadModel) Meta() typedMeta {
	return typedMeta{
		TypeID:       "WindowUnload",
		ResourceName: "matomo_tagmanager_trigger_windowunload",
		Schema:       triggerWindowunloadSchema(),
	}
}

func (m *triggerWindowunloadModel) ToParams() map[string]string {
	return map[string]string{}
}

func (m *triggerWindowunloadModel) FromParams(p map[string]string) {
}

func newTriggerWindowunloadModel() typedModel {
	return &triggerWindowunloadModel{}
}
