// Code generated by tools/gen. DO NOT EDIT.

package provider

import (
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/nicole-ashley/terraform-provider-matomo/internal/matomo"
)

type tagGoogleanalytics4eventEventParameterModel struct {
	Parameter types.String `tfsdk:"parameter"`
	Value     types.String `tfsdk:"value"`
}

type tagGoogleanalytics4eventModel struct {
	typedTagCommon
	EventName       types.String                                  `tfsdk:"event_name"`
	EventParameters []tagGoogleanalytics4eventEventParameterModel `tfsdk:"event_parameter"`
}

func tagGoogleanalytics4eventSchema() schema.Schema {
	return schema.Schema{
		Description: "Send an event to Google Analytics 4. This tag requires Google Tag (gtag.js) tag to be configured.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"container_id": schema.StringAttribute{
				Required:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
			},
			"name": schema.StringAttribute{
				Required: true,
			},
			"status": schema.StringAttribute{
				Optional:      true,
				Computed:      true,
				Validators:    []validator.String{stringvalidator.OneOf("active", "paused")},
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"fire_trigger_ids": schema.ListAttribute{
				Required:    true,
				ElementType: types.StringType,
			},
			"block_trigger_ids": schema.ListAttribute{
				// Not Computed, unlike the other common/generated Optional
				// attributes: the generated Go field type for a List
				// attribute is a bare []types.String (see the Params
				// range below), which - unlike types.List - has no way to
				// represent "the whole list is unknown," so marking it
				// Computed makes terraform-plugin-framework fail outright
				// trying to decode plan's Unknown value into it
				// (confirmed against a real acceptance-test run: "Value
				// Conversion Error ... Received unknown value, however
				// the target type cannot handle unknown values"). A
				// List-typed field can still show a spurious
				// "refresh plan not empty" diff if Matomo defaults it to
				// a non-empty value server-side - fixing that for real
				// would mean switching the generated field type to
				// types.List, which is a larger change than this pass
				// covers.
				Optional:    true,
				ElementType: types.StringType,
			},
			"event_name": schema.StringAttribute{
				Required:    true,
				Description: "",
			},
		},
		Blocks: map[string]schema.Block{
			"event_parameter": schema.ListNestedBlock{
				Description: "",
				NestedObject: schema.NestedBlockObject{
					Attributes: map[string]schema.Attribute{
						"parameter": schema.StringAttribute{
							Required: true,
						},
						"value": schema.StringAttribute{
							Required: true,
						},
					},
				},
			},
		},
	}
}

func (m *tagGoogleanalytics4eventModel) Meta() typedMeta {
	return typedMeta{
		TypeID:       "GoogleAnalytics4Event",
		ResourceName: "matomo_tagmanager_tag_googleanalytics4event",
		Schema:       tagGoogleanalytics4eventSchema(),
	}
}

// ToParams only includes a key for an Optional parameter when it's
// actually set - sending an empty string for an unset Optional field
// (rather than omitting the key) was rejected by Matomo's own validation
// on live enum/format-constrained parameters (confirmed against a real
// acceptance-test run: an unset htmlPosition sent as "" was rejected by
// CustomHtml's own field validator, which never happens for a key that's
// simply absent from the parameters map). A List-typed parameter is sent
// via matomo.ListParam, never joined into a single string - see
// matomo.ParamValue's doc comment for why. A ListOfObjects (real nested
// block) parameter is sent via matomo.ListOfObjectsParam, row by row; a
// single-key MULTI_TUPLE parameter (SingleKeyName set, e.g. domains) stays
// a flat list in the schema/model but is wire-encoded via
// matomo.WrapSingleKeyParam instead of matomo.ListParam - see
// matomo.ParamValue's doc comment for why Matomo needs this shape.
func (m *tagGoogleanalytics4eventModel) ToParams() matomo.ParamsMap {
	p := matomo.ParamsMap{}
	p["eventName"] = matomo.ScalarParam(m.EventName.ValueString())
	if m.EventParameters != nil {
		rows := make([]map[string]string, len(m.EventParameters))
		for i, row := range m.EventParameters {
			rows[i] = map[string]string{
				"parameter": row.Parameter.ValueString(),
				"value":     row.Value.ValueString(),
			}
		}
		p["eventParameters"] = matomo.ListOfObjectsParam(rows)
	}
	return p
}

// FromParams mirrors ToParams' omission convention on the way back: a key
// absent from Matomo's response (an unset Optional parameter) must decode
// to a null value, not a zero value ("", false, 0) - decoding it to a
// zero value made every unset Optional parameter round-trip as a
// non-null empty value, which never matched the null the config itself
// produced and left Terraform reporting a perpetual "refresh plan not
// empty" diff on every generated resource with an unset Optional field
// (confirmed against a real acceptance-test run).
func (m *tagGoogleanalytics4eventModel) FromParams(p matomo.ParamsMap) {
	m.EventName = types.StringValue(p["eventName"].Scalar)
	if v, ok := p["eventParameters"]; ok {
		m.EventParameters = make([]tagGoogleanalytics4eventEventParameterModel, len(v.ListOfObjects))
		for i, row := range v.ListOfObjects {
			m.EventParameters[i] = tagGoogleanalytics4eventEventParameterModel{
				Parameter: types.StringValue(row["parameter"]),
				Value:     types.StringValue(row["value"]),
			}
		}
	} else {
		m.EventParameters = nil
	}
}

func (m *tagGoogleanalytics4eventModel) Common() *typedTagCommon {
	return &m.typedTagCommon
}

func newTagGoogleanalytics4eventModel() typedTagModel {
	return &tagGoogleanalytics4eventModel{}
}
