// Code generated by tools/gen. DO NOT EDIT.

package provider

import (
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type variableClickhtmlattributeModel struct {
	typedVariableCommon
	HtmlAttribute types.String `tfsdk:"html_attribute"`
}

func variableClickhtmlattributeSchema() schema.Schema {
	return schema.Schema{
		Description: "Reads a custom value from the clicked HTML attribute.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"container_id": schema.StringAttribute{
				Required:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
			},
			"name": schema.StringAttribute{
				Required: true,
			},
			"default_value": schema.StringAttribute{
				Optional: true,
			},
			"html_attribute": schema.StringAttribute{
				Required:    true,
				Description: "The name of the attribute, such as title, value, alt, or any other HTML attribute.",
			},
		},
	}
}

func (m *variableClickhtmlattributeModel) Meta() typedMeta {
	return typedMeta{
		TypeID:       "ClickHtmlAttribute",
		ResourceName: "matomo_tagmanager_variable_clickhtmlattribute",
		Schema:       variableClickhtmlattributeSchema(),
	}
}

func (m *variableClickhtmlattributeModel) ToParams() map[string]string {
	return map[string]string{
		"htmlAttribute": m.HtmlAttribute.ValueString(),
	}
}

func (m *variableClickhtmlattributeModel) FromParams(p map[string]string) {
	m.HtmlAttribute = types.StringValue(p["htmlAttribute"])
}

func (m *variableClickhtmlattributeModel) Common() *typedVariableCommon {
	return &m.typedVariableCommon
}

func newVariableClickhtmlattributeModel() typedVariableModel {
	return &variableClickhtmlattributeModel{}
}
