// Code generated by tools/gen. DO NOT EDIT.

package provider

import (
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type variableCustomrequestprocessingModel struct {
	typedVariableCommon
	JsFunction types.String `tfsdk:"js_function"`
}

func variableCustomrequestprocessingSchema() schema.Schema {
	return schema.Schema{
		Description: "A custom function to use with a Matomo Tracker that can transform all tracking requests.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"container_id": schema.StringAttribute{
				Required:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
			},
			"name": schema.StringAttribute{
				Required: true,
			},
			"default_value": schema.StringAttribute{
				Optional: true,
			},
			"js_function": schema.StringAttribute{
				Required:    true,
				Description: "The function will be called once the request (query parameters string) has been prepared, and before the request content is sent. If the return value evaluates to false, no request will be sent. Must start with \"function(request){\".",
			},
		},
	}
}

func (m *variableCustomrequestprocessingModel) Meta() typedMeta {
	return typedMeta{
		TypeID:       "CustomRequestProcessing",
		ResourceName: "matomo_tagmanager_variable_customrequestprocessing",
		Schema:       variableCustomrequestprocessingSchema(),
	}
}

func (m *variableCustomrequestprocessingModel) ToParams() map[string]string {
	return map[string]string{
		"jsFunction": m.JsFunction.ValueString(),
	}
}

func (m *variableCustomrequestprocessingModel) FromParams(p map[string]string) {
	m.JsFunction = types.StringValue(p["jsFunction"])
}

func (m *variableCustomrequestprocessingModel) Common() *typedVariableCommon {
	return &m.typedVariableCommon
}

func newVariableCustomrequestprocessingModel() typedVariableModel {
	return &variableCustomrequestprocessingModel{}
}
