// Code generated by tools/gen. DO NOT EDIT.

package provider

import (
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type triggerCustomeventModel struct {
	ID          types.String `tfsdk:"id"`
	ContainerID types.String `tfsdk:"container_id"`
	Name        types.String `tfsdk:"name"`
	EventName   types.String `tfsdk:"event_name"`
}

func triggerCustomeventSchema() schema.Schema {
	return schema.Schema{
		Description: "Triggered when a custom event is pushed to the Data-Layer.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"container_id": schema.StringAttribute{
				Required:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
			},
			"name": schema.StringAttribute{
				Required: true,
			},
			"event_name": schema.StringAttribute{
				Required:    true,
				Description: "The name of the event that is pushed to the Data-Layer. For example you can push an event by adding this to your website: _mtm.push({\"event\": \"my-custom-event\"});",
			},
		},
	}
}

func (m *triggerCustomeventModel) Meta() typedMeta {
	return typedMeta{
		TypeID:       "CustomEvent",
		ResourceName: "matomo_tagmanager_trigger_customevent",
		Schema:       triggerCustomeventSchema(),
	}
}

func (m *triggerCustomeventModel) ToParams() map[string]string {
	return map[string]string{
		"eventName": m.EventName.ValueString(),
	}
}

func (m *triggerCustomeventModel) FromParams(p map[string]string) {
	m.EventName = types.StringValue(p["eventName"])
}

func newTriggerCustomeventModel() typedModel {
	return &triggerCustomeventModel{}
}
