// Code generated by tools/gen. DO NOT EDIT.

package provider

import (
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type triggerAllelementsclickModel struct {
	ID          types.String `tfsdk:"id"`
	ContainerID types.String `tfsdk:"container_id"`
	Name        types.String `tfsdk:"name"`
}

func triggerAllelementsclickSchema() schema.Schema {
	return schema.Schema{
		Description: "Triggered when any element is clicked. It will be triggered on left, middle and right click.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"container_id": schema.StringAttribute{
				Required:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
			},
			"name": schema.StringAttribute{
				Required: true,
			},
		},
	}
}

func (m *triggerAllelementsclickModel) Meta() typedMeta {
	return typedMeta{
		TypeID:       "AllElementsClick",
		ResourceName: "matomo_tagmanager_trigger_allelementsclick",
		Schema:       triggerAllelementsclickSchema(),
	}
}

func (m *triggerAllelementsclickModel) ToParams() map[string]string {
	return map[string]string{}
}

func (m *triggerAllelementsclickModel) FromParams(p map[string]string) {
}

func newTriggerAllelementsclickModel() typedModel {
	return &triggerAllelementsclickModel{}
}
