// Code generated by tools/gen. DO NOT EDIT.

package provider

import (
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type triggerWindowleaveModel struct {
	ID           types.String `tfsdk:"id"`
	ContainerID  types.String `tfsdk:"container_id"`
	Name         types.String `tfsdk:"name"`
	TriggerLimit types.Int64  `tfsdk:"trigger_limit"`
}

func triggerWindowleaveSchema() schema.Schema {
	return schema.Schema{
		Description: "Triggered when the user is about to leave the current page by moving the mouse outside the window.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"container_id": schema.StringAttribute{
				Required:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
			},
			"name": schema.StringAttribute{
				Required: true,
			},
			"trigger_limit": schema.Int64Attribute{
				Required:    false,
				Optional:    true,
				Description: "Enter \"0\" to not limit how often the trigger should be triggered",
			},
		},
	}
}

func (m *triggerWindowleaveModel) Meta() typedMeta {
	return typedMeta{
		TypeID:       "WindowLeave",
		ResourceName: "matomo_tagmanager_trigger_windowleave",
		Schema:       triggerWindowleaveSchema(),
	}
}

func (m *triggerWindowleaveModel) ToParams() map[string]string {
	return map[string]string{
		"triggerLimit": paramInt64String(m.TriggerLimit.ValueInt64()),
	}
}

func (m *triggerWindowleaveModel) FromParams(p map[string]string) {
	m.TriggerLimit = types.Int64Value(paramInt64Value(p["triggerLimit"]))
}

func newTriggerWindowleaveModel() typedModel {
	return &triggerWindowleaveModel{}
}
