package provider

import (
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

// This file is generated by tools/gen only if it does not already exist.
// Once present, tools/gen never overwrites it - edit freely to add real
// assertions (this scaffold only proves create+read-back with placeholder
// values).
func TestAccTagThemecolor_createAndReadBack(t *testing.T) {
	testAccPreCheck(t)
	resourceName := "matomo_tagmanager_tag_themecolor.test"

	resource.Test(t, resource.TestCase{
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: testAccTagThemecolorConfig(),
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttrSet(resourceName, "id"),
				),
			},
			{
				ResourceName:      resourceName,
				ImportState:       true,
				ImportStateVerify: true,
			},
		},
	})
}

func testAccTagThemecolorConfig() string {
	return `
provider "matomo" {}

resource "matomo_site" "test" {
  name = "Generated ThemeColor Acceptance Site"
  urls = ["https://acc-generated-themecolor.example.com"]
}

resource "matomo_tagmanager_container" "test" {
  site_id = matomo_site.test.id
  context = "web"
  name    = "Generated ThemeColor Acceptance Container"
}

resource "matomo_tagmanager_trigger" "test" {
  container_id = matomo_tagmanager_container.test.id
  type         = "PageView"
  name         = "Generated ThemeColor Acceptance Trigger"
}

resource "matomo_tagmanager_tag_themecolor" "test" {
  container_id = matomo_tagmanager_container.test.id
  name         = "generated-test-themecolor"
  fire_trigger_ids = [matomo_tagmanager_trigger.test.id]
  // ThemeColorTag.php validates against /^#(?:[0-9a-fA-F]{3}){1,2}$/
  // ("Please enter a valid hexadecimal color").
  theme_color = "#FF5733"
}
`
}
