// Code generated by tools/gen. DO NOT EDIT.

package provider

import (
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/listplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type tagAddthisModel struct {
	typedTagCommon
	AddThisPubId          types.String `tfsdk:"add_this_pub_id"`
	AddThisParentSelector types.String `tfsdk:"add_this_parent_selector"`
}

func tagAddthisSchema() schema.Schema {
	return schema.Schema{
		Description: "Add the AddThis social media buttons and more to your website.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"container_id": schema.StringAttribute{
				Required:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
			},
			"name": schema.StringAttribute{
				Required: true,
			},
			"status": schema.StringAttribute{
				Optional:      true,
				Computed:      true,
				Validators:    []validator.String{stringvalidator.OneOf("active", "paused")},
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"fire_trigger_ids": schema.ListAttribute{
				Required:    true,
				ElementType: types.StringType,
			},
			"block_trigger_ids": schema.ListAttribute{
				Optional:      true,
				Computed:      true,
				ElementType:   types.StringType,
				PlanModifiers: []planmodifier.List{listplanmodifier.UseStateForUnknown()},
			},
			"add_this_pub_id": schema.StringAttribute{
				Required:    true,
				Description: "Create a new site in Shareaholic and paste the site ID here",
			},
			"add_this_parent_selector": schema.StringAttribute{
				Required: false,
				Optional: true,
				// Computed + UseStateForUnknown: Matomo can return a
				// non-empty default for this field even when it was never
				// sent (e.g. a boolean parameter defaulting to false
				// server-side), which a bare Optional attribute can't
				// reconcile against an unset (null) config without
				// reporting a spurious diff on every subsequent plan - see
				// NeedsBoolPlanModifierImport's doc comment in
				// tools/gen/emit.go.
				Computed:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
				Description:   "Optionally enter a CSS selector to the element where the Inline Tools should be added.",
			},
		},
	}
}

func (m *tagAddthisModel) Meta() typedMeta {
	return typedMeta{
		TypeID:       "AddThis",
		ResourceName: "matomo_tagmanager_tag_addthis",
		Schema:       tagAddthisSchema(),
	}
}

// ToParams only includes a key for an Optional parameter when it's
// actually set - sending an empty string for an unset Optional field
// (rather than omitting the key) was rejected by Matomo's own validation
// on live enum/format-constrained parameters (confirmed against a real
// acceptance-test run: an unset htmlPosition sent as "" was rejected by
// CustomHtml's own field validator, which never happens for a key that's
// simply absent from the parameters map).
func (m *tagAddthisModel) ToParams() map[string]string {
	p := map[string]string{}
	p["AddThisPubId"] = m.AddThisPubId.ValueString()
	if !m.AddThisParentSelector.IsNull() && !m.AddThisParentSelector.IsUnknown() {
		p["AddThisParentSelector"] = m.AddThisParentSelector.ValueString()
	}
	return p
}

// FromParams mirrors ToParams' omission convention on the way back: a key
// absent from Matomo's response (an unset Optional parameter) must decode
// to a null value, not a zero value ("", false, 0) - decoding it to a
// zero value made every unset Optional parameter round-trip as a
// non-null empty value, which never matched the null the config itself
// produced and left Terraform reporting a perpetual "refresh plan not
// empty" diff on every generated resource with an unset Optional field
// (confirmed against a real acceptance-test run).
func (m *tagAddthisModel) FromParams(p map[string]string) {
	m.AddThisPubId = types.StringValue(p["AddThisPubId"])
	if v, ok := p["AddThisParentSelector"]; ok {
		m.AddThisParentSelector = types.StringValue(v)
	} else {
		m.AddThisParentSelector = types.StringNull()
	}
}

func (m *tagAddthisModel) Common() *typedTagCommon {
	return &m.typedTagCommon
}

func newTagAddthisModel() typedTagModel {
	return &tagAddthisModel{}
}
