// Code generated by tools/gen. DO NOT EDIT.

package provider

import (
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
)

type triggerDomreadyModel struct {
	typedTriggerCommon
}

func triggerDomreadySchema() schema.Schema {
	return schema.Schema{
		Description: "Triggered as soon as all the HTML has been received and parsed.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"container_id": schema.StringAttribute{
				Required:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
			},
			"name": schema.StringAttribute{
				Required: true,
			},
		},
	}
}

func (m *triggerDomreadyModel) Meta() typedMeta {
	return typedMeta{
		TypeID:       "DomReady",
		ResourceName: "matomo_tagmanager_trigger_domready",
		Schema:       triggerDomreadySchema(),
	}
}

func (m *triggerDomreadyModel) ToParams() map[string]string {
	return map[string]string{}
}

func (m *triggerDomreadyModel) FromParams(p map[string]string) {
}

func (m *triggerDomreadyModel) Common() *typedTriggerCommon {
	return &m.typedTriggerCommon
}

func newTriggerDomreadyModel() typedTriggerModel {
	return &triggerDomreadyModel{}
}
