// Code generated by tools/gen. DO NOT EDIT.

package provider

import (
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type tagEmarsysModel struct {
	ID              types.String   `tfsdk:"id"`
	ContainerID     types.String   `tfsdk:"container_id"`
	Name            types.String   `tfsdk:"name"`
	Status          types.String   `tfsdk:"status"`
	FireTriggerIDs  []types.String `tfsdk:"fire_trigger_ids"`
	BlockTriggerIDs []types.String `tfsdk:"block_trigger_ids"`
	MerchantId      types.String   `tfsdk:"merchant_id"`
	CommandCategory types.String   `tfsdk:"command_category"`
	CommandView     types.String   `tfsdk:"command_view"`
	CommandTag      types.String   `tfsdk:"command_tag"`
	CommandGo       types.Bool     `tfsdk:"command_go"`
}

func tagEmarsysSchema() schema.Schema {
	return schema.Schema{
		Description: "Emarsys is the largest independent marketing platform in the world.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"container_id": schema.StringAttribute{
				Required:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
			},
			"name": schema.StringAttribute{
				Required: true,
			},
			"status": schema.StringAttribute{
				Optional:      true,
				Computed:      true,
				Validators:    []validator.String{stringvalidator.OneOf("active", "paused")},
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"fire_trigger_ids": schema.ListAttribute{
				Required:    true,
				ElementType: types.StringType,
			},
			"block_trigger_ids": schema.ListAttribute{
				Optional:    true,
				ElementType: types.StringType,
			},
			"merchant_id": schema.StringAttribute{
				Required:    true,
				Description: "Your Emarsys Merchant ID",
			},
			"command_category": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Description: "Report the category currently browsed by the visitor.",
			},
			"command_view": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Description: "Report a product view.",
			},
			"command_tag": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Description: "Add an arbitrary tag to the current event. The tag is collected and can be accessed later from other Emarsys products.",
			},
			"command_go": schema.BoolAttribute{
				Required:    false,
				Optional:    true,
				Description: "Execute commands in the queue, that is, send them to the recommender service for processing.",
			},
		},
	}
}

func (m *tagEmarsysModel) Meta() typedMeta {
	return typedMeta{
		TypeID:       "Emarsys",
		ResourceName: "matomo_tagmanager_tag_emarsys",
		Schema:       tagEmarsysSchema(),
	}
}

func (m *tagEmarsysModel) ToParams() map[string]string {
	return map[string]string{
		"merchantId":      m.MerchantId.ValueString(),
		"commandCategory": m.CommandCategory.ValueString(),
		"commandView":     m.CommandView.ValueString(),
		"commandTag":      m.CommandTag.ValueString(),
		"commandGo":       paramBoolString(m.CommandGo.ValueBool()),
	}
}

func (m *tagEmarsysModel) FromParams(p map[string]string) {
	m.MerchantId = types.StringValue(p["merchantId"])
	m.CommandCategory = types.StringValue(p["commandCategory"])
	m.CommandView = types.StringValue(p["commandView"])
	m.CommandTag = types.StringValue(p["commandTag"])
	m.CommandGo = types.BoolValue(paramBoolValue(p["commandGo"]))
}

func newTagEmarsysModel() typedModel {
	return &tagEmarsysModel{}
}
