package provider

import (
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

// This file is generated by tools/gen only if it does not already exist.
// Once present, tools/gen never overwrites it - edit freely to add real
// assertions (this scaffold only proves create+read-back with placeholder
// values).
func TestAccTriggerAlldownloadsclick_createAndReadBack(t *testing.T) {
	testAccPreCheck(t)
	resourceName := "matomo_tagmanager_trigger_alldownloadsclick.test"

	resource.Test(t, resource.TestCase{
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: testAccTriggerAlldownloadsclickConfig(),
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttrSet(resourceName, "id"),
				),
			},
			{
				ResourceName:      resourceName,
				ImportState:       true,
				ImportStateVerify: true,
			},
		},
	})
}

func testAccTriggerAlldownloadsclickConfig() string {
	return `
provider "matomo" {}

resource "matomo_site" "test" {
  name = "Generated AllDownloadsClick Acceptance Site"
  urls = ["https://acc-generated-alldownloadsclick.example.com"]
}

resource "matomo_tagmanager_container" "test" {
  site_id = matomo_site.test.id
  context = "web"
  name    = "Generated AllDownloadsClick Acceptance Container"
}

resource "matomo_tagmanager_trigger_alldownloadsclick" "test" {
  container_id = matomo_tagmanager_container.test.id
  name         = "generated-test-alldownloadsclick"
  download_extensions = "test-value"
}
`
}
