// Code generated by tools/gen. DO NOT EDIT.

package provider

import (
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/nicole-ashley/terraform-provider-matomo/internal/matomo"
)

type tagTawktoModel struct {
	typedTagCommon
	TawkToId       types.String `tfsdk:"tawk_to_id"`
	TawkToWidgetId types.String `tfsdk:"tawk_to_widget_id"`
}

func tagTawktoSchema() schema.Schema {
	return schema.Schema{
		Description: "Tawk.to lets you monitor and chat with visitors on your website.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"container_id": schema.StringAttribute{
				Required:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
			},
			"name": schema.StringAttribute{
				Required: true,
			},
			"status": schema.StringAttribute{
				Optional:      true,
				Computed:      true,
				Validators:    []validator.String{stringvalidator.OneOf("active", "paused")},
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"fire_trigger_ids": schema.ListAttribute{
				Required:    true,
				ElementType: types.StringType,
			},
			"block_trigger_ids": schema.ListAttribute{
				// Not Computed, unlike the other common/generated Optional
				// attributes: the generated Go field type for a List
				// attribute is a bare []types.String (see the Params
				// range below), which - unlike types.List - has no way to
				// represent "the whole list is unknown," so marking it
				// Computed makes terraform-plugin-framework fail outright
				// trying to decode plan's Unknown value into it
				// (confirmed against a real acceptance-test run: "Value
				// Conversion Error ... Received unknown value, however
				// the target type cannot handle unknown values"). A
				// List-typed field can still show a spurious
				// "refresh plan not empty" diff if Matomo defaults it to
				// a non-empty value server-side - fixing that for real
				// would mean switching the generated field type to
				// types.List, which is a larger change than this pass
				// covers.
				Optional:    true,
				ElementType: types.StringType,
			},
			"tawk_to_id": schema.StringAttribute{
				Required:    true,
				Description: "You can get the Site ID by logging into Tawk.to, going to \"Administration\" and clicking on \"Property Settings\". The Site ID has typically about 25 characters, for example \"123451c27295ad739e46b6b1\".",
			},
			"tawk_to_widget_id": schema.StringAttribute{
				Required:    true,
				Description: "You can get the Widget ID by logging into Tawk.to, going to \"Administration\" and clicking on \"Chat Widget\" and selecting an appropriate widget. The widget ID can be retrieved from \"Direct Chat Link\" as https://tawk.to/chat/{SITE_ID}/{WIDGET_ID}.",
			},
		},
	}
}

func (m *tagTawktoModel) Meta() typedMeta {
	return typedMeta{
		TypeID:       "TawkTo",
		ResourceName: "matomo_tagmanager_tag_tawkto",
		Schema:       tagTawktoSchema(),
	}
}

// ToParams only includes a key for an Optional parameter when it's
// actually set - sending an empty string for an unset Optional field
// (rather than omitting the key) was rejected by Matomo's own validation
// on live enum/format-constrained parameters (confirmed against a real
// acceptance-test run: an unset htmlPosition sent as "" was rejected by
// CustomHtml's own field validator, which never happens for a key that's
// simply absent from the parameters map). A List-typed parameter is sent
// via matomo.ListParam, never joined into a single string - see
// matomo.ParamValue's doc comment for why. A ListOfObjects (real nested
// block) parameter is sent via matomo.ListOfObjectsParam, row by row; a
// single-key MULTI_TUPLE parameter (SingleKeyName set, e.g. domains) stays
// a flat list in the schema/model but is wire-encoded via
// matomo.WrapSingleKeyParam instead of matomo.ListParam - see
// matomo.ParamValue's doc comment for why Matomo needs this shape.
func (m *tagTawktoModel) ToParams() matomo.ParamsMap {
	p := matomo.ParamsMap{}
	p["tawkToId"] = matomo.ScalarParam(m.TawkToId.ValueString())
	p["tawkToWidgetId"] = matomo.ScalarParam(m.TawkToWidgetId.ValueString())
	return p
}

// FromParams mirrors ToParams' omission convention on the way back: a key
// absent from Matomo's response (an unset Optional parameter) must decode
// to a null value, not a zero value ("", false, 0) - decoding it to a
// zero value made every unset Optional parameter round-trip as a
// non-null empty value, which never matched the null the config itself
// produced and left Terraform reporting a perpetual "refresh plan not
// empty" diff on every generated resource with an unset Optional field
// (confirmed against a real acceptance-test run).
func (m *tagTawktoModel) FromParams(p matomo.ParamsMap) {
	m.TawkToId = types.StringValue(p["tawkToId"].Scalar)
	m.TawkToWidgetId = types.StringValue(p["tawkToWidgetId"].Scalar)
}

func (m *tagTawktoModel) Common() *typedTagCommon {
	return &m.typedTagCommon
}

func newTagTawktoModel() typedTagModel {
	return &tagTawktoModel{}
}
