// Code generated by tools/gen. DO NOT EDIT.

package provider

import (
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type variableUrlparameterModel struct {
	ID            types.String `tfsdk:"id"`
	ContainerID   types.String `tfsdk:"container_id"`
	Name          types.String `tfsdk:"name"`
	DefaultValue  types.String `tfsdk:"default_value"`
	ParameterName types.String `tfsdk:"parameter_name"`
}

func variableUrlparameterSchema() schema.Schema {
	return schema.Schema{
		Description: "Gets the value of a specific URL parameter.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"container_id": schema.StringAttribute{
				Required:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
			},
			"name": schema.StringAttribute{
				Required: true,
			},
			"default_value": schema.StringAttribute{
				Optional: true,
			},
			"parameter_name": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Description: "For example when your page has URL parameters such as \"?lang=NZ\" and you want to get the value \"NZ\", then you need to enter \"lang\".",
			},
		},
	}
}

func (m *variableUrlparameterModel) Meta() typedMeta {
	return typedMeta{
		TypeID:       "UrlParameter",
		ResourceName: "matomo_tagmanager_variable_urlparameter",
		Schema:       variableUrlparameterSchema(),
	}
}

func (m *variableUrlparameterModel) ToParams() map[string]string {
	return map[string]string{
		"parameterName": m.ParameterName.ValueString(),
	}
}

func (m *variableUrlparameterModel) FromParams(p map[string]string) {
	m.ParameterName = types.StringValue(p["parameterName"])
}

func newVariableUrlparameterModel() typedModel {
	return &variableUrlparameterModel{}
}
