// Code generated by tools/gen. DO NOT EDIT.

package provider

import (
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type tagShareaholicModel struct {
	ID                        types.String   `tfsdk:"id"`
	ContainerID               types.String   `tfsdk:"container_id"`
	Name                      types.String   `tfsdk:"name"`
	Status                    types.String   `tfsdk:"status"`
	FireTriggerIDs            []types.String `tfsdk:"fire_trigger_ids"`
	BlockTriggerIDs           []types.String `tfsdk:"block_trigger_ids"`
	ShareaholicSiteId         types.String   `tfsdk:"shareaholic_site_id"`
	ShareaholicInPageApp      types.String   `tfsdk:"shareaholic_in_page_app"`
	ShareaholicAppId          types.String   `tfsdk:"shareaholic_app_id"`
	ShareaholicParentSelector types.String   `tfsdk:"shareaholic_parent_selector"`
}

func tagShareaholicSchema() schema.Schema {
	return schema.Schema{
		Description: "Content Marketing Platform & Website Traffic Tools",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"container_id": schema.StringAttribute{
				Required:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
			},
			"name": schema.StringAttribute{
				Required: true,
			},
			"status": schema.StringAttribute{
				Optional:      true,
				Computed:      true,
				Validators:    []validator.String{stringvalidator.OneOf("active", "paused")},
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"fire_trigger_ids": schema.ListAttribute{
				Required:    true,
				ElementType: types.StringType,
			},
			"block_trigger_ids": schema.ListAttribute{
				Optional:    true,
				ElementType: types.StringType,
			},
			"shareaholic_site_id": schema.StringAttribute{
				Required:    true,
				Description: "Create a new site in Shareaholic and paste the site ID here",
			},
			"shareaholic_in_page_app": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Description: "Here you can optionally add an In-Page App to your website.",
				Validators:  []validator.String{stringvalidator.OneOf("", "follow_buttons", "recommendations", "share_buttons", "total_share_count")},
			},
			"shareaholic_app_id": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Description: "If you want to add an In-Page App enter the App ID here. It is about eight digits long. The App ID is not required for the Total Share Counter.",
			},
			"shareaholic_parent_selector": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Description: "Enter a CSS selector to the element where the In-Page App should be added.",
			},
		},
	}
}

func (m *tagShareaholicModel) Meta() typedMeta {
	return typedMeta{
		TypeID:       "Shareaholic",
		ResourceName: "matomo_tagmanager_tag_shareaholic",
		Schema:       tagShareaholicSchema(),
	}
}

func (m *tagShareaholicModel) ToParams() map[string]string {
	return map[string]string{
		"shareaholicSiteId":         m.ShareaholicSiteId.ValueString(),
		"shareaholicInPageApp":      m.ShareaholicInPageApp.ValueString(),
		"shareaholicAppId":          m.ShareaholicAppId.ValueString(),
		"shareaholicParentSelector": m.ShareaholicParentSelector.ValueString(),
	}
}

func (m *tagShareaholicModel) FromParams(p map[string]string) {
	m.ShareaholicSiteId = types.StringValue(p["shareaholicSiteId"])
	m.ShareaholicInPageApp = types.StringValue(p["shareaholicInPageApp"])
	m.ShareaholicAppId = types.StringValue(p["shareaholicAppId"])
	m.ShareaholicParentSelector = types.StringValue(p["shareaholicParentSelector"])
}

func newTagShareaholicModel() typedModel {
	return &tagShareaholicModel{}
}
