package provider

import (
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

// This file is generated by tools/gen only if it does not already exist.
// Once present, tools/gen never overwrites it - edit freely to add real
// assertions (this scaffold only proves create+read-back with placeholder
// values).
func TestAccTagOnetrust_createAndReadBack(t *testing.T) {
	testAccPreCheck(t)
	resourceName := "matomo_tagmanager_tag_onetrust.test"

	resource.Test(t, resource.TestCase{
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: testAccTagOnetrustConfig(),
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttrSet(resourceName, "id"),
				),
			},
			{
				ResourceName:      resourceName,
				ImportState:       true,
				ImportStateVerify: true,
			},
		},
	})
}

func testAccTagOnetrustConfig() string {
	return `
provider "matomo" {}

resource "matomo_site" "test" {
  name = "Generated OneTrust Acceptance Site"
  urls = ["https://acc-generated-onetrust.example.com"]
}

resource "matomo_tagmanager_container" "test" {
  site_id = matomo_site.test.id
  context = "web"
  name    = "Generated OneTrust Acceptance Container"
}

resource "matomo_tagmanager_trigger" "test" {
  container_id = matomo_tagmanager_container.test.id
  type         = "PageView"
  name         = "Generated OneTrust Acceptance Trigger"
}

resource "matomo_tagmanager_tag_onetrust" "test" {
  container_id = matomo_tagmanager_container.test.id
  name         = "generated-test-onetrust"
  fire_trigger_ids = [matomo_tagmanager_trigger.test.id]
  domain = "test-value"
}
`
}
