// Code generated by tools/gen. DO NOT EDIT.

package provider

import (
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type triggerWindowleaveModel struct {
	typedTriggerCommon
	TriggerLimit types.Int64 `tfsdk:"trigger_limit"`
}

func triggerWindowleaveSchema() schema.Schema {
	return schema.Schema{
		Description: "Triggered when the user is about to leave the current page by moving the mouse outside the window.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"container_id": schema.StringAttribute{
				Required:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
			},
			"name": schema.StringAttribute{
				Required: true,
			},
			"trigger_limit": schema.Int64Attribute{
				Required:    false,
				Optional:    true,
				Description: "Enter \"0\" to not limit how often the trigger should be triggered",
			},
		},
	}
}

func (m *triggerWindowleaveModel) Meta() typedMeta {
	return typedMeta{
		TypeID:       "WindowLeave",
		ResourceName: "matomo_tagmanager_trigger_windowleave",
		Schema:       triggerWindowleaveSchema(),
	}
}

// ToParams only includes a key for an Optional parameter when it's
// actually set - sending an empty string for an unset Optional field
// (rather than omitting the key) was rejected by Matomo's own validation
// on live enum/format-constrained parameters (confirmed against a real
// acceptance-test run: an unset htmlPosition sent as "" was rejected by
// CustomHtml's own field validator, which never happens for a key that's
// simply absent from the parameters map).
func (m *triggerWindowleaveModel) ToParams() map[string]string {
	p := map[string]string{}
	if !m.TriggerLimit.IsNull() && !m.TriggerLimit.IsUnknown() {
		p["triggerLimit"] = paramInt64String(m.TriggerLimit.ValueInt64())
	}
	return p
}

func (m *triggerWindowleaveModel) FromParams(p map[string]string) {
	m.TriggerLimit = types.Int64Value(paramInt64Value(p["triggerLimit"]))
}

func (m *triggerWindowleaveModel) Common() *typedTriggerCommon {
	return &m.typedTriggerCommon
}

func newTriggerWindowleaveModel() typedTriggerModel {
	return &triggerWindowleaveModel{}
}
