// Code generated by tools/gen. DO NOT EDIT.

package provider

import (
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/listplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type tagSentryravenModel struct {
	typedTagCommon
	SentryDSN types.String `tfsdk:"sentry_dsn"`
}

func tagSentryravenSchema() schema.Schema {
	return schema.Schema{
		Description: "Sentry.io is an Open-Source error tracking tool that allows you to detect errors that happen on your website.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"container_id": schema.StringAttribute{
				Required:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
			},
			"name": schema.StringAttribute{
				Required: true,
			},
			"status": schema.StringAttribute{
				Optional:      true,
				Computed:      true,
				Validators:    []validator.String{stringvalidator.OneOf("active", "paused")},
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"fire_trigger_ids": schema.ListAttribute{
				Required:    true,
				ElementType: types.StringType,
			},
			"block_trigger_ids": schema.ListAttribute{
				Optional:      true,
				Computed:      true,
				ElementType:   types.StringType,
				PlanModifiers: []planmodifier.List{listplanmodifier.UseStateForUnknown()},
			},
			"sentry_dsn": schema.StringAttribute{
				Required:    true,
				Description: "The DSN (Data Source Name) of your sentry.io project. It should look like 'https://<key>@sentry.io/<project>'",
			},
		},
	}
}

func (m *tagSentryravenModel) Meta() typedMeta {
	return typedMeta{
		TypeID:       "SentryRaven",
		ResourceName: "matomo_tagmanager_tag_sentryraven",
		Schema:       tagSentryravenSchema(),
	}
}

// ToParams only includes a key for an Optional parameter when it's
// actually set - sending an empty string for an unset Optional field
// (rather than omitting the key) was rejected by Matomo's own validation
// on live enum/format-constrained parameters (confirmed against a real
// acceptance-test run: an unset htmlPosition sent as "" was rejected by
// CustomHtml's own field validator, which never happens for a key that's
// simply absent from the parameters map).
func (m *tagSentryravenModel) ToParams() map[string]string {
	p := map[string]string{}
	p["sentryDSN"] = m.SentryDSN.ValueString()
	return p
}

// FromParams mirrors ToParams' omission convention on the way back: a key
// absent from Matomo's response (an unset Optional parameter) must decode
// to a null value, not a zero value ("", false, 0) - decoding it to a
// zero value made every unset Optional parameter round-trip as a
// non-null empty value, which never matched the null the config itself
// produced and left Terraform reporting a perpetual "refresh plan not
// empty" diff on every generated resource with an unset Optional field
// (confirmed against a real acceptance-test run).
func (m *tagSentryravenModel) FromParams(p map[string]string) {
	m.SentryDSN = types.StringValue(p["sentryDSN"])
}

func (m *tagSentryravenModel) Common() *typedTagCommon {
	return &m.typedTagCommon
}

func newTagSentryravenModel() typedTagModel {
	return &tagSentryravenModel{}
}
