// Code generated by tools/gen. DO NOT EDIT.

package provider

import (
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/nicole-ashley/terraform-provider-matomo/internal/matomo"
)

type triggerElementvisibilityModel struct {
	typedTriggerCommon
	SelectionMethod   types.String `tfsdk:"selection_method"`
	CssSelector       types.String `tfsdk:"css_selector"`
	ElementId         types.String `tfsdk:"element_id"`
	FireTriggerWhen   types.String `tfsdk:"fire_trigger_when"`
	MinPercentVisible types.Int64  `tfsdk:"min_percent_visible"`
	ObserveDomChanges types.Bool   `tfsdk:"observe_dom_changes"`
}

func triggerElementvisibilitySchema() schema.Schema {
	return schema.Schema{
		Description: "Triggered when a specific element becomes visible.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"container_id": schema.StringAttribute{
				Required:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
			},
			"name": schema.StringAttribute{
				Required: true,
			},
			"selection_method": schema.StringAttribute{
				Required:    true,
				Description: "Select the way you want to identify an element you want to select.",
				Validators: []validator.String{
					stringvalidator.OneOf("cssSelector", "elementId"),
				},
			},
			"css_selector": schema.StringAttribute{
				Required: false,
				Optional: true,
				// Computed + UseStateForUnknown: Matomo can return a
				// non-empty default for this field even when it was never
				// sent (e.g. a boolean parameter defaulting to false
				// server-side), which a bare Optional attribute can't
				// reconcile against an unset (null) config without
				// reporting a spurious diff on every subsequent plan - see
				// NeedsBoolPlanModifierImport's doc comment in
				// tools/gen/emit.go. Skipped for List: the generated Go
				// field type is a bare []types.String, which can't
				// represent "the whole list is unknown" the way
				// Computed's plan semantics require (see
				// block_trigger_ids' comment above for the same
				// limitation and the confirmed failure it caused).
				Computed:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
				Description:   "A CSS selector allows you to select an element by id, className, element names, etc. If multiple elements match this selector, the first matching element will be used to get the value from. Examples for valid selectors are \".classname\", \"#id\" or \"li a\".",
				Validators: []validator.String{
					conditionRequiredValidator{Condition: matomo.EqNode{Field: "selection_method", Value: "cssSelector", Negate: false}},
				},
			},
			"element_id": schema.StringAttribute{
				Required: false,
				Optional: true,
				// Computed + UseStateForUnknown: Matomo can return a
				// non-empty default for this field even when it was never
				// sent (e.g. a boolean parameter defaulting to false
				// server-side), which a bare Optional attribute can't
				// reconcile against an unset (null) config without
				// reporting a spurious diff on every subsequent plan - see
				// NeedsBoolPlanModifierImport's doc comment in
				// tools/gen/emit.go. Skipped for List: the generated Go
				// field type is a bare []types.String, which can't
				// represent "the whole list is unknown" the way
				// Computed's plan semantics require (see
				// block_trigger_ids' comment above for the same
				// limitation and the confirmed failure it caused).
				Computed:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
				Description:   "The id attribute specifies a unique id for an HTML element. Insert here the value of an ID attribute of any element within your website.",
				Validators: []validator.String{
					conditionRequiredValidator{Condition: matomo.EqNode{Field: "selection_method", Value: "elementId", Negate: false}},
				},
			},
			"fire_trigger_when": schema.StringAttribute{
				Required:    true,
				Description: "",
				Validators: []validator.String{
					stringvalidator.OneOf("every", "onceElement", "oncePage"),
				},
			},
			"min_percent_visible": schema.Int64Attribute{
				Required: false,
				Optional: true,
				// Computed + UseStateForUnknown: Matomo can return a
				// non-empty default for this field even when it was never
				// sent (e.g. a boolean parameter defaulting to false
				// server-side), which a bare Optional attribute can't
				// reconcile against an unset (null) config without
				// reporting a spurious diff on every subsequent plan - see
				// NeedsBoolPlanModifierImport's doc comment in
				// tools/gen/emit.go. Skipped for List: the generated Go
				// field type is a bare []types.String, which can't
				// represent "the whole list is unknown" the way
				// Computed's plan semantics require (see
				// block_trigger_ids' comment above for the same
				// limitation and the confirmed failure it caused).
				Computed:      true,
				PlanModifiers: []planmodifier.Int64{int64planmodifier.UseStateForUnknown()},
				Description:   "",
			},
			"observe_dom_changes": schema.BoolAttribute{
				Required: false,
				Optional: true,
				// Computed + UseStateForUnknown: Matomo can return a
				// non-empty default for this field even when it was never
				// sent (e.g. a boolean parameter defaulting to false
				// server-side), which a bare Optional attribute can't
				// reconcile against an unset (null) config without
				// reporting a spurious diff on every subsequent plan - see
				// NeedsBoolPlanModifierImport's doc comment in
				// tools/gen/emit.go. Skipped for List: the generated Go
				// field type is a bare []types.String, which can't
				// represent "the whole list is unknown" the way
				// Computed's plan semantics require (see
				// block_trigger_ids' comment above for the same
				// limitation and the confirmed failure it caused).
				Computed:      true,
				PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()},
				Description:   "",
			},
		},
	}
}

func (m *triggerElementvisibilityModel) Meta() typedMeta {
	return typedMeta{
		TypeID:       "ElementVisibility",
		ResourceName: "matomo_tagmanager_trigger_elementvisibility",
		Schema:       triggerElementvisibilitySchema(),
	}
}

// ToParams only includes a key for an Optional parameter when it's
// actually set - sending an empty string for an unset Optional field
// (rather than omitting the key) was rejected by Matomo's own validation
// on live enum/format-constrained parameters (confirmed against a real
// acceptance-test run: an unset htmlPosition sent as "" was rejected by
// CustomHtml's own field validator, which never happens for a key that's
// simply absent from the parameters map). A List-typed parameter is sent
// via matomo.ListParam, never joined into a single string - see
// matomo.ParamValue's doc comment for why. A ListOfObjects (real nested
// block) parameter is sent via matomo.ListOfObjectsParam, row by row; a
// single-key MULTI_TUPLE parameter (SingleKeyName set, e.g. domains) stays
// a flat list in the schema/model but is wire-encoded via
// matomo.WrapSingleKeyParam instead of matomo.ListParam - see
// matomo.ParamValue's doc comment for why Matomo needs this shape.
func (m *triggerElementvisibilityModel) ToParams() matomo.ParamsMap {
	p := matomo.ParamsMap{}
	p["selectionMethod"] = matomo.ScalarParam(m.SelectionMethod.ValueString())
	if !m.CssSelector.IsNull() && !m.CssSelector.IsUnknown() {
		p["cssSelector"] = matomo.ScalarParam(m.CssSelector.ValueString())
	}
	if !m.ElementId.IsNull() && !m.ElementId.IsUnknown() {
		p["elementId"] = matomo.ScalarParam(m.ElementId.ValueString())
	}
	p["fireTriggerWhen"] = matomo.ScalarParam(m.FireTriggerWhen.ValueString())
	if !m.MinPercentVisible.IsNull() && !m.MinPercentVisible.IsUnknown() {
		p["minPercentVisible"] = matomo.ScalarParam(paramInt64String(m.MinPercentVisible.ValueInt64()))
	}
	if !m.ObserveDomChanges.IsNull() && !m.ObserveDomChanges.IsUnknown() {
		p["observeDomChanges"] = matomo.ScalarParam(paramBoolString(m.ObserveDomChanges.ValueBool()))
	}
	return p
}

// FromParams mirrors ToParams' omission convention on the way back: a key
// absent from Matomo's response (an unset Optional parameter) must decode
// to a null value, not a zero value ("", false, 0) - decoding it to a
// zero value made every unset Optional parameter round-trip as a
// non-null empty value, which never matched the null the config itself
// produced and left Terraform reporting a perpetual "refresh plan not
// empty" diff on every generated resource with an unset Optional field
// (confirmed against a real acceptance-test run).
func (m *triggerElementvisibilityModel) FromParams(p matomo.ParamsMap) {
	m.SelectionMethod = types.StringValue(p["selectionMethod"].Scalar)
	if v, ok := p["cssSelector"]; ok {
		m.CssSelector = types.StringValue(v.Scalar)
	} else {
		m.CssSelector = types.StringNull()
	}
	if v, ok := p["elementId"]; ok {
		m.ElementId = types.StringValue(v.Scalar)
	} else {
		m.ElementId = types.StringNull()
	}
	m.FireTriggerWhen = types.StringValue(p["fireTriggerWhen"].Scalar)
	if v, ok := p["minPercentVisible"]; ok {
		m.MinPercentVisible = types.Int64Value(paramInt64Value(v.Scalar))
	} else {
		m.MinPercentVisible = types.Int64Null()
	}
	if v, ok := p["observeDomChanges"]; ok {
		m.ObserveDomChanges = types.BoolValue(paramBoolValue(v.Scalar))
	} else {
		m.ObserveDomChanges = types.BoolNull()
	}
}

func (m *triggerElementvisibilityModel) Common() *typedTriggerCommon {
	return &m.typedTriggerCommon
}

func newTriggerElementvisibilityModel() typedTriggerModel {
	return &triggerElementvisibilityModel{}
}
