// Code generated by tools/gen. DO NOT EDIT.

package provider

import (
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/nicole-ashley/terraform-provider-matomo/internal/matomo"
)

type variableDomelementModel struct {
	typedVariableCommon
	SelectionMethod types.String `tfsdk:"selection_method"`
	CssSelector     types.String `tfsdk:"css_selector"`
	ElementId       types.String `tfsdk:"element_id"`
	AttributeName   types.String `tfsdk:"attribute_name"`
}

func variableDomelementSchema() schema.Schema {
	return schema.Schema{
		Description: "Gets the value from a DOM element.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"container_id": schema.StringAttribute{
				Required:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
			},
			"name": schema.StringAttribute{
				Required: true,
			},
			"default_value": schema.StringAttribute{
				Optional:      true,
				Computed:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"selection_method": schema.StringAttribute{
				Required:    true,
				Description: "Select the way you want to identify the element you want to read the value from.",
				Validators: []validator.String{
					stringvalidator.OneOf("cssSelector", "elementId"),
				},
			},
			"css_selector": schema.StringAttribute{
				Required: false,
				Optional: true,
				// Computed + UseStateForUnknown: Matomo can return a
				// non-empty default for this field even when it was never
				// sent (e.g. a boolean parameter defaulting to false
				// server-side), which a bare Optional attribute can't
				// reconcile against an unset (null) config without
				// reporting a spurious diff on every subsequent plan - see
				// NeedsBoolPlanModifierImport's doc comment in
				// tools/gen/emit.go.
				Computed:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
				Description:   "A CSS selector allows you to select an element by id, className, element names, etc. If multiple elements match this selector, the first matching element will be used to get the value from. Examples for valid selectors are \".classname\", \"#id\" or \"li a\".",
				Validators: []validator.String{
					conditionRequiredValidator{Condition: matomo.EqNode{Field: "selection_method", Value: "cssSelector", Negate: false}},
				},
			},
			"element_id": schema.StringAttribute{
				Required: false,
				Optional: true,
				// Computed + UseStateForUnknown: Matomo can return a
				// non-empty default for this field even when it was never
				// sent (e.g. a boolean parameter defaulting to false
				// server-side), which a bare Optional attribute can't
				// reconcile against an unset (null) config without
				// reporting a spurious diff on every subsequent plan - see
				// NeedsBoolPlanModifierImport's doc comment in
				// tools/gen/emit.go.
				Computed:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
				Description:   "The id attribute specifies a unique id for an HTML element. Insert here the value of an ID attribute of any element within your website.",
				Validators: []validator.String{
					conditionRequiredValidator{Condition: matomo.EqNode{Field: "selection_method", Value: "elementId", Negate: false}},
				},
			},
			"attribute_name": schema.StringAttribute{
				Required: false,
				Optional: true,
				// Computed + UseStateForUnknown: Matomo can return a
				// non-empty default for this field even when it was never
				// sent (e.g. a boolean parameter defaulting to false
				// server-side), which a bare Optional attribute can't
				// reconcile against an unset (null) config without
				// reporting a spurious diff on every subsequent plan - see
				// NeedsBoolPlanModifierImport's doc comment in
				// tools/gen/emit.go.
				Computed:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
				Description:   "",
			},
		},
	}
}

func (m *variableDomelementModel) Meta() typedMeta {
	return typedMeta{
		TypeID:       "DomElement",
		ResourceName: "matomo_tagmanager_variable_domelement",
		Schema:       variableDomelementSchema(),
	}
}

// ToParams only includes a key for an Optional parameter when it's
// actually set - sending an empty string for an unset Optional field
// (rather than omitting the key) was rejected by Matomo's own validation
// on live enum/format-constrained parameters (confirmed against a real
// acceptance-test run: an unset htmlPosition sent as "" was rejected by
// CustomHtml's own field validator, which never happens for a key that's
// simply absent from the parameters map).
func (m *variableDomelementModel) ToParams() map[string]string {
	p := map[string]string{}
	p["selectionMethod"] = m.SelectionMethod.ValueString()
	if !m.CssSelector.IsNull() && !m.CssSelector.IsUnknown() {
		p["cssSelector"] = m.CssSelector.ValueString()
	}
	if !m.ElementId.IsNull() && !m.ElementId.IsUnknown() {
		p["elementId"] = m.ElementId.ValueString()
	}
	if !m.AttributeName.IsNull() && !m.AttributeName.IsUnknown() {
		p["attributeName"] = m.AttributeName.ValueString()
	}
	return p
}

// FromParams mirrors ToParams' omission convention on the way back: a key
// absent from Matomo's response (an unset Optional parameter) must decode
// to a null value, not a zero value ("", false, 0) - decoding it to a
// zero value made every unset Optional parameter round-trip as a
// non-null empty value, which never matched the null the config itself
// produced and left Terraform reporting a perpetual "refresh plan not
// empty" diff on every generated resource with an unset Optional field
// (confirmed against a real acceptance-test run).
func (m *variableDomelementModel) FromParams(p map[string]string) {
	m.SelectionMethod = types.StringValue(p["selectionMethod"])
	if v, ok := p["cssSelector"]; ok {
		m.CssSelector = types.StringValue(v)
	} else {
		m.CssSelector = types.StringNull()
	}
	if v, ok := p["elementId"]; ok {
		m.ElementId = types.StringValue(v)
	} else {
		m.ElementId = types.StringNull()
	}
	if v, ok := p["attributeName"]; ok {
		m.AttributeName = types.StringValue(v)
	} else {
		m.AttributeName = types.StringNull()
	}
}

func (m *variableDomelementModel) Common() *typedVariableCommon {
	return &m.typedVariableCommon
}

func newVariableDomelementModel() typedVariableModel {
	return &variableDomelementModel{}
}
