// Code generated by tools/gen. DO NOT EDIT.

package provider

import (
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type triggerFormsubmitModel struct {
	ID          types.String `tfsdk:"id"`
	ContainerID types.String `tfsdk:"container_id"`
	Name        types.String `tfsdk:"name"`
}

func triggerFormsubmitSchema() schema.Schema {
	return schema.Schema{
		Description: "Triggered when any form is submitted.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"container_id": schema.StringAttribute{
				Required:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
			},
			"name": schema.StringAttribute{
				Required: true,
			},
		},
	}
}

func (m *triggerFormsubmitModel) Meta() typedMeta {
	return typedMeta{
		TypeID:       "FormSubmit",
		ResourceName: "matomo_tagmanager_trigger_formsubmit",
		Schema:       triggerFormsubmitSchema(),
	}
}

func (m *triggerFormsubmitModel) ToParams() map[string]string {
	return map[string]string{}
}

func (m *triggerFormsubmitModel) FromParams(p map[string]string) {
}

func newTriggerFormsubmitModel() typedModel {
	return &triggerFormsubmitModel{}
}
