package provider

import (
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

// This file is generated by tools/gen only if it does not already exist.
// Once present, tools/gen never overwrites it - edit freely to add real
// assertions (this scaffold only proves create+read-back with placeholder
// values).
func TestAccTagMatomo_createAndReadBack(t *testing.T) {
	testAccPreCheck(t)
	resourceName := "matomo_tagmanager_tag_matomo.test"

	resource.Test(t, resource.TestCase{
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: testAccTagMatomoConfig(),
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttrSet(resourceName, "id"),
				),
			},
			{
				ResourceName:      resourceName,
				ImportState:       true,
				ImportStateVerify: true,
			},
		},
	})
}

func testAccTagMatomoConfig() string {
	return `
provider "matomo" {}

resource "matomo_site" "test" {
  name = "Generated Matomo Acceptance Site"
  urls = ["https://acc-generated-matomo.example.com"]
}

resource "matomo_tagmanager_container" "test" {
  site_id = matomo_site.test.id
  context = "web"
  name    = "Generated Matomo Acceptance Container"
}

resource "matomo_tagmanager_trigger" "test" {
  container_id = matomo_tagmanager_container.test.id
  type         = "PageView"
  name         = "Generated Matomo Acceptance Trigger"
}

resource "matomo_tagmanager_tag_matomo" "test" {
  container_id = matomo_tagmanager_container.test.id
  name         = "generated-test-matomo"
  fire_trigger_ids = [matomo_tagmanager_trigger.test.id]
  matomo_config = "test-value"
  tracking_type = "event"
  event_category = "test-value"
  event_action = "test-value"
}
`
}
