// Code generated by tools/gen. DO NOT EDIT.

package provider

import (
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type tagZendeskchatModel struct {
	typedTagCommon
	ZendeskChatId types.String `tfsdk:"zendesk_chat_id"`
}

func tagZendeskchatSchema() schema.Schema {
	return schema.Schema{
		Description: "Reach your customers, instantly via web, mobile, and messaging.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"container_id": schema.StringAttribute{
				Required:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
			},
			"name": schema.StringAttribute{
				Required: true,
			},
			"status": schema.StringAttribute{
				Optional:      true,
				Computed:      true,
				Validators:    []validator.String{stringvalidator.OneOf("active", "paused")},
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"fire_trigger_ids": schema.ListAttribute{
				Required:    true,
				ElementType: types.StringType,
			},
			"block_trigger_ids": schema.ListAttribute{
				Optional:    true,
				ElementType: types.StringType,
			},
			"zendesk_chat_id": schema.StringAttribute{
				Required:    true,
				Description: "You can get the Site ID by logging into Zendesk Chat, going to \"Settings\" and clicking on \"Widget\". The Site ID has typically about 32 characters and is the text coming directly after \"https://v2.zopim.com/?\", for example \"123451c27295ad739e46b6b1\".",
			},
		},
	}
}

func (m *tagZendeskchatModel) Meta() typedMeta {
	return typedMeta{
		TypeID:       "ZendeskChat",
		ResourceName: "matomo_tagmanager_tag_zendeskchat",
		Schema:       tagZendeskchatSchema(),
	}
}

// ToParams only includes a key for an Optional parameter when it's
// actually set - sending an empty string for an unset Optional field
// (rather than omitting the key) was rejected by Matomo's own validation
// on live enum/format-constrained parameters (confirmed against a real
// acceptance-test run: an unset htmlPosition sent as "" was rejected by
// CustomHtml's own field validator, which never happens for a key that's
// simply absent from the parameters map).
func (m *tagZendeskchatModel) ToParams() map[string]string {
	p := map[string]string{}
	p["zendeskChatId"] = m.ZendeskChatId.ValueString()
	return p
}

// FromParams mirrors ToParams' omission convention on the way back: a key
// absent from Matomo's response (an unset Optional parameter) must decode
// to a null value, not a zero value ("", false, 0) - decoding it to a
// zero value made every unset Optional parameter round-trip as a
// non-null empty value, which never matched the null the config itself
// produced and left Terraform reporting a perpetual "refresh plan not
// empty" diff on every generated resource with an unset Optional field
// (confirmed against a real acceptance-test run).
func (m *tagZendeskchatModel) FromParams(p map[string]string) {
	m.ZendeskChatId = types.StringValue(p["zendeskChatId"])
}

func (m *tagZendeskchatModel) Common() *typedTagCommon {
	return &m.typedTagCommon
}

func newTagZendeskchatModel() typedTagModel {
	return &tagZendeskchatModel{}
}
