// Code generated by tools/gen. DO NOT EDIT.

package provider

import (
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type tagOnetrustModel struct {
	typedTagCommon
	Domain types.String `tfsdk:"domain"`
}

func tagOnetrustSchema() schema.Schema {
	return schema.Schema{
		Description: "The OneTrust Consent Management Platform orchestrates the collection of consent across web, mobile, and CTV.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"container_id": schema.StringAttribute{
				Required:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
			},
			"name": schema.StringAttribute{
				Required: true,
			},
			"status": schema.StringAttribute{
				Optional:      true,
				Computed:      true,
				Validators:    []validator.String{stringvalidator.OneOf("active", "paused")},
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"fire_trigger_ids": schema.ListAttribute{
				Required:    true,
				ElementType: types.StringType,
			},
			"block_trigger_ids": schema.ListAttribute{
				Optional:    true,
				ElementType: types.StringType,
			},
			"domain": schema.StringAttribute{
				Required:    true,
				Description: "To find your OneTrust data-domain-script, log into OneTrust, navigate to Scripts, select your desired domain, select the Production Scripts tab, and  find your data-domain-script in the Production CDN Script.",
			},
		},
	}
}

func (m *tagOnetrustModel) Meta() typedMeta {
	return typedMeta{
		TypeID:       "OneTrust",
		ResourceName: "matomo_tagmanager_tag_onetrust",
		Schema:       tagOnetrustSchema(),
	}
}

func (m *tagOnetrustModel) ToParams() map[string]string {
	return map[string]string{
		"domain": m.Domain.ValueString(),
	}
}

func (m *tagOnetrustModel) FromParams(p map[string]string) {
	m.Domain = types.StringValue(p["domain"])
}

func (m *tagOnetrustModel) Common() *typedTagCommon {
	return &m.typedTagCommon
}

func newTagOnetrustModel() typedTagModel {
	return &tagOnetrustModel{}
}
