// Code generated by tools/gen. DO NOT EDIT.

package provider

import (
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type tagBinguetModel struct {
	ID              types.String   `tfsdk:"id"`
	ContainerID     types.String   `tfsdk:"container_id"`
	Name            types.String   `tfsdk:"name"`
	Status          types.String   `tfsdk:"status"`
	FireTriggerIDs  []types.String `tfsdk:"fire_trigger_ids"`
	BlockTriggerIDs []types.String `tfsdk:"block_trigger_ids"`
	BingAdID        types.String   `tfsdk:"bing_ad_id"`
}

func tagBinguetSchema() schema.Schema {
	return schema.Schema{
		Description: "Adds the Bing Ads Universal Event Tracking Tag to your website so you can apply conversion tracking to your Bing ad campaigns.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"container_id": schema.StringAttribute{
				Required:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
			},
			"name": schema.StringAttribute{
				Required: true,
			},
			"status": schema.StringAttribute{
				Optional:      true,
				Computed:      true,
				Validators:    []validator.String{stringvalidator.OneOf("active", "paused")},
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"fire_trigger_ids": schema.ListAttribute{
				Required:    true,
				ElementType: types.StringType,
			},
			"block_trigger_ids": schema.ListAttribute{
				Optional:    true,
				ElementType: types.StringType,
			},
			"bing_ad_id": schema.StringAttribute{
				Required:    true,
				Description: "You can find the Bing Ad ID when creating a new tracking code in the Bing Ad Campaign Manager.",
			},
		},
	}
}

func (m *tagBinguetModel) Meta() typedMeta {
	return typedMeta{
		TypeID:       "BingUET",
		ResourceName: "matomo_tagmanager_tag_binguet",
		Schema:       tagBinguetSchema(),
	}
}

func (m *tagBinguetModel) ToParams() map[string]string {
	return map[string]string{
		"bingAdID": m.BingAdID.ValueString(),
	}
}

func (m *tagBinguetModel) FromParams(p map[string]string) {
	m.BingAdID = types.StringValue(p["bingAdID"])
}

func newTagBinguetModel() typedModel {
	return &tagBinguetModel{}
}
