// Code generated by tools/gen. DO NOT EDIT.

package provider

import (
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type variableCustomjsfunctionModel struct {
	typedVariableCommon
	JsFunction types.String `tfsdk:"js_function"`
}

func variableCustomjsfunctionSchema() schema.Schema {
	return schema.Schema{
		Description: "Executes a custom JavaScript function to retrieve the value.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"container_id": schema.StringAttribute{
				Required:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
			},
			"name": schema.StringAttribute{
				Required: true,
			},
			"default_value": schema.StringAttribute{
				Optional: true,
			},
			"js_function": schema.StringAttribute{
				Required:    true,
				Description: "The value should start with \"function() { \" and end with \"return yourValue; }\". You have to define a function and return a value. We highly recommend to test the pasted JavaScript function to avoid JavaScript errors on your website.",
			},
		},
	}
}

func (m *variableCustomjsfunctionModel) Meta() typedMeta {
	return typedMeta{
		TypeID:       "CustomJsFunction",
		ResourceName: "matomo_tagmanager_variable_customjsfunction",
		Schema:       variableCustomjsfunctionSchema(),
	}
}

func (m *variableCustomjsfunctionModel) ToParams() map[string]string {
	return map[string]string{
		"jsFunction": m.JsFunction.ValueString(),
	}
}

func (m *variableCustomjsfunctionModel) FromParams(p map[string]string) {
	m.JsFunction = types.StringValue(p["jsFunction"])
}

func (m *variableCustomjsfunctionModel) Common() *typedVariableCommon {
	return &m.typedVariableCommon
}

func newVariableCustomjsfunctionModel() typedVariableModel {
	return &variableCustomjsfunctionModel{}
}
