// Code generated by tools/gen. DO NOT EDIT.

package provider

import (
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type tagMatomoModel struct {
	typedTagCommon
	MatomoConfig              types.String   `tfsdk:"matomo_config"`
	TrackingType              types.String   `tfsdk:"tracking_type"`
	IdGoal                    types.String   `tfsdk:"id_goal"`
	GoalCustomRevenue         types.String   `tfsdk:"goal_custom_revenue"`
	DocumentTitle             types.String   `tfsdk:"document_title"`
	CustomUrl                 types.String   `tfsdk:"custom_url"`
	IsEcommerceView           types.Bool     `tfsdk:"is_ecommerce_view"`
	ProductSKU                types.String   `tfsdk:"product_sku"`
	ProductName               types.String   `tfsdk:"product_name"`
	CategoryName              types.String   `tfsdk:"category_name"`
	Price                     types.String   `tfsdk:"price"`
	EventCategory             types.String   `tfsdk:"event_category"`
	EventAction               types.String   `tfsdk:"event_action"`
	EventName                 types.String   `tfsdk:"event_name"`
	EventValue                types.String   `tfsdk:"event_value"`
	CustomDimensions          []types.String `tfsdk:"custom_dimensions"`
	AreCustomDimensionsSticky types.Bool     `tfsdk:"are_custom_dimensions_sticky"`
}

func tagMatomoSchema() schema.Schema {
	return schema.Schema{
		Description: "Matomo is the leading open source analytics platform.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"container_id": schema.StringAttribute{
				Required:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
			},
			"name": schema.StringAttribute{
				Required: true,
			},
			"status": schema.StringAttribute{
				Optional:      true,
				Computed:      true,
				Validators:    []validator.String{stringvalidator.OneOf("active", "paused")},
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"fire_trigger_ids": schema.ListAttribute{
				Required:    true,
				ElementType: types.StringType,
			},
			"block_trigger_ids": schema.ListAttribute{
				Optional:    true,
				ElementType: types.StringType,
			},
			"matomo_config": schema.StringAttribute{
				Required:    true,
				Description: "Assign a Matomo configuration in order to track data into a specific site.",
			},
			"tracking_type": schema.StringAttribute{
				Required:    true,
				Description: "Choose which action should be executed when this tag is fired.",
				Validators:  []validator.String{stringvalidator.OneOf("event", "goal", "initialise", "pageview")},
			},
			"id_goal": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Description: "The ID of the goal you want to track manually.",
			},
			"goal_custom_revenue": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Description: "The estimated revenue value to track when the goal is triggered manually. As this value will be used in a calculation, it must either be a numeric value or it must reference a variable that contains a numeric value. If this field is empty or references a variable that doesn't contain a valid numeric value, the value will default to the revenue configured as part of the goal being triggered. A valid numeric value is something like 2430 or 2430.00 (note the absence of commas).",
			},
			"document_title": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Description: "Optionally, specify a custom document title which should be tracked instead of the default document title.",
			},
			"custom_url": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Description: "Optionally, specify a custom URL which should be tracked instead of the current location.",
			},
			"is_ecommerce_view": schema.BoolAttribute{
				Required:    false,
				Optional:    true,
				Description: "",
			},
			"product_sku": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Description: "Item's SKU code being viewed. On a category page this should be empty.",
			},
			"product_name": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Description: "Item's Name being viewed. On a category page this should be empty.",
			},
			"category_name": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Description: "Category page being viewed. On an item's page, this is the item's category.",
			},
			"price": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Description: "Item's display price, not used in standard Matomo reports, but output in API product reports.",
			},
			"event_category": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Description: "The event's category, for example Videos, Music, Games…",
			},
			"event_action": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Description: "The event's action, for example Play, Pause, Duration, Add Playlist, Downloaded, Clicked…",
			},
			"event_name": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Description: "The event's object Name, for example a particular Movie name, or Song name, or File name…",
			},
			"event_value": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Description: "Specify a value or choose a variable.",
			},
			"custom_dimensions": schema.ListAttribute{
				ElementType: types.StringType,
				Required:    false,
				Optional:    true,
				Description: "Optionally, set a value for one or more custom dimensions.",
			},
			"are_custom_dimensions_sticky": schema.BoolAttribute{
				Required:    false,
				Optional:    true,
				Description: "",
			},
		},
	}
}

func (m *tagMatomoModel) Meta() typedMeta {
	return typedMeta{
		TypeID:       "Matomo",
		ResourceName: "matomo_tagmanager_tag_matomo",
		Schema:       tagMatomoSchema(),
	}
}

// ToParams only includes a key for an Optional parameter when it's
// actually set - sending an empty string for an unset Optional field
// (rather than omitting the key) was rejected by Matomo's own validation
// on live enum/format-constrained parameters (confirmed against a real
// acceptance-test run: an unset htmlPosition sent as "" was rejected by
// CustomHtml's own field validator, which never happens for a key that's
// simply absent from the parameters map).
func (m *tagMatomoModel) ToParams() map[string]string {
	p := map[string]string{}
	p["matomoConfig"] = m.MatomoConfig.ValueString()
	p["trackingType"] = m.TrackingType.ValueString()
	if !m.IdGoal.IsNull() && !m.IdGoal.IsUnknown() {
		p["idGoal"] = m.IdGoal.ValueString()
	}
	if !m.GoalCustomRevenue.IsNull() && !m.GoalCustomRevenue.IsUnknown() {
		p["goalCustomRevenue"] = m.GoalCustomRevenue.ValueString()
	}
	if !m.DocumentTitle.IsNull() && !m.DocumentTitle.IsUnknown() {
		p["documentTitle"] = m.DocumentTitle.ValueString()
	}
	if !m.CustomUrl.IsNull() && !m.CustomUrl.IsUnknown() {
		p["customUrl"] = m.CustomUrl.ValueString()
	}
	if !m.IsEcommerceView.IsNull() && !m.IsEcommerceView.IsUnknown() {
		p["isEcommerceView"] = paramBoolString(m.IsEcommerceView.ValueBool())
	}
	if !m.ProductSKU.IsNull() && !m.ProductSKU.IsUnknown() {
		p["productSKU"] = m.ProductSKU.ValueString()
	}
	if !m.ProductName.IsNull() && !m.ProductName.IsUnknown() {
		p["productName"] = m.ProductName.ValueString()
	}
	if !m.CategoryName.IsNull() && !m.CategoryName.IsUnknown() {
		p["categoryName"] = m.CategoryName.ValueString()
	}
	if !m.Price.IsNull() && !m.Price.IsUnknown() {
		p["price"] = m.Price.ValueString()
	}
	if !m.EventCategory.IsNull() && !m.EventCategory.IsUnknown() {
		p["eventCategory"] = m.EventCategory.ValueString()
	}
	if !m.EventAction.IsNull() && !m.EventAction.IsUnknown() {
		p["eventAction"] = m.EventAction.ValueString()
	}
	if !m.EventName.IsNull() && !m.EventName.IsUnknown() {
		p["eventName"] = m.EventName.ValueString()
	}
	if !m.EventValue.IsNull() && !m.EventValue.IsUnknown() {
		p["eventValue"] = m.EventValue.ValueString()
	}
	if m.CustomDimensions != nil {
		p["customDimensions"] = paramListString(m.CustomDimensions)
	}
	if !m.AreCustomDimensionsSticky.IsNull() && !m.AreCustomDimensionsSticky.IsUnknown() {
		p["areCustomDimensionsSticky"] = paramBoolString(m.AreCustomDimensionsSticky.ValueBool())
	}
	return p
}

// FromParams mirrors ToParams' omission convention on the way back: a key
// absent from Matomo's response (an unset Optional parameter) must decode
// to a null value, not a zero value ("", false, 0) - decoding it to a
// zero value made every unset Optional parameter round-trip as a
// non-null empty value, which never matched the null the config itself
// produced and left Terraform reporting a perpetual "refresh plan not
// empty" diff on every generated resource with an unset Optional field
// (confirmed against a real acceptance-test run).
func (m *tagMatomoModel) FromParams(p map[string]string) {
	m.MatomoConfig = types.StringValue(p["matomoConfig"])
	m.TrackingType = types.StringValue(p["trackingType"])
	if v, ok := p["idGoal"]; ok {
		m.IdGoal = types.StringValue(v)
	} else {
		m.IdGoal = types.StringNull()
	}
	if v, ok := p["goalCustomRevenue"]; ok {
		m.GoalCustomRevenue = types.StringValue(v)
	} else {
		m.GoalCustomRevenue = types.StringNull()
	}
	if v, ok := p["documentTitle"]; ok {
		m.DocumentTitle = types.StringValue(v)
	} else {
		m.DocumentTitle = types.StringNull()
	}
	if v, ok := p["customUrl"]; ok {
		m.CustomUrl = types.StringValue(v)
	} else {
		m.CustomUrl = types.StringNull()
	}
	if v, ok := p["isEcommerceView"]; ok {
		m.IsEcommerceView = types.BoolValue(paramBoolValue(v))
	} else {
		m.IsEcommerceView = types.BoolNull()
	}
	if v, ok := p["productSKU"]; ok {
		m.ProductSKU = types.StringValue(v)
	} else {
		m.ProductSKU = types.StringNull()
	}
	if v, ok := p["productName"]; ok {
		m.ProductName = types.StringValue(v)
	} else {
		m.ProductName = types.StringNull()
	}
	if v, ok := p["categoryName"]; ok {
		m.CategoryName = types.StringValue(v)
	} else {
		m.CategoryName = types.StringNull()
	}
	if v, ok := p["price"]; ok {
		m.Price = types.StringValue(v)
	} else {
		m.Price = types.StringNull()
	}
	if v, ok := p["eventCategory"]; ok {
		m.EventCategory = types.StringValue(v)
	} else {
		m.EventCategory = types.StringNull()
	}
	if v, ok := p["eventAction"]; ok {
		m.EventAction = types.StringValue(v)
	} else {
		m.EventAction = types.StringNull()
	}
	if v, ok := p["eventName"]; ok {
		m.EventName = types.StringValue(v)
	} else {
		m.EventName = types.StringNull()
	}
	if v, ok := p["eventValue"]; ok {
		m.EventValue = types.StringValue(v)
	} else {
		m.EventValue = types.StringNull()
	}
	if v, ok := p["customDimensions"]; ok {
		m.CustomDimensions = paramListValue(v)
	} else {
		m.CustomDimensions = nil
	}
	if v, ok := p["areCustomDimensionsSticky"]; ok {
		m.AreCustomDimensionsSticky = types.BoolValue(paramBoolValue(v))
	} else {
		m.AreCustomDimensionsSticky = types.BoolNull()
	}
}

func (m *tagMatomoModel) Common() *typedTagCommon {
	return &m.typedTagCommon
}

func newTagMatomoModel() typedTagModel {
	return &tagMatomoModel{}
}
