// Code generated by tools/gen. DO NOT EDIT.

package provider

import (
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type triggerScrollreachModel struct {
	typedTriggerCommon
	ScrollType types.String `tfsdk:"scroll_type"`
	Pixels     types.Int64  `tfsdk:"pixels"`
	Percentage types.Int64  `tfsdk:"percentage"`
}

func triggerScrollreachSchema() schema.Schema {
	return schema.Schema{
		Description: "Triggered as soon as the user scrolls to a certain position.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"container_id": schema.StringAttribute{
				Required:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
			},
			"name": schema.StringAttribute{
				Required: true,
			},
			"scroll_type": schema.StringAttribute{
				Required:    true,
				Description: "",
				Validators: []validator.String{
					stringvalidator.OneOf("horizontalpercentage", "horizontalpixel", "verticalpercentage", "verticalpixel"),
				},
			},
			"pixels": schema.Int64Attribute{
				Required:    false,
				Optional:    true,
				Description: "The amount in pixels that needs to be visible of this element depending on the selected scroll match type.",
			},
			"percentage": schema.Int64Attribute{
				Required:    false,
				Optional:    true,
				Description: "You can specify any number between 1 and 100. If you specify 50, then it means the element needs to be at least 50% visible depending on the scroll match type.",
			},
		},
	}
}

func (m *triggerScrollreachModel) Meta() typedMeta {
	return typedMeta{
		TypeID:       "ScrollReach",
		ResourceName: "matomo_tagmanager_trigger_scrollreach",
		Schema:       triggerScrollreachSchema(),
	}
}

// ToParams only includes a key for an Optional parameter when it's
// actually set - sending an empty string for an unset Optional field
// (rather than omitting the key) was rejected by Matomo's own validation
// on live enum/format-constrained parameters (confirmed against a real
// acceptance-test run: an unset htmlPosition sent as "" was rejected by
// CustomHtml's own field validator, which never happens for a key that's
// simply absent from the parameters map).
func (m *triggerScrollreachModel) ToParams() map[string]string {
	p := map[string]string{}
	p["scrollType"] = m.ScrollType.ValueString()
	if !m.Pixels.IsNull() && !m.Pixels.IsUnknown() {
		p["pixels"] = paramInt64String(m.Pixels.ValueInt64())
	}
	if !m.Percentage.IsNull() && !m.Percentage.IsUnknown() {
		p["percentage"] = paramInt64String(m.Percentage.ValueInt64())
	}
	return p
}

// FromParams mirrors ToParams' omission convention on the way back: a key
// absent from Matomo's response (an unset Optional parameter) must decode
// to a null value, not a zero value ("", false, 0) - decoding it to a
// zero value made every unset Optional parameter round-trip as a
// non-null empty value, which never matched the null the config itself
// produced and left Terraform reporting a perpetual "refresh plan not
// empty" diff on every generated resource with an unset Optional field
// (confirmed against a real acceptance-test run).
func (m *triggerScrollreachModel) FromParams(p map[string]string) {
	m.ScrollType = types.StringValue(p["scrollType"])
	if v, ok := p["pixels"]; ok {
		m.Pixels = types.Int64Value(paramInt64Value(v))
	} else {
		m.Pixels = types.Int64Null()
	}
	if v, ok := p["percentage"]; ok {
		m.Percentage = types.Int64Value(paramInt64Value(v))
	} else {
		m.Percentage = types.Int64Null()
	}
}

func (m *triggerScrollreachModel) Common() *typedTriggerCommon {
	return &m.typedTriggerCommon
}

func newTriggerScrollreachModel() typedTriggerModel {
	return &triggerScrollreachModel{}
}
