// Code generated by tools/gen. DO NOT EDIT.

package provider

import (
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type triggerElementvisibilityModel struct {
	typedTriggerCommon
	SelectionMethod   types.String `tfsdk:"selection_method"`
	CssSelector       types.String `tfsdk:"css_selector"`
	ElementId         types.String `tfsdk:"element_id"`
	FireTriggerWhen   types.String `tfsdk:"fire_trigger_when"`
	MinPercentVisible types.Int64  `tfsdk:"min_percent_visible"`
	ObserveDomChanges types.Bool   `tfsdk:"observe_dom_changes"`
}

func triggerElementvisibilitySchema() schema.Schema {
	return schema.Schema{
		Description: "Triggered when a specific element becomes visible.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"container_id": schema.StringAttribute{
				Required:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
			},
			"name": schema.StringAttribute{
				Required: true,
			},
			"selection_method": schema.StringAttribute{
				Required:    true,
				Description: "Select the way you want to identify an element you want to select.",
				Validators:  []validator.String{stringvalidator.OneOf("cssSelector", "elementId")},
			},
			"css_selector": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Description: "A CSS selector allows you to select an element by id, className, element names, etc. If multiple elements match this selector, the first matching element will be used to get the value from. Examples for valid selectors are \".classname\", \"#id\" or \"li a\".",
			},
			"element_id": schema.StringAttribute{
				Required:    false,
				Optional:    true,
				Description: "The id attribute specifies a unique id for an HTML element. Insert here the value of an ID attribute of any element within your website.",
			},
			"fire_trigger_when": schema.StringAttribute{
				Required:    true,
				Description: "",
				Validators:  []validator.String{stringvalidator.OneOf("every", "onceElement", "oncePage")},
			},
			"min_percent_visible": schema.Int64Attribute{
				Required:    false,
				Optional:    true,
				Description: "",
			},
			"observe_dom_changes": schema.BoolAttribute{
				Required:    false,
				Optional:    true,
				Description: "",
			},
		},
	}
}

func (m *triggerElementvisibilityModel) Meta() typedMeta {
	return typedMeta{
		TypeID:       "ElementVisibility",
		ResourceName: "matomo_tagmanager_trigger_elementvisibility",
		Schema:       triggerElementvisibilitySchema(),
	}
}

// ToParams only includes a key for an Optional parameter when it's
// actually set - sending an empty string for an unset Optional field
// (rather than omitting the key) was rejected by Matomo's own validation
// on live enum/format-constrained parameters (confirmed against a real
// acceptance-test run: an unset htmlPosition sent as "" was rejected by
// CustomHtml's own field validator, which never happens for a key that's
// simply absent from the parameters map).
func (m *triggerElementvisibilityModel) ToParams() map[string]string {
	p := map[string]string{}
	p["selectionMethod"] = m.SelectionMethod.ValueString()
	if !m.CssSelector.IsNull() && !m.CssSelector.IsUnknown() {
		p["cssSelector"] = m.CssSelector.ValueString()
	}
	if !m.ElementId.IsNull() && !m.ElementId.IsUnknown() {
		p["elementId"] = m.ElementId.ValueString()
	}
	p["fireTriggerWhen"] = m.FireTriggerWhen.ValueString()
	if !m.MinPercentVisible.IsNull() && !m.MinPercentVisible.IsUnknown() {
		p["minPercentVisible"] = paramInt64String(m.MinPercentVisible.ValueInt64())
	}
	if !m.ObserveDomChanges.IsNull() && !m.ObserveDomChanges.IsUnknown() {
		p["observeDomChanges"] = paramBoolString(m.ObserveDomChanges.ValueBool())
	}
	return p
}

func (m *triggerElementvisibilityModel) FromParams(p map[string]string) {
	m.SelectionMethod = types.StringValue(p["selectionMethod"])
	m.CssSelector = types.StringValue(p["cssSelector"])
	m.ElementId = types.StringValue(p["elementId"])
	m.FireTriggerWhen = types.StringValue(p["fireTriggerWhen"])
	m.MinPercentVisible = types.Int64Value(paramInt64Value(p["minPercentVisible"]))
	m.ObserveDomChanges = types.BoolValue(paramBoolValue(p["observeDomChanges"]))
}

func (m *triggerElementvisibilityModel) Common() *typedTriggerCommon {
	return &m.typedTriggerCommon
}

func newTriggerElementvisibilityModel() typedTriggerModel {
	return &triggerElementvisibilityModel{}
}
