// Code generated by tools/gen. DO NOT EDIT.

package provider

import (
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type tagCustomimageModel struct {
	typedTagCommon
	CustomImageSrc     types.String `tfsdk:"custom_image_src"`
	CacheBusterEnabled types.Bool   `tfsdk:"cache_buster_enabled"`
}

func tagCustomimageSchema() schema.Schema {
	return schema.Schema{
		Description: "Allows you to embed any image, for example a tracking pixel.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"container_id": schema.StringAttribute{
				Required:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
			},
			"name": schema.StringAttribute{
				Required: true,
			},
			"status": schema.StringAttribute{
				Optional:      true,
				Computed:      true,
				Validators:    []validator.String{stringvalidator.OneOf("active", "paused")},
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"fire_trigger_ids": schema.ListAttribute{
				Required:    true,
				ElementType: types.StringType,
			},
			"block_trigger_ids": schema.ListAttribute{
				Optional:    true,
				ElementType: types.StringType,
			},
			"custom_image_src": schema.StringAttribute{
				Required:    true,
				Description: "You can define any image URL. We recommend to define a URL that starts with \"//\" so it will work on HTTP and HTTPS pages. If your website only supports HTTPS, it should start with \"https://\".",
			},
			"cache_buster_enabled": schema.BoolAttribute{
				Required:    false,
				Optional:    true,
				Description: "Makes sure the image will be fetched again every time it is added to the page by adding a URL parameter to the image URL with a random value, for example \"?mtmcb=12345\"..",
			},
		},
	}
}

func (m *tagCustomimageModel) Meta() typedMeta {
	return typedMeta{
		TypeID:       "CustomImage",
		ResourceName: "matomo_tagmanager_tag_customimage",
		Schema:       tagCustomimageSchema(),
	}
}

func (m *tagCustomimageModel) ToParams() map[string]string {
	return map[string]string{
		"customImageSrc":     m.CustomImageSrc.ValueString(),
		"cacheBusterEnabled": paramBoolString(m.CacheBusterEnabled.ValueBool()),
	}
}

func (m *tagCustomimageModel) FromParams(p map[string]string) {
	m.CustomImageSrc = types.StringValue(p["customImageSrc"])
	m.CacheBusterEnabled = types.BoolValue(paramBoolValue(p["cacheBusterEnabled"]))
}

func (m *tagCustomimageModel) Common() *typedTagCommon {
	return &m.typedTagCommon
}

func newTagCustomimageModel() typedTagModel {
	return &tagCustomimageModel{}
}
