// Code generated by tools/gen. DO NOT EDIT.

package provider

import (
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/listplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type tagEmarsysModel struct {
	typedTagCommon
	MerchantId      types.String `tfsdk:"merchant_id"`
	CommandCategory types.String `tfsdk:"command_category"`
	CommandView     types.String `tfsdk:"command_view"`
	CommandTag      types.String `tfsdk:"command_tag"`
	CommandGo       types.Bool   `tfsdk:"command_go"`
}

func tagEmarsysSchema() schema.Schema {
	return schema.Schema{
		Description: "Emarsys is the largest independent marketing platform in the world.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"container_id": schema.StringAttribute{
				Required:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
			},
			"name": schema.StringAttribute{
				Required: true,
			},
			"status": schema.StringAttribute{
				Optional:      true,
				Computed:      true,
				Validators:    []validator.String{stringvalidator.OneOf("active", "paused")},
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"fire_trigger_ids": schema.ListAttribute{
				Required:    true,
				ElementType: types.StringType,
			},
			"block_trigger_ids": schema.ListAttribute{
				Optional:      true,
				Computed:      true,
				ElementType:   types.StringType,
				PlanModifiers: []planmodifier.List{listplanmodifier.UseStateForUnknown()},
			},
			"merchant_id": schema.StringAttribute{
				Required:    true,
				Description: "Your Emarsys Merchant ID",
			},
			"command_category": schema.StringAttribute{
				Required: false,
				Optional: true,
				// Computed + UseStateForUnknown: Matomo can return a
				// non-empty default for this field even when it was never
				// sent (e.g. a boolean parameter defaulting to false
				// server-side), which a bare Optional attribute can't
				// reconcile against an unset (null) config without
				// reporting a spurious diff on every subsequent plan - see
				// NeedsBoolPlanModifierImport's doc comment in
				// tools/gen/emit.go.
				Computed:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
				Description:   "Report the category currently browsed by the visitor.",
			},
			"command_view": schema.StringAttribute{
				Required: false,
				Optional: true,
				// Computed + UseStateForUnknown: Matomo can return a
				// non-empty default for this field even when it was never
				// sent (e.g. a boolean parameter defaulting to false
				// server-side), which a bare Optional attribute can't
				// reconcile against an unset (null) config without
				// reporting a spurious diff on every subsequent plan - see
				// NeedsBoolPlanModifierImport's doc comment in
				// tools/gen/emit.go.
				Computed:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
				Description:   "Report a product view.",
			},
			"command_tag": schema.StringAttribute{
				Required: false,
				Optional: true,
				// Computed + UseStateForUnknown: Matomo can return a
				// non-empty default for this field even when it was never
				// sent (e.g. a boolean parameter defaulting to false
				// server-side), which a bare Optional attribute can't
				// reconcile against an unset (null) config without
				// reporting a spurious diff on every subsequent plan - see
				// NeedsBoolPlanModifierImport's doc comment in
				// tools/gen/emit.go.
				Computed:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
				Description:   "Add an arbitrary tag to the current event. The tag is collected and can be accessed later from other Emarsys products.",
			},
			"command_go": schema.BoolAttribute{
				Required: false,
				Optional: true,
				// Computed + UseStateForUnknown: Matomo can return a
				// non-empty default for this field even when it was never
				// sent (e.g. a boolean parameter defaulting to false
				// server-side), which a bare Optional attribute can't
				// reconcile against an unset (null) config without
				// reporting a spurious diff on every subsequent plan - see
				// NeedsBoolPlanModifierImport's doc comment in
				// tools/gen/emit.go.
				Computed:      true,
				PlanModifiers: []planmodifier.Bool{boolplanmodifier.UseStateForUnknown()},
				Description:   "Execute commands in the queue, that is, send them to the recommender service for processing.",
			},
		},
	}
}

func (m *tagEmarsysModel) Meta() typedMeta {
	return typedMeta{
		TypeID:       "Emarsys",
		ResourceName: "matomo_tagmanager_tag_emarsys",
		Schema:       tagEmarsysSchema(),
	}
}

// ToParams only includes a key for an Optional parameter when it's
// actually set - sending an empty string for an unset Optional field
// (rather than omitting the key) was rejected by Matomo's own validation
// on live enum/format-constrained parameters (confirmed against a real
// acceptance-test run: an unset htmlPosition sent as "" was rejected by
// CustomHtml's own field validator, which never happens for a key that's
// simply absent from the parameters map).
func (m *tagEmarsysModel) ToParams() map[string]string {
	p := map[string]string{}
	p["merchantId"] = m.MerchantId.ValueString()
	if !m.CommandCategory.IsNull() && !m.CommandCategory.IsUnknown() {
		p["commandCategory"] = m.CommandCategory.ValueString()
	}
	if !m.CommandView.IsNull() && !m.CommandView.IsUnknown() {
		p["commandView"] = m.CommandView.ValueString()
	}
	if !m.CommandTag.IsNull() && !m.CommandTag.IsUnknown() {
		p["commandTag"] = m.CommandTag.ValueString()
	}
	if !m.CommandGo.IsNull() && !m.CommandGo.IsUnknown() {
		p["commandGo"] = paramBoolString(m.CommandGo.ValueBool())
	}
	return p
}

// FromParams mirrors ToParams' omission convention on the way back: a key
// absent from Matomo's response (an unset Optional parameter) must decode
// to a null value, not a zero value ("", false, 0) - decoding it to a
// zero value made every unset Optional parameter round-trip as a
// non-null empty value, which never matched the null the config itself
// produced and left Terraform reporting a perpetual "refresh plan not
// empty" diff on every generated resource with an unset Optional field
// (confirmed against a real acceptance-test run).
func (m *tagEmarsysModel) FromParams(p map[string]string) {
	m.MerchantId = types.StringValue(p["merchantId"])
	if v, ok := p["commandCategory"]; ok {
		m.CommandCategory = types.StringValue(v)
	} else {
		m.CommandCategory = types.StringNull()
	}
	if v, ok := p["commandView"]; ok {
		m.CommandView = types.StringValue(v)
	} else {
		m.CommandView = types.StringNull()
	}
	if v, ok := p["commandTag"]; ok {
		m.CommandTag = types.StringValue(v)
	} else {
		m.CommandTag = types.StringNull()
	}
	if v, ok := p["commandGo"]; ok {
		m.CommandGo = types.BoolValue(paramBoolValue(v))
	} else {
		m.CommandGo = types.BoolNull()
	}
}

func (m *tagEmarsysModel) Common() *typedTagCommon {
	return &m.typedTagCommon
}

func newTagEmarsysModel() typedTagModel {
	return &tagEmarsysModel{}
}
